Repository auth0/docs, pull requests merged in 2018-02, with the labels that each got.

#5676 Java Spring MVC, change port to 3000
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_setup.md
Labels: quickstart

#5675 Java web app, change port to 3000
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_setup.md
Labels: quickstart

#5719 Update _centralized_login.md
  articles/quickstart/spa/ember/_includes/_centralized_login.md
Labels: quickstart

#5716 Update setup.md
  snippets/server-platforms/apache/setup.md
Labels: quickstart

#5633 Native passwordless with universal login
  articles/_includes/_native_passwordless_warning.md
  articles/connections/passwordless/android-email.md
  articles/connections/passwordless/android-sms.md
  articles/connections/passwordless/android.md
  articles/connections/passwordless/index.md
  articles/connections/passwordless/ios-email-objc.md
  articles/connections/passwordless/ios-email-swift.md
  articles/connections/passwordless/ios-magic-link.md
  articles/connections/passwordless/ios-sms-objc.md
  articles/connections/passwordless/ios-sms-swift.md
  articles/connections/passwordless/native-passwordless-universal.md
  articles/libraries/auth0-android/passwordless.md
  articles/libraries/auth0-swift/passwordless.md
  articles/libraries/lock-android/v1/passwordless.md
  articles/libraries/lock-android/v2/passwordless-magic-link.md
  articles/libraries/lock-android/v2/passwordless.md
  articles/libraries/lock-ios/v1/passwordless.md
  articles/libraries/lock-ios/v2/passwordless.md
  config/sidebar.yml
  updates/2018-02-15.yml
Labels: ready-for-review

#5725 Add deprecation warning on GA landing/admin/dev
  articles/multifactor-authentication/google-auth/_deprecation-notice.md
  articles/multifactor-authentication/google-auth/admin-guide.md
  articles/multifactor-authentication/google-auth/dev-guide.md
  articles/multifactor-authentication/google-auth/google-landing.md
Labels: ready-for-review

#5720 Update snippets
  snippets/client-platforms/cyclejs/configure.md
  snippets/client-platforms/cyclejs/logout.md
  snippets/client-platforms/cyclejs/query.md
  snippets/client-platforms/cyclejs/setup.md
  snippets/client-platforms/cyclejs/use.md
Labels: quickstart

#5718 Update frontend.js
  snippets/server-apis/relay/frontend.md
Labels: quickstart

#5712 Fix snippets
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  snippets/client-platforms/vuejs/use.md
Labels: quickstart

#5738 Updating migrations page
  articles/migrations/index.md
Labels: ready-for-review

#5293 MFA API
  articles/api-auth/tutorials/multifactor-resource-owner-password.md
  articles/multifactor-authentication/api/challenges.md
  articles/multifactor-authentication/api/faq.md
  articles/multifactor-authentication/api/index.md
  articles/multifactor-authentication/api/manage.md
  articles/multifactor-authentication/api/oob.md
  articles/multifactor-authentication/api/otp.md
Labels: ready-for-review

#5722 Add docs for MFA unified API
  articles/api/authentication/api-authz/_get-token.md
Labels: ready-for-review

#5733 Update 01-login.md
  articles/quickstart/webapp/php/01-login.md
Labels: quickstart

#5763 MFA API
  articles/api/authentication/api-authz/_get-token.md
Labels: do-not-merge

#5764 Adding deprecation notices in libraries pages
  articles/_includes/_lock_auth0js_deprecations_notice.md
  articles/libraries/index.md
  articles/libraries/when-to-use-lock.md
  articles/support/matrix.md
Labels: ready-for-review

#5750 Fix typo in legacy flows
  articles/guides/migration-legacy-flows.md
Labels: ready-for-review

#5751 Using Lock w/ Appliance
  articles/appliance/infrastructure/faq.md
Labels: ready-for-review

#5756 Add explanatory sentence to CORS
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#5748 Appliance: GEO HA docs updates
  articles/appliance/geo-ha/index.md
Labels: ready-for-review

#5757 Add Client Logo text
  articles/clients/client-settings/_settings.md
Labels: ready-for-review

#5218 Improve Quickstart iOS - Calling APIs
  articles/quickstart/native/ios-objc/04-calling-apis.md
  articles/quickstart/native/ios-swift/04-calling-apis.md
Labels: quickstart

#5709 Adding version warnings to any versioned doc w/ deprecated Lock/Auth0.js
  articles/_includes/_lock-sdk.html
  articles/_includes/_version_warning_auth0js.md
  articles/_includes/_version_warning_lock.md
  articles/connections/passwordless/_older-version-alert.md
  articles/connections/passwordless/_setup-callback.md
  articles/connections/passwordless/_setup-cors.md
  articles/connections/passwordless/_setup-email.md
  articles/connections/passwordless/_setup-sms-twilio.md
  articles/connections/passwordless/_version_warning_auth0js.md
  articles/connections/passwordless/regular-web-app-email-code.md
  articles/connections/passwordless/regular-web-app-email-code/index.yml
  articles/connections/passwordless/regular-web-app-email-code/v7/index.md
  articles/connections/passwordless/regular-web-app-email-code/v9/index.md
  articles/connections/passwordless/regular-web-app-email-link.md
  articles/connections/passwordless/regular-web-app-email-link/index.yml
  articles/connections/passwordless/regular-web-app-email-link/v7/index.md
  articles/connections/passwordless/regular-web-app-email-link/v9/index.md
  articles/connections/passwordless/regular-web-app-sms.md
  articles/connections/passwordless/regular-web-app-sms/index.yml
  articles/connections/passwordless/regular-web-app-sms/v7/index.md
  articles/connections/passwordless/regular-web-app-sms/v9/index.md
  articles/connections/passwordless/spa-email-code.md
  articles/connections/passwordless/spa-email-code/index.yml
  articles/connections/passwordless/spa-email-code/v7/index.md
  articles/connections/passwordless/spa-email-code/v9/index.md
  articles/connections/passwordless/spa-email-link.md
  articles/connections/passwordless/spa-email-link/index.yml
  articles/connections/passwordless/spa-email-link/v7/index.md
  articles/connections/passwordless/spa-email-link/v8/index.md
  articles/connections/passwordless/spa-sms.md
  articles/connections/passwordless/spa-sms/index.yml
  articles/connections/passwordless/spa-sms/v7/index.md
  articles/connections/passwordless/spa-sms/v9/index.md
  articles/libraries/auth0js/v7/index.md
  articles/libraries/auth0js/v8/index.md
  articles/libraries/lock/_includes/_lock-version-9.md
  articles/libraries/lock/_includes/_lock-version.md
  articles/libraries/lock/v10/api.md
  articles/libraries/lock/v10/auth0js.md
  articles/libraries/lock/v10/authentication-modes.md
  articles/libraries/lock/v10/configuration.md
  articles/libraries/lock/v10/customizing-error-messages.md
  articles/libraries/lock/v10/i18n.md
  articles/libraries/lock/v10/index.md
  articles/libraries/lock/v10/new-features.md
  articles/libraries/lock/v10/selecting-the-connection-for-multiple-logins.md
  articles/libraries/lock/v10/sending-authentication-parameters.md
  articles/libraries/lock/v10/ui-customization.md
  articles/libraries/lock/v9/api.md
  articles/libraries/lock/v9/authentication-modes.md
  articles/libraries/lock/v9/configuration.md
  articles/libraries/lock/v9/customizing-error-messages.md
  articles/libraries/lock/v9/i18n.md
  articles/libraries/lock/v9/index.md
  articles/libraries/lock/v9/migration-guide.md
  articles/libraries/lock/v9/selecting-the-connection-for-multiple-logins.md
  articles/libraries/lock/v9/sending-authentication-parameters.md
  articles/libraries/lock/v9/ui-customization.md
  articles/libraries/lock/v9/using-a-refresh-token.md
  updates/2018-02-16.yml
Labels: ready-for-review

#5671 Further updates to documents about Lock with Passwordless
  articles/connections/passwordless/_init-passwordless-lock.md
  articles/hosted-pages/login/index.md
  articles/hosted-pages/login/lock-passwordless.md
  articles/link-accounts/user-initiated-linking.md
Labels: ready-for-review

#5770 Fix agreement abbreviations
  articles/compliance/gdpr/roles-responsibilities.md
Labels: ready-for-review

#5743 Add acs migration
  articles/users/migrations/azure-access-control.md
  config/sidebar.yml
  updates/2018-02-22.yml
Labels: ready-for-review

#5776 Fix broken link in AWS
  articles/integrations/aws-api-gateway/custom-authorizers/part-4.md
Labels: ready-for-review

#5754 Update API usage section with HAR snippets
  articles/quickstart/backend/_includes/_api_using.md
Labels: quickstart

#5777 Update symfony WebApp Samples
  articles/quickstart/webapp/symfony/01-login.md
  snippets/server-platforms/symfony/dependencies.md
  snippets/server-platforms/symfony/setup.md
Labels: quickstart

#5783 Fix CURL snippet
  articles/api/authorization-extension/_roles.md
Labels: ready-for-review

#5786 Edit doc: Calling your APIs with Auth0 tokens
  articles/api-auth/tutorials/adoption/api-tokens.md
Labels: ready-for-review

#5717 Breadcrumbs
  articles/extensions/authorization-extension/v2/implementation/_stepnav.html
  articles/extensions/authorization-extension/v2/implementation/configuration.md
  articles/extensions/authorization-extension/v2/implementation/installation.md
  articles/extensions/authorization-extension/v2/implementation/setup.md
  articles/getting-started/_stepnav.html
  articles/getting-started/dashboard-overview.md
  articles/getting-started/deployment-models.md
  articles/getting-started/overview.md
  articles/getting-started/the-basics.md
  articles/hooks/_stepnav.html
  articles/hooks/cli/_stepnav.html
  articles/hooks/cli/create-delete.md
  articles/hooks/cli/edit.md
  articles/hooks/cli/enable-disable.md
  articles/hooks/cli/index.md
  articles/hooks/cli/logs.md
  articles/hooks/dashboard/_stepnav.html
  articles/hooks/dashboard/create-delete.md
  articles/hooks/dashboard/edit.md
  articles/hooks/dashboard/enable-disable.md
  articles/hooks/dashboard/index.md
  articles/hooks/extensibility-points/_stepnav.html
  articles/hooks/extensibility-points/credentials-exchange.md
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/post-user-registration.md
  articles/hooks/extensibility-points/pre-user-registration.md
  articles/hooks/overview.md
  config/sidebar.yml
Labels: ready-for-review

#5788 Add missing quotes to literal parameters on snippet
  articles/tokens/id-token.md
Labels: ready-for-review

#5789 Adding note about checkSession triggering rules
  articles/libraries/_includes/_review_get_ssodata.md
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#5790 Add text indicating that Lock/Auth0.js are recommended for SPAs
  articles/libraries/auth0js/v9/index.md
  articles/libraries/lock/v11/index.md
Labels: ready-for-review

#5707 Adding Extending page with hook examples
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/how-does-it-work.md
  articles/cms/wordpress/index.md
  articles/cms/wordpress/installation.md
  articles/cms/wordpress/jwt-authentication.md
  articles/cms/wordpress/troubleshoot.md
  updates/2018-02-26.yml
Labels: ready-for-review

#5761 Change zoomable and remove backslashes (for html-to-react PR)
  CONTRIBUTING.md
  articles/appliance/appliance-overview.md
  articles/appliance/infrastructure/infrastructure-overview.md
  articles/guides/login/centralized-vs-embedded.md
  articles/protocols/saml/saml-apps/cisco-webex.md
  articles/protocols/saml/saml-apps/datadog.md
  articles/protocols/saml/saml-apps/egencia.md
  articles/protocols/saml/saml-apps/eloqua.md
  articles/protocols/saml/saml-apps/freshdesk.md
  articles/protocols/saml/saml-apps/google-apps.md
  articles/protocols/saml/saml-apps/hosted-graphite.md
  articles/protocols/saml/saml-apps/litmos.md
  articles/protocols/saml/saml-apps/pluralsight.md
  articles/protocols/saml/saml-apps/sprout-video.md
  articles/protocols/saml/saml-apps/tableau-server.md
  articles/protocols/saml/saml-apps/workday.md
  articles/quickstart/spa/cyclejs/01-login.md
Labels: do-not-merge

#5772 Update 01-authorization.md
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart

#5797 Add note on token issuer
  articles/integrations/aws-api-gateway/custom-authorizers/part-3.md
Labels: ready-for-review

#5640 Update Spring Security Java API for new structure
  articles/quickstart/backend/_includes/_api_endpoints.md
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/java-spring-security/02-using.md
  articles/quickstart/backend/java-spring-security/index.yml
Labels: quickstart
