Repository auth0/docs, pull requests merged in 2018-03, with the labels that each got.

#5796 Move single sign on integrations section
  articles/integrations/index.md
  articles/integrations/sso/_template.md
  articles/integrations/sso/ad-rms.md
  articles/integrations/sso/box.md
  articles/integrations/sso/cloudbees.md
  articles/integrations/sso/concur.md
  articles/integrations/sso/disqus.md
  articles/integrations/sso/dropbox.md
  articles/integrations/sso/dynamics-crm.md
  articles/integrations/sso/echosign.md
  articles/integrations/sso/egnyte.md
  articles/integrations/sso/index.md
  articles/integrations/sso/new-relic.md
  articles/integrations/sso/office-365.md
  articles/integrations/sso/salesforce.md
  articles/integrations/sso/sharepoint.md
  articles/integrations/sso/slack.md
  articles/integrations/sso/springcm.md
  articles/integrations/sso/zendesk.md
  articles/integrations/sso/zoom.md
  articles/sso/current/index.md
  articles/sso/current/setup.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#5771 Adjusted docs for Management API and state management.
  articles/libraries/auth0js/v8/index.md
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#5782 Remove beta markers from custom domains
  articles/custom-domains/index.md
  articles/custom-domains/self-managed-certificates.md
Labels: do-not-merge

#5787 Update flask api
  articles/quickstart/backend/python/01-authorization.md
  snippets/server-apis/python/use.md
Labels: quickstart

#5829 Add missing descriptions and JQuery logo
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/webapi-owin/01-authorization.md
  articles/quickstart/spa/jquery/index.yml
  media/platforms/jquery.svg
Labels: ready-for-review

#5826 add Client Authentication at sidebar
  articles/client-auth/current/index.md
  articles/client-auth/legacy/index.md
  config/sidebar.yml
Labels: do-not-merge

#5824 Fixing universal login URLs (from centralized) + redirects
  articles/api-auth/intro.md
  articles/cross-origin-authentication/index.md
  articles/guides/login/migrating-lock-v10-spa.md
  articles/guides/login/migrating-lock-v10-webapp.md
  articles/guides/login/migrating-lock-v9-spa-popup.md
  articles/guides/login/migrating-lock-v9-spa.md
  articles/guides/login/migrating-lock-v9-webapp.md
  articles/guides/login/migration-embedded-universal.md
  articles/guides/login/universal-vs-embedded.md
  config/redirects.js
Labels: ready-for-review

#5832 Updating table header to be more clear
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#5831 Add warning to user search doc
  articles/api/management/v2/user-search.md
Labels: ready-for-review

#5853 Angular Quick Start - update to remove angular2-jwt
  articles/quickstart/spa/angular2/03-calling-an-api.md
  articles/quickstart/spa/angular2/05-token-renewal.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/angular2/custom-login-form.md
  articles/quickstart/spa/angular2/embedded-login.md
  snippets/client-platforms/angular2/setup.md
Labels: ready-for-review

#5855 Add brief intro
  articles/design/using-auth0-with-multi-tenant-apps.md
Labels: ready-for-review

#5859 Fixed incorrect logout route code sample
  articles/quickstart/webapp/golang/01-login.md
Labels: quickstart

#5815 A couple of paragraphs were duplicated
  articles/quickstart/webapp/aspnet-core/v2/00-intro.md
Labels: quickstart, ready-for-review

#5865 Appliance Deployment Models: update custom domains
  articles/getting-started/deployment-models.md
Labels: do-not-merge

#5637 Update endpoints
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/backend/laravel/02-using.md
  articles/quickstart/backend/laravel/index.yml
Labels: quickstart

#5870 Update main.go
  articles/quickstart/backend/golang/01-authorization.md
Labels: quickstart

#5864 Update snippets
  articles/quickstart/backend/laravel/01-authorization.md
  snippets/server-apis/php-laravel/setup.md
Labels: quickstart

#5871 Updates to user search
  articles/api/management/v2/user-search.md
  articles/users/search/index.md
  articles/users/search/v3/index.md
  config/sidebar.yml
  updates/2018-03-12.yaml
Labels: ready-for-review

#5863 GDPR content | user consent
  articles/compliance/gdpr/_stepnav.html
  articles/compliance/gdpr/data-processing.md
  articles/compliance/gdpr/definitions.md
  articles/compliance/gdpr/features-aiding-compliance/data-minimization.md
  articles/compliance/gdpr/features-aiding-compliance/data-portability.md
  articles/compliance/gdpr/features-aiding-compliance/index.md
  articles/compliance/gdpr/features-aiding-compliance/protect-user-data.md
  articles/compliance/gdpr/features-aiding-compliance/right-to-access-data.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/_redirect.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/index.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock.md
  articles/compliance/gdpr/gdpr-summary.md
  articles/compliance/gdpr/roles-responsibilities.md
  articles/compliance/gdpr/security-advice-for-customers.md
  config/sidebar.yml
  media/articles/compliance/auth0js-db-consent-flag.png
  media/articles/compliance/lock-consent-form-agree.png
  media/articles/compliance/lock-db-consent-flag-TC.png
  media/articles/compliance/lock-db-consent-flag.png
  media/articles/compliance/lock-signup-new-field-TC.png
  media/articles/compliance/lock-signup-new-field.png
  updates/2018-03-14.yml
Labels: do-not-merge

#5876 Adding error codes and descriptions for /co/authenticate
  articles/_includes/_co_authenticate_errors.md
  articles/cross-origin-authentication/index.md
  articles/libraries/auth0js/v9/index.md
  articles/libraries/lock/v11/index.md
Labels: ready-for-review

#5891 Removing `loginWithCredentials` section
  articles/_includes/_lock-sdk.html
  articles/libraries/auth0js/v8/migration-guide.md
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#5883 fix leeway param
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#5886 add checkSession to lock
  articles/libraries/lock/v11/api.md
Labels: ready-for-review

#5849 Migration custom domains
  articles/custom-domains/index.md
  articles/libraries/_includes/_configure_custom_domain.md
  articles/libraries/_includes/_configure_embedded_login.md
  articles/libraries/auth0js/v9/index.md
  articles/libraries/auth0js/v9/migration-v8-v9.md
  articles/libraries/lock/v11/migration-v10-v11.md
Labels: ready-for-review

#5899 Added instructions to customize the login page for Sharepoint
  articles/integrations/sharepoint.md
  media/articles/integrations/sharepoint/sharepoint-login-page-windows-auth.png
  media/articles/integrations/sharepoint/sharepoint-login-page.png
Labels: ready-for-review

#5281 Update android QS
  articles/quickstart/native/android/02-custom-login-form.md
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/07-authorization.md
  articles/quickstart/native/android/_includes/_api_authz.md
  articles/quickstart/native/android/_includes/_lock_login.md
  articles/quickstart/native/android/_includes/_login.md
Labels: quickstart

#5906 Update Guardian versioning info
  articles/custom-domains/index.md
Labels: ready-for-review

#5898 Add DNS host name warnings
  articles/appliance/infrastructure/dns.md
  articles/appliance/webtask/dedicated-domains.md
Labels: ready-for-review

#5816 Typo in file descriptor
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart, ready-for-review

#5817 Add nonce to buildAuthorizeUrl() code example
  articles/libraries/auth0js/v9/index.md
Labels: bug, ready-for-review

#5830 Update 01-login.md
  articles/quickstart/webapp/scala/01-login.md
Labels: quickstart

#5857 Impersonation
  articles/api/authentication/_impersonation.md
  articles/user-profile/index.md
  articles/user-profile/user-impersonation.md
Labels: do-not-merge

#5925 Update warning w/ Enterprise customer info
  articles/design/using-auth0-with-multi-tenant-apps.md
Labels: ready-for-review

#5923 Incorrect variable name
  articles/quickstart/backend/laravel/01-authorization.md
Labels: ready-for-review

#5934 Small language change to a migrations section
  articles/migrations/index.md
Labels: ready-for-review

#5926 Add note for custom DB usage of metadata
  articles/metadata/index.md
Labels: ready-for-review

#5915 Updating leftover Lock v10 links
  articles/libraries/lock/v11/api.md
  articles/libraries/lock/v11/i18n.md
Labels: ready-for-review

#5872 Improve Installation and Configuration for WP
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/index.md
  articles/cms/wordpress/installation.md
  articles/cms/wordpress/troubleshoot.md
  media/articles/cms/wordpress/plugin-auth-page.png
Labels: ready-for-review

#5921 Add interface to Quick Start API
  articles/quickstart/spa/angular2/03-calling-an-api.md
Labels: quickstart

#5928 Populate warnings re: flags
  articles/protocols/saml/identity-providers/okta.md
  articles/protocols/saml/identity-providers/onelogin.md
  articles/protocols/saml/identity-providers/ping7.md
  articles/protocols/saml/idp-initiated-sso.md
  articles/protocols/saml/saml-configuration/special-configuration-scenarios/idp-initiated-sso.md
  articles/protocols/saml/saml-idp-eloqua.md
Labels: ready-for-review

#5792 Altering /clients/connections with a temporary multitenancy scenario
  articles/clients/connections.md
Labels: ready-for-review

#5947 Update user-consent.md
  articles/api-auth/user-consent.md
Labels: ready-for-review
