Repository auth0/docs, pull requests merged in 2018-08, with the labels that each got.

#5685 Edits: Why you should always use access tokens to secure an API
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
Labels: ready-for-review

#6488 Adding note on redirectUri param
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#6487 Adding custom domain example
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#5860 Fix for sign up slack message rule
  articles/rules/current/index.md
Labels: in-review

#6426 Quickstarts / Webapp / Node-js: Merge profile and user login + general improvements
  articles/quickstart/webapp/nodejs/01-login.md
  articles/quickstart/webapp/nodejs/02-user-profile.md
  articles/quickstart/webapp/nodejs/_includes/_login.md
  articles/quickstart/webapp/nodejs/index.yml
  config/redirects.js
Labels: quickstart

#6505 Be more explicit about opening xcworkspace in XCode.
  articles/quickstart/native/ios-objc/download.md
  articles/quickstart/native/ios-swift/download.md
Labels: quickstart

#6480 Fix errors and add more information on routes, views for Rails quickstart
  articles/quickstart/webapp/rails/01-login.md
  snippets/server-platforms/rails/setup.md
Labels: quickstart, ready-for-review

#6516 Update Lock warning
  articles/connector/kerberos.md
Labels: ready-for-review

#6518 search users v3: include missing breaking changes
  articles/users/search/v3/index.md
  articles/users/search/v3/query-syntax.md
Labels: ready-for-review

#6507 AD Connector updates
  articles/connector/modify.md
Labels: ready-for-review

#6526 search users v3: include missing breaking changes
  articles/users/search/v3/index.md
  articles/users/search/v3/query-syntax.md
Labels: ready-for-review

#6478 Update verbiage on user billing
  articles/policies/billing.md
Labels: ready-for-review

#6517 Update WordPress Configuration and Extending
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
Labels: ready-for-review

#6553 QS Webapp Scala / Play 2: Fix callback URL in download instructions
  articles/quickstart/webapp/scala/01-login.md
  articles/quickstart/webapp/scala/download.md
Labels: quickstart

#6550 QS SPA Vanilla JS: Fix callback URL in download instructions
  articles/quickstart/spa/vanillajs/download.md
Labels: quickstart

#6548 QS .NET Core 2.0 Download: Fix callback URL in download instructions
  articles/quickstart/webapp/aspnet-core/download.md
Labels: quickstart

#6551 QS SPA Ember: Fix callback URL in download instructions
  articles/quickstart/spa/ember/download.md
Labels: quickstart

#6490 Break up scopes docs
  articles/scopes/current/api-scopes.md
  articles/scopes/current/custom-claims.md
  articles/scopes/current/index.md
  articles/scopes/current/oidc-scopes.md
Labels: ready-for-review

#6513 Fixed links to callback urls in Swift QSs
  articles/quickstart/native/ios-objc/02-custom-login-form.md
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
  articles/quickstart/native/ios-objc/_includes/_login_embedded.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_login_embedded.md
Labels: quickstart

#6514 Rename client to application in dynamic-application-registration.md
  articles/api-auth/dynamic-client-registration.md
  config/sidebar.yml
Labels: ready-for-review

#6559 Added information about SDKs
  articles/users/search/v3/index.md
Labels: ready-for-review

#6562 Remove unused get_state method
  articles/quickstart/webapp/rails/01-login.md
Labels: ready-for-review

#6564 Add limit warning
  articles/applications/application-settings/_settings-pt2.md
Labels: ready-for-review

#6570 Add ToC to long doc
  articles/email/templates.md
Labels: ready-for-review

#6574 Remove dotnet restore command
  articles/quickstart/webapp/aspnet-core/download.md
Labels: quickstart

#6575 QS API Symfony: Fix port number in download instructions
  articles/quickstart/backend/symfony/download.md
Labels: quickstart

#6563 QS webapp Rails: Update requirements with compatibility with Rails 4.2.0
  articles/quickstart/webapp/rails/index.yml
Labels: quickstart

#6556 QS webapp Go-Lang: Use filesystem store for sessions. Fix wrong use of Os.GetEnv.
  articles/quickstart/webapp/golang/01-login.md
Labels: quickstart

#6580 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#6584 Removing unsupported frameworks and adding replacement
  articles/_includes/_libraries_support_frameworks.html
Labels: ready-for-review

#6578 Fixing a typo in configuration doc
  articles/libraries/lock/v11/configuration.md
Labels: ready-for-review

#6585 Save and refresh JWT link
  articles/tokens/index.html
Labels: ready-for-review

#6581 Added note about lack of support in Mgmt API v1
  articles/users/search/v3/index.md
Labels: ready-for-review

#6596 Update docs referencing WT CLI
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/hooks/cli/create-delete.md
  articles/hooks/cli/edit.md
  articles/hooks/cli/enable-disable.md
  articles/hooks/cli/index.md
  articles/hooks/cli/logs.md
  articles/multifactor-authentication/yubikey.md
Labels: update-needed
