Repository auth0/docs, pull requests merged in 2018-04, with the labels that each got.

#5924 Document custom domain differences
  articles/appliance/custom-domains/index.md
  articles/appliance/infrastructure/faq.md
  articles/appliance/infrastructure/network.md
  articles/getting-started/deployment-models.md
Labels: do-not-merge

#5958 Adding note about universal login migration; also date fix
  articles/libraries/_includes/_migrate_universal.md
  articles/libraries/auth0js/v9/migration-v8-v9.md
  articles/libraries/lock/v11/migration-guide.md
  articles/libraries/lock/v11/migration-v10-v11.md
Labels: ready-for-review

#5948 Add tokens error
  articles/errors/libraries/auth0-js/invalid-token.md
Labels: do-not-merge

#5971 Adding a note about bookmarking / direct URL usage of login page
  articles/hosted-pages/login/index.md
Labels: ready-for-review

#5968 Update when-to-use-lock.md
  articles/libraries/when-to-use-lock.md
Labels: ready-for-review

#5969 Minor correction to CVE
  articles/security/bulletins/cve-2018-6873.md
  config/sidebar.yml
Labels: ready-for-review

#5877 Add author metadata
  articles/quickstart/backend/falcor/index.yml
  articles/quickstart/backend/hapi/index.yml
  articles/quickstart/backend/java-spring-security/index.yml
  articles/quickstart/backend/laravel/index.yml
  articles/quickstart/backend/php/index.yml
  articles/quickstart/backend/relay/index.yml
  articles/quickstart/backend/ruby/index.yml
  articles/quickstart/backend/symfony/index.yml
  articles/quickstart/config.yml
  articles/quickstart/native/android/index.yml
  articles/quickstart/native/chrome/index.yml
  articles/quickstart/native/cordova/index.yml
  articles/quickstart/native/ios-objc/index.yml
  articles/quickstart/native/ios-swift/index.yml
  articles/quickstart/native/phonegap/_index.yml
  articles/quickstart/native/react-native/index.yml
  articles/quickstart/native/windows-uwp-csharp/index.yml
  articles/quickstart/native/wpf-winforms/index.yml
  articles/quickstart/native/xamarin/index.yml
  articles/quickstart/spa/aurelia/index.yml
  articles/quickstart/spa/cyclejs/index.yml
  articles/quickstart/spa/ember/index.yml
  articles/quickstart/spa/socket-io/index.yml
  articles/quickstart/webapp/apache/index.yml
  articles/quickstart/webapp/java-spring-mvc/index.yml
  articles/quickstart/webapp/java-spring-security-mvc/index.yml
  articles/quickstart/webapp/java/index.yml
Labels: quickstart, ready-for-review

#5977 Add file paths to code snippets
  articles/quickstart/webapp/rails/01-login.md
Labels: ready-for-review

#5957 Fingerprinting
  articles/cross-origin-authentication/fingerprinting.md
  articles/cross-origin-authentication/index.md
  articles/libraries/auth0js/v9/migration-guide.md
  articles/libraries/lock/v11/migration-guide.md
Labels: ready-for-review

#5986 Add Node.js v8 migration docs
  articles/migrations/guides/extensibility-node8.md
  articles/migrations/index.md
  media/articles/migrations/node-runtime1.png
  media/articles/migrations/node-runtime2.png
Labels: do-not-merge

#5900 Restructure user search section
  articles/users/search/index.yml
  articles/users/search/v2/index.md
  articles/users/search/v2/query-syntax.md
  articles/users/search/v3/best-practices.md
  articles/users/search/v3/index.md
  articles/users/search/v3/query-syntax.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#6009 Fixing broken link
  articles/guides/login/_includes/_centralized_webapp.md
Labels: ready-for-review

#5988 Adding guides for SSO and Cordova
  articles/guides/login/migration-sso.md
  articles/libraries/auth0js/v9/migration-guide.md
  articles/libraries/lock/v11/migration-cordova.md
  articles/libraries/lock/v11/migration-guide.md
Labels: ready-for-review

#6028 Fix redirect
  config/redirects.js
Labels: do-not-merge

#6033 Update 02-session-handling.md
  articles/quickstart/webapp/rails/02-session-handling.md
Labels: quickstart

#5935 Add note about OWIN 4 incompatibility
  articles/quickstart/backend/webapi-owin/01-authorization.md
Labels: quickstart

#5980 Update 01-login.md
  articles/quickstart/webapp/python/01-login.md
Labels: quickstart

#6045 Fix flashMessage example for authorization errors
  articles/libraries/lock/v11/api.md
Labels: in-review

#6043 Quick fixes
  articles/custom-domains/index.md
  articles/rules/current/context.md
Labels: ready-for-review

#6041 Update cisco-webex.md
  articles/protocols/saml/saml-apps/cisco-webex.md
Labels: ready-for-review

#6062 Fix image URLs
  articles/cms/wordpress/configuration.md
Labels: do-not-merge

#6100 Clients --> Applications Fixes + Clean-Up
  articles/_includes/_new_app.md
  articles/api-auth/apis.md
  articles/api-auth/grant/authorization-code-pkce.md
  articles/api-auth/grant/authorization-code.md
  articles/api-auth/restrict-requests-for-scopes.md
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
  articles/api/authentication/_userinfo.md
  articles/api/authorization-extension/_groups.md
  articles/applications/application-grant-types.md
  articles/applications/application-types.md
  articles/architecture-scenarios/_includes/_api-authentication-and-authorization.md
  articles/architecture-scenarios/_includes/_api-implement.md
  articles/architecture-scenarios/implementations/mobile-api/api-implementation-nodejs.md
  articles/architecture-scenarios/implementations/spa-api/api-implementation-nodejs.md
  articles/connections/_quickstart-links.md
  articles/connections/enterprise/active-directory.md
  articles/connections/social/google.md
  articles/extensions/account-link.md
  articles/libraries/_includes/_configure_custom_domain.md
  articles/libraries/lock-android/v2/configuration.md
  articles/policies/billing.md
  articles/protocols/oauth2/index.md
  articles/protocols/saml/samlsso-auth0-to-auth0.md
  articles/quickstart/native/_includes/_cordova_setup.md
  articles/quickstart/native/_includes/_ionic_setup.md
  articles/quickstart/native/_includes/_ios_config.md
  articles/quickstart/native/android/_includes/_api_authz.md
  articles/quickstart/native/android/_includes/_credentials.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/react-native/_includes/_config.md
  articles/quickstart/native/react-native/_includes/_intro.md
  articles/quickstart/native/react-native/_includes/_login.md
  articles/quickstart/spa/_includes/_auth_service_configure_client_details.md
  articles/quickstart/spa/_includes/_auth_service_method_description_lock.md
  articles/quickstart/spa/_includes/_auth_service_method_description_no_callback.md
  articles/quickstart/spa/_includes/_calling_api_create_api.md
  articles/quickstart/webapp/_includes/_getting_started.md
  articles/security/common-threats.md
  articles/users/migrations/bulk-import.md
Labels: do-not-merge

#6082 Link to reprompt permissions
  articles/connections/_quickstart-links.md
  articles/connections/social/reprompt-permissions.md
Labels: ready-for-review
