Repository auth0/docs, pull requests merged in 2018-06, with the labels that each got.

#6220 updated "Searchable fields (v3)" section with the new features
  articles/users/search/v3/query-syntax.md
Labels: ready-for-review

#6221 update "Migrate from search engine v2 to v3" based on recent changes
  articles/users/search/v3/index.md
Labels: ready-for-review

#6211 Migration guide updates
  articles/_includes/_embedded_login_warning.md
  articles/errors/deprecation-errors.md
  articles/libraries/auth0js/v9/index.md
  articles/libraries/auth0js/v9/migration-guide.md
  articles/libraries/lock/v11/index.md
  articles/libraries/lock/v11/migration-guide.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
Labels: update-needed

#6056 Node8 Migration Guide for Appliance
  articles/appliance/migrations/extensibility-node8.md
  media/articles/appliance/migrations/node-version.png
  media/articles/appliance/migrations/sandbox.png
Labels: do-not-merge

#6226 Appliance updates
  articles/appliance/admin/index.md
  articles/appliance/admin/limiting-ssh-access.md
  articles/appliance/dashboard/updates.md
  config/sidebar.yml
Labels: do-not-merge

#6217 WordPress v3.6.0 install and configure updates
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/installation.md
  media/articles/cms/wordpress/setup-wizard-select-setup.png
  media/articles/cms/wordpress/setup-wizard-social-modal.png
  media/articles/cms/wordpress/setup-wizard-step-1.png
Labels: do-not-merge

#6233 Fixing a broken link
  articles/migrations/guides/legacy-lock-api-deprecation.md
Labels: ready-for-review

#6234 Move doc
  articles/appliance/extensibility-node8.md
Labels: do-not-merge

#6229 Updates to Appliance docs
  articles/appliance/appliance-overview.md
  articles/appliance/cli/reconfiguring-ip.md
  articles/appliance/infrastructure/internet-restricted-deployment.md
Labels: do-not-merge

#6239 Fix links
  articles/appliance/extensibility-node8.md
Labels: do-not-merge

#6241 Update account-link.md
  articles/extensions/account-link.md
Labels: ready-for-review

#6071 Spring MVC Web App Update _setup.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_setup.md
Labels: quickstart

#6253 Fixing wording of notifications in docs
  articles/users/search/v2/index.md
  articles/users/search/v3/index.md
Labels: ready-for-review

#6237 Update ASP.NET Core samples for .NET Core 2.1
  articles/quickstart/backend/aspnet-core-webapi/01-authorization.md
  articles/quickstart/webapp/aspnet-core/00-intro.md
  articles/quickstart/webapp/aspnet-core/01-login.md
  articles/quickstart/webapp/aspnet-core/02-user-profile.md
  articles/quickstart/webapp/aspnet-core/03-authorization.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
Labels: quickstart

#6257 Adding two new scenarios to deprecation errors document
  articles/errors/deprecation-errors.md
  articles/hosted-pages/login/index.md
Labels: ready-for-review

#6255 Add warning
  articles/hosted-pages/login/_custom-domains.md
  articles/hosted-pages/login/auth0js.md
  articles/hosted-pages/login/lock-passwordless.md
  articles/hosted-pages/login/lock.md
Labels: ready-for-review

#6240 Rename non-interactive clients
  articles/api-auth/blacklists-vs-grants.md
  articles/api-auth/grant/client-credentials.md
  articles/api-auth/intro.md
  articles/api-auth/tutorials/adoption/api-tokens.md
  articles/api-auth/tutorials/client-credentials.md
  articles/applications/application-grant-types.md
  articles/applications/application-settings/index.yml
  articles/applications/application-settings/machine-to-machine/index.md
  articles/architecture-scenarios/server-api/cron-implementation-python.md
  articles/architecture-scenarios/server-api/part-1.md
  articles/connections/calling-an-external-idp-api.md
  articles/protocols/oauth2/index.md
  config/redirects.js
Labels: ready-for-review

#6274 Removing non-maintained Quickstarts
  articles/logout/index.md
  articles/quickstart/backend/relay/01-authentication.md
  articles/quickstart/backend/relay/index.yml
  articles/quickstart/native/electron/01-login.md
  articles/quickstart/native/electron/_index.yml
  articles/quickstart/native/ionic/01-login.md
  articles/quickstart/native/ionic/_index.yml
  articles/quickstart/native/ionic2/01-login.md
  articles/quickstart/native/ionic2/_index.yml
  articles/quickstart/native/phonegap/01-login.md
  articles/quickstart/native/phonegap/_index.yml
  articles/quickstart/spa/cyclejs/01-login.md
  articles/quickstart/spa/cyclejs/index.yml
  articles/quickstart/spa/socket-io/01-login.md
  articles/quickstart/spa/socket-io/index.yml
  articles/support/matrix.md
  config/redirects.js
  snippets/application-platforms/cyclejs/configure.md
  snippets/application-platforms/cyclejs/dependencies.md
  snippets/application-platforms/cyclejs/logout.md
  snippets/application-platforms/cyclejs/query.md
  snippets/application-platforms/cyclejs/securize.md
  snippets/application-platforms/cyclejs/setup.md
  snippets/application-platforms/cyclejs/use.md
  snippets/native-platforms/phonegap/dependencies.md
  snippets/server-apis/relay/dependencies.md
  snippets/server-apis/relay/frontend.md
  snippets/server-apis/relay/setup.md
  snippets/server-apis/relay/use.md
Labels: quickstart

#6277 Adding info about the management warning panel
  articles/errors/deprecation-errors.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
Labels: ready-for-review

#6170 Examples for custom web signup when "Requires Username" is true
  articles/libraries/auth0js/v9/index.md
  articles/libraries/custom-signup.md
Labels: ready-for-review

#6295 Token Renewal in Safari
  articles/api-auth/token-renewal-in-safari.md
  articles/api-auth/tutorials/silent-authentication.md
  articles/libraries/auth0js/v9/index.md
  media/articles/api-auth/safari-privacy-preferences.png
Labels: do-not-merge

#6306 Update Node8 docs
  articles/appliance/extensibility-node8.md
Labels: do-not-merge

#6317 Docs Fixes for Appliance
  articles/appliance/extensibility-node8.md
  articles/appliance/extensions.md
  articles/appliance/infrastructure/extensions.md
  articles/appliance/infrastructure/internet-restricted-deployment.md
  articles/appliance/infrastructure/ip-domain-port-list.md
  articles/appliance/webtasks/dedicated-domains.md
Labels: do-not-merge

#6327 Updated migration warning notes
  articles/migrations/guides/legacy-lock-api-deprecation.md
Labels: ready-for-review

#6222 Improving M2M docs reflecting new UX changes
  articles/api-auth/apis.md
  articles/api-auth/config/using-the-auth0-dashboard.md
  articles/api-auth/config/using-the-management-api.md
  articles/api-auth/grant/client-credentials.md
  articles/api-auth/index.md
  articles/api-auth/intro.md
  articles/api-auth/tutorials/client-credentials.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/api/authentication/api-authz/_get-token.md
  articles/api/management/v2/tokens.md
  articles/applications/_configure.md
  articles/applications/application-grant-types.md
  articles/applications/application-settings/_adv-settings-mobile.md
  articles/applications/application-settings/_adv-settings-pt2.md
  articles/applications/application-settings/_adv-settings.md
  articles/applications/application-settings/index.yml
  articles/applications/application-settings/machine-to-machine/index.md
  articles/applications/application-settings/native/index.md
  articles/applications/application-settings/regular-web-app/index.md
  articles/applications/application-settings/single-page-app/index.md
  articles/applications/index.md
  articles/applications/machine-to-machine.md
  articles/applications/native.md
  articles/applications/spa.md
  articles/applications/webapps.md
  articles/tokens/access-token.md
  media/articles/applications/m2m-apis.png
  media/articles/applications/m2m-create.png
  media/articles/applications/m2m-quickstart.png
  media/articles/applications/m2m-select-api.png
  media/articles/applications/m2m-select-scopes.png
Labels: do-not-merge

#6332 Production Checks updates
  articles/applications/application-settings/_settings-pt2.md
  articles/cross-origin-authentication/index.md
  articles/custom-domains/index.md
  articles/guides/migration-legacy-flows.md
  articles/libraries/lock/v11/migration-guide.md
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/pre-deployment/how-to-run-test.md
  articles/pre-deployment/index.html
  articles/pre-deployment/prelaunch-tips.md
  articles/pre-deployment/tests/best-practice.md
  articles/pre-deployment/tests/recommended.md
  articles/pre-deployment/tests/required.md
  config/sidebar.yml
  media/articles/support/pre-deployment-tests/choose-applications.png
  media/articles/support/pre-deployment-tests/choose-clients.png
  media/articles/support/pre-deployment-tests/results.png
  media/articles/support/pre-deployment-tests/tenants-tests.png
  media/articles/support/pre-deployment-tests/tenants.png
Labels: ready-for-review
