Repository auth0/docs, pull requests merged in 2018-09, with the labels that each got.

#6600 Added new migration section on Extensions
  articles/users/search/v3/index.md
Labels: ready-for-review

#6604 Remove userinfo audience from SPA quickstarts
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/angular2/custom-login-form.md
  articles/quickstart/spa/angular2/embedded-login.md
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
  articles/quickstart/spa/aurelia/_includes/_centralized_login.md
  articles/quickstart/spa/ember/_includes/_centralized_login.md
  articles/quickstart/spa/jquery/_includes/_centralized_login.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart

#6583 Conceptual fixes on JWT doc
  articles/tokens/jwt.md
  media/articles/jwt/client-credentials-grant.png
  media/articles/jwt/jwt-diagram.png
Labels: ready-for-review

#6597 Information for trouble shooting CO issues with IE
  articles/custom-domains/index.md
Labels: update-needed

#6599 Update billing policy
  articles/policies/billing.md
Labels: ready-for-review

#6598 Remove note
  articles/users/search/v3/index.md
Labels: ready-for-review

#6594 Update MySQL Custom DB Scripts
  articles/connections/database/custom-db/templates/change-password.md
  articles/connections/database/custom-db/templates/verify.md
Labels: ready-for-review

#6592 Add reference to auth0 library
  articles/api/management/v2/tokens.md
Labels: ready-for-review

#6566 Add appliance note
  articles/custom-domains/index.md
Labels: ready-for-review

#6569 Hooks
  articles/hooks/dashboard/index.md
  articles/hooks/extensibility-points/pre-user-registration.md
Labels: ready-for-review

#6577 Update GitLab Screenshots
  articles/extensions/gitlab-deploy.md
  media/articles/extensions/gitlab-deploy/gitlab-add-webhook.png
  media/articles/extensions/gitlab-deploy/gitlab-settings-menu.png
  media/articles/extensions/gitlab-deploy/new-access-token.png
Labels: ready-for-review

#6586 Remove Touch ID references
  articles/api/authentication/_passwordless.md
  articles/connections/passwordless/ios.md
Labels: ready-for-review

#6587 Remove recs on secret questions
  articles/connections/passwordless/faq.md
  articles/multifactor-authentication/custom/custom-landing.md
Labels: ready-for-review

#6611 Update community-supported to correct div class
  articles/support/matrix.md
Labels: bug

#6617 Adding polling with checkSession section
  articles/_includes/_checksession_polling.md
  articles/api-auth/tutorials/represent-multiple-apis.md
  articles/api-auth/tutorials/silent-authentication.md
  articles/libraries/auth0js/v9/index.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/sso/current/single-page-apps.md
Labels: ready-for-review

#6616 Remove Passwordlessless Refs
  articles/api/authentication/_passwordless.md
  articles/connections/passwordless/ios.md
Labels: ready-for-review

#6589 Update management-api.md
  articles/rules/current/management-api.md
Labels: ready-for-review

#6588 Add password fields
  articles/user-profile/user-profile-structure.md
Labels: ready-for-review

#6525 Minimum Password Length
  articles/connections/database/password-strength.md
  articles/hosted-pages/password-reset.md
  media/articles/connections/database/password-strength/pw-manage.png
Labels: do-not-merge

#6623 Update working with Auth0 locally
  articles/dev-lifecycle/local-testing-and-development.md
Labels: ready-for-review

#6613 Update auth0 & multi-tenancy page
  articles/design/using-auth0-with-multi-tenant-apps.md
Labels: ready-for-review

#6627 Removed outdated Bitbucket screen shots
  articles/connections/social/bitbucket.md
Labels: ready-for-review

#6631 Quickstart NodeJS: Added note on order of commands
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart

#6632 change != to !==
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart

#6628 Remove /userinfo audience from Ruby web app quickstart
  snippets/server-platforms/rails/setup.md
Labels: quickstart

#6595 IdP-Initiated SSO
  articles/protocols/saml/idp-initiated-sso.md
Labels: ready-for-review

#6579 Configuration best practices / recommendations
  articles/best-practices/application-settings.md
  articles/best-practices/connection-settings.md
  articles/best-practices/index.md
  articles/best-practices/operations.md
  articles/best-practices/rules.md
  articles/best-practices/tenant-settings.md
  config/sidebar.yml
  updates/2018-09-07.yml
Labels: update-needed

#6625 Specify URL rules
  articles/api-auth/apis.md
Labels: ready-for-review

#6626 Added panel generating password reset ticket
  articles/connections/database/password-change.md
Labels: ready-for-review

#6622 Update troubleshooting with har files
  articles/support/troubleshooting-with-har-files.md
Labels: ready-for-review

#6466 Add email authenticator tutorial
  articles/multifactor-authentication/api/email.md
Labels: ready-for-review

#6640 Added custom db script checklist
  articles/connections/database/custom-db/index.md
  articles/connections/database/custom-db/templates/index.md
Labels: ready-for-review

#6645 Fixed a few typos and a broken bullet
  articles/connections/database/custom-db/templates/index.md
Labels: ready-for-review

#6648 Added version to delegated admin to fix versioning
  config/sidebar.yml
Labels: ready-for-review

#6644 Update Sesssions Screenshot
  media/articles/tutorials/tenant-settings/session-timeout.png
Labels: ready-for-review

#6647 Updated to account for removal of user profile locations tab in dashboard
  articles/user-profile/index.md
  media/articles/user-profile/user-picture.png
  media/articles/user-profile/user1.png
  media/articles/user-profile/user4.png
  media/articles/user-profile/user5.png
  media/articles/user-profile/user6.png
Labels: ready-for-review

#6650 Add troubleshooting section
  articles/troubleshoot/basics.md
  articles/troubleshoot/har.md
  articles/troubleshoot/index.md
  articles/troubleshoot/issues.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#6682 Add note to set up app prior to sample code setup
  articles/api-auth/tutorials/represent-multiple-apis.md
Labels: ready-for-review

#6677 Clarify scope location per customer feedback
  articles/scopes/current/index.md
Labels: ready-for-review

#6649 Update B2C & B2E architecture scenarios pages
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/b2e.md
Labels: ready-for-review

#6686 update description metadata
  articles/metadata/index.md
Labels: ready-for-review

#6607 Update to reflect terminology change-Client to Application
  media/articles/api-auth/oauth2-grants-flow.png
Labels: ready-for-review

#6653 Clarified the definition scopes
  articles/scopes/current/index.md
Labels: ready-for-review

#6675 Update rules context object information
  articles/rules/current/context.md
  articles/rules/current/index.md
  articles/tokens/access-token.md
Labels: ready-for-review

#6521 Delegated-admin-extension docs
  articles/extensions/delegated-admin/v2/index.md
  articles/extensions/delegated-admin/v3/index.md
Labels: do-not-merge

#6689 Rewording messaging about error formats
  articles/api/authentication/_introduction.md
Labels: ready-for-review

#6676 Added note that ID token toggle may be unavailable for new tenants
  articles/extensions/account-link.md
Labels: ready-for-review

#6673 Link to list of source control extensions
  articles/best-practices/operations.md
Labels: ready-for-review

#6683 Add pagination info to Authorization Extension API docs
  articles/api/authorization-extension/_groups.md
  articles/api/authorization-extension/_users.md
Labels: ready-for-review

#6679 Resized and compressed images after removing user location tab
  articles/user-profile/index.md
  media/articles/user-profile/user-picture.png
  media/articles/user-profile/user1.png
  media/articles/user-profile/user4.png
  media/articles/user-profile/user5.png
  media/articles/user-profile/user6.png
Labels: ready-for-review

#6684 Update impersonation warning, remove references from unnecessary spots
  articles/_includes/_deprecate-impersonation.md
  articles/api/management/v1/use-cases.md
  articles/extensions/delegated-admin/v2/manage-users.md
  articles/extensions/delegated-admin/v3/manage-users.md
  articles/users/index.md
Labels: ready-for-review

#6685 Specify connection type for emails
  articles/email/index.md
Labels: ready-for-review

#6690 Add docs on min PW length
  articles/connections/database/password-strength.md
  articles/hosted-pages/password-reset.md
  media/articles/connections/database/password-strength/pw-manage.png
Labels: do-not-merge
