Repository auth0/docs, pull requests merged in 2018-10, with the labels that each got.

#6692 Update frontmatter for arch scenario pages, troubleshooting docs
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/b2e.md
  articles/troubleshoot/index.md
  articles/troubleshoot/issues.md
Labels: ready-for-review

#6687 Update sidebar for mfa section
  config/sidebar.yml
Labels: ready-for-review

#6706 File paths added for sample code in Android native docs
  articles/quickstart/native/android/_includes/_auth0.md
  articles/quickstart/native/android/_includes/_login.md
Labels: quickstart

#6698 Update gitignore
  .gitignore
Labels: quickstart

#6700 Fix config path in laravel docs
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart

#6707 Removed Mongo
  articles/connections/database/custom-db/templates/index.md
Labels: ready-for-review

#6710 Quick updates to arch scenarios
  articles/architecture-scenarios/b2e.md
  articles/architecture-scenarios/index.md
  config/sidebar.yml
Labels: ready-for-review

#6728 Add frequently made unsupported request
  articles/policies/data-transfer.md
Labels: ready-for-review

#6699 Update where to store tokens information
  articles/security/store-tokens.md
Labels: ready-for-review

#6752 Update custom-social-extensions.md
  articles/extensions/custom-social-extensions.md
Labels: ready-for-review

#6733 fixed spacing
  articles/_includes/_deprecate-impersonation.md
Labels: ready-for-review

#6732 Fixed broken link
  articles/sso/current/setup.md
Labels: ready-for-review

#6762 Fix grammar and typo
  articles/connections/social/auth0-oidc.md
Labels: ready-for-review

#6765 Correct curl and label on create group mappings
  articles/api/authorization-extension/_groups.md
Labels: ready-for-review

#6764 Add location of config file and note about ticket use case
  articles/connector/modify.md
Labels: ready-for-review

#6763 Add note on guardian & google auth ui changes
  articles/multifactor-authentication/guardian/dev-guide.md
Labels: ready-for-review

#6755 Fix article spelling errors
  articles/analytics/integrations/_usage.md
  articles/analytics/integrations/facebook-analytics/index.md
  articles/api-auth/grant/password.md
  articles/api/authentication/_multifactor-authentication.md
  articles/api/management/v1/index.md
  articles/appliance/cli/configure-cli.md
  articles/appliance/infrastructure/extensions.md
  articles/appliance/infrastructure/internet-restricted-deployment.md
  articles/appliance/infrastructure/ip-domain-port-list.md
  articles/appliance/webtasks/index.md
  articles/architecture-scenarios/mobile-api/api-implementation-nodejs.md
  articles/connections/criipto/nemid.md
  articles/connections/database/password-strength.md
  articles/connections/enterprise/adfs.md
  articles/connections/social/bitbucket.md
  articles/connections/social/salesforce.md
  articles/dashboard/dashboard-tenant-settings.md
  articles/extensions/logstash.md
  articles/extensions/mixpanel.md
  articles/extensions/papertrail.md
  articles/extensions/splunk.md
  articles/extensions/sso-dashboard.md
  articles/hooks/cli/create-delete.md
  articles/hooks/cli/edit.md
  articles/hooks/cli/enable-disable.md
  articles/logs/index.md
  articles/policies/rate-limits.md
  articles/policies/restore-deleted-tenant.md
  articles/pre-deployment/how-to-run-test.md
  articles/scopes/current/api-scopes.md
  articles/support/subscription.md
  articles/support/tickets.md
  articles/troubleshoot/issues.md
Labels: ready-for-review

#6758 Add Base64 requirement to AD/LDAP connector client certs doc
  articles/connector/client-certificates.md
Labels: ready-for-review

#6757 Fix broken links on azure tutorial
  articles/integrations/azure-tutorial.md
Labels: ready-for-review

#6702 Update links in STYLEGUIDE.md
  STYLEGUIDE.md
Labels: ready-for-review

#6694 Update setting up mult env for clarity and to better explain rules
  articles/dev-lifecycle/setting-up-env.md
  media/articles/lifecycle/rules-conf-values.png
  media/articles/lifecycle/rules-create-first.png
  media/articles/lifecycle/rules-enter-name.png
  media/articles/lifecycle/rules-rule-code.png
  media/articles/lifecycle/rules-template-empty.png
Labels: ready-for-review

#6726 Re-add missing page
  articles/multifactor-authentication/api/email.md
Labels: ready-for-review

#6767 Add warning to self-managed-certificates.md
  articles/custom-domains/self-managed-certificates.md
Labels: ready-for-review

#6777 QS webapp Nodejs: Add state to passport strategy
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart

#6779 Fixed URL to Azure Portal
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review

#5951 Update config/app.php
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart

#5847 Update _login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
Labels: quickstart

#6809 Update articles/quickstart/spa/vuejs/index.yml
  articles/quickstart/spa/vuejs/index.yml
Labels: quickstart

#5749 Fix comments #5219
  articles/quickstart/native/react-native/_includes/_config.md
  articles/quickstart/native/react-native/_includes/_login.md
Labels: quickstart, ready-for-review, verified

#6815 Fix URLs
  articles/extensions/delegated-admin/v3/index.md
Labels: ready-for-review

#6719 Updated Symfony version
  articles/quickstart/backend/symfony/index.yml
Labels: quickstart

#6817 Update google-apps.md
  articles/connections/enterprise/google-apps.md
Labels: ready-for-review

#6751 Hybrid Flow Theory & How-To
  articles/api-auth/grant/hybrid.md
  articles/api-auth/tutorials/hybrid-flow.md
Labels: ready-for-review

#6821 Remove Extend cross-linking
  articles/extensions/index.md
  articles/hooks/index.md
  articles/rules/current/index.md
  articles/topics/extensibility.md
Labels: ready-for-review

#6839 Replace panels with table
  articles/tokens/jwks.md
Labels: ready-for-review

#6835 Update articles/anomaly-detection/index.md
  articles/anomaly-detection/index.md
Labels: ready-for-review

#6833 Update ping7.md
  articles/protocols/saml/identity-providers/ping7.md
Labels: ready-for-review

#6834 Delegation warning updates
  articles/_includes/_deprecate-delegation.md
  articles/api-auth/intro.md
  articles/api-auth/tutorials/adoption/_index.md
  articles/api-auth/tutorials/adoption/api-tokens.md
  articles/api-auth/tutorials/adoption/delegation.md
  articles/api-auth/tutorials/adoption/refresh-tokens.md
  articles/best-practices/application-settings.md
  articles/integrations/aws-api-gateway/delegation/_delegation-version-warning.md
  articles/integrations/aws-api-gateway/delegation/index.md
  articles/integrations/aws-api-gateway/delegation/part-1.md
  articles/integrations/aws-api-gateway/delegation/part-2.md
  articles/integrations/aws-api-gateway/delegation/part-3.md
  articles/integrations/aws-api-gateway/delegation/part-4.md
  articles/integrations/aws-api-gateway/delegation/part-5.md
  articles/libraries/auth0js/v8/migration-guide.md
  articles/libraries/lock-android/v2/delegation-api.md
  articles/libraries/lock-ios/v2/migration.md
Labels: ready-for-review

#6831 Update Universal Login Add'l Parameters
  articles/custom-domains/additional-configuration.md
Labels: ready-for-review

#6804 Added spacing after sentence
  articles/applications/machine-to-machine.md
Labels: ready-for-review

#6836 Fix quotes
  articles/quickstart/backend/rails/01-authorization.md
Labels: quickstart

#6846 Add note on MFA not working with popup mode
  articles/libraries/lock/v11/authentication-modes.md
Labels: ready-for-review

#6845 Clarify how rules are executed
  articles/rules/current/index.md
Labels: ready-for-review

#6842 Quick fix for SSO page
  articles/sso/current/setup.md
Labels: ready-for-review

#6850 Update articles/connections/pass-parameters-to-idps.md
  articles/connections/pass-parameters-to-idps.md
Labels: ready-for-review

#6864 Fixed minor typos and toc setting
  articles/tokens/add-custom-claims.md
  articles/tokens/get-access-tokens.md
  articles/tokens/overview-access-tokens.md
Labels: ready-for-review

#6808 Password length docs updates
  articles/connections/database/password-strength.md
  articles/hosted-pages/password-reset.md
Labels: do-not-merge

#6754 Updating Laravel version from 5.5 to 5.7 in urls
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/laravel/index.yml
Labels: do-not-merge, quickstart

#6870 Update articles/api/management/v2/tokens.md
  articles/api/management/v2/tokens.md
Labels: ready-for-review

#6847 Added a Missing Comma
  articles/email/index.md
Labels: ready-for-review

#6813 Improvements based on suggestions by @jfromaniello and @rcocetta:
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart

#6820 Update _new_app.md: Minor grammar change
  articles/_includes/_new_app.md
Labels: ready-for-review

#6816 Update incorrect reference to user_profile
  articles/user-profile/user-profile-details.md
Labels: ready-for-review

#6857 Fix a few typos
  articles/connections/social/facebook.md
  articles/extensions/authorization-extension/v2/rules.md
  articles/integrations/authenticating-devices-using-mqtt.md
  articles/libraries/lock-android/v2/native-social-authentication.md
  articles/libraries/lock-ios/v2/migration.md
  articles/libraries/lock/v9/ui-customization.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_setup.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_setup.md
Labels: ready-for-review

#6458 Scala web app update 01-login.md
  articles/quickstart/webapp/scala/01-login.md
Labels: quickstart

#6868 Fix minor typo
  articles/anomaly-detection/breached-passwords.md
Labels: ready-for-review

#6848 Corrected a Typo
  articles/users/search/v3/index.md
Labels: ready-for-review

#6849 Update b2b arch scenario
  articles/architecture-scenarios/b2b.md
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/index.md
Labels: ready-for-review

#6875 Updated Delegated Admin page
  articles/extensions/delegated-admin/v3/index.md
  media/articles/extensions/delegated-admin/install-extension.png
Labels: ready-for-review

#6693 Instructions on getting the access token expiration time
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
Labels: quickstart, verified

#6892 Adding custom error pages liquid syntax variables names [DO NOT MERGE]
  articles/hosted-pages/custom-error-pages.md
Labels: ready-for-review

#6883 Azure Tutorial Update
  articles/integrations/azure-tutorial.md
Labels: ready-for-review
