Repository auth0/docs, pull requests merged in 2018-07, with the labels that each got.

#6352 Add/fix troubleshooting steps; add new filters; fix how it works page
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/how-does-it-work.md
  articles/cms/wordpress/troubleshoot.md
Labels: ready-for-review

#6326 Convert ASP.NET (OWIN) Quickstarts to OWIN 4
  articles/quickstart/backend/webapi-owin/01-authorization.md
  articles/quickstart/backend/webapi-owin/03-troubleshooting.md
  articles/quickstart/backend/webapi-owin/index.yml
  articles/quickstart/webapp/aspnet-owin/00-intro.md
  articles/quickstart/webapp/aspnet-owin/01-login.md
  articles/quickstart/webapp/aspnet-owin/02-user-profile.md
  articles/quickstart/webapp/aspnet-owin/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/04-migrating.md
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
  articles/quickstart/webapp/aspnet-owin/_includes/_setup.md
  articles/quickstart/webapp/aspnet-owin/dashboard-default.md
  articles/quickstart/webapp/aspnet-owin/index.yml
Labels: quickstart

#6380 Updating Lock options to add passwordlessMethod and alter clientBaseUrl
  articles/libraries/lock/v11/configuration.md
Labels: ready-for-review

#6210 Delegated Admin + Hooks Update
  articles/extensions/delegated-admin/index.yml
  articles/extensions/delegated-admin/v2/hooks.md
  articles/extensions/delegated-admin/v2/index.md
  articles/extensions/delegated-admin/v2/manage-users.md
  articles/extensions/delegated-admin/v3/hooks/_stepnav.html
  articles/extensions/delegated-admin/v3/hooks/access.md
  articles/extensions/delegated-admin/v3/hooks/filter.md
  articles/extensions/delegated-admin/v3/hooks/index.md
  articles/extensions/delegated-admin/v3/hooks/membership.md
  articles/extensions/delegated-admin/v3/hooks/settings.md
  articles/extensions/delegated-admin/v3/hooks/write.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/delegated-admin/v3/manage-users.md
Labels: do-not-merge

#6183 Custom DB Docs Revamp
  articles/connections/database/custom-db.md
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/error-handling.md
  articles/connections/database/custom-db/index.md
  articles/connections/database/custom-db/lock.md
  articles/connections/database/custom-db/metadata.md
  articles/connections/database/custom-db/templates/change-password.md
  articles/connections/database/custom-db/templates/create.md
  articles/connections/database/custom-db/templates/delete.md
  articles/connections/database/custom-db/templates/get-user.md
  articles/connections/database/custom-db/templates/index.md
  articles/connections/database/custom-db/templates/login.md
  articles/connections/database/custom-db/templates/verify.md
  articles/connections/database/custom-db/troubleshooting.md
Labels: do-not-merge

#6397 SAML Updates
  articles/protocols/saml/adfs.md
  articles/protocols/saml/saml2webapp-tutorial.md
Labels: do-not-merge

#6404 Update error messages
  articles/libraries/error-messages.md
Labels: do-not-merge

#6411 Remove confusing line item
  articles/libraries/when-to-use-lock.md
Labels: ready-for-review

#6413 Edit OneLogin (SAML IdP) doc
  articles/protocols/saml/identity-providers/onelogin.md
Labels: ready-for-review

#6200 Laravel backend: Update CORS configuration
  articles/quickstart/backend/laravel/01-authorization.md
Labels: quickstart

#6206 Update 01-authorization.md
  articles/quickstart/backend/java-spring-security/01-authorization.md
Labels: quickstart

#6421 Add warning callout for callback URL caching
  articles/cms/wordpress/configuration.md
Labels: ready-for-review

#6406 Custom DB Docs
  articles/connections/database/custom-db.md
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/error-handling.md
  articles/connections/database/custom-db/index.md
  articles/connections/database/custom-db/templates/change-password.md
  articles/connections/database/custom-db/templates/create.md
  articles/connections/database/custom-db/templates/delete.md
  articles/connections/database/custom-db/templates/get-user.md
  articles/connections/database/custom-db/templates/index.md
  articles/connections/database/custom-db/templates/login.md
  articles/connections/database/custom-db/templates/verify.md
Labels: ready-for-review

#6429 Updates to various ASP.NET Quickstarts
  articles/quickstart/backend/webapi-owin/download.md
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_login.md
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
  articles/quickstart/webapp/aspnet-owin/download.md
Labels: quickstart

#6425 Update enable-disable.md
  articles/hooks/cli/create-delete.md
  articles/hooks/cli/edit.md
  articles/hooks/cli/enable-disable.md
  articles/hooks/cli/index.md
  articles/hooks/cli/logs.md
  articles/hooks/dashboard/create-delete.md
  articles/hooks/dashboard/edit.md
  articles/hooks/dashboard/enable-disable.md
  articles/hooks/extensibility-points/credentials-exchange.md
  articles/hooks/extensibility-points/post-user-registration.md
  articles/hooks/extensibility-points/pre-user-registration.md
  articles/hooks/overview.md
Labels: ready-for-review

#6430 Quickstarts React-native: Improve download instructions
  articles/quickstart/native/react-native/download.md
Labels: quickstart
