Repository auth0/docs, pull requests merged in 2018-11, with the labels that each got.

#6904 Users having trouble finding correct reset password pages
  articles/connections/database/password-change.md
  articles/hosted-pages/password-reset.md
  articles/support/reset-account-password.md
Labels: ready-for-review

#6903 Added examples of Other SMTP
  articles/email/providers.md
Labels: ready-for-review

#6901 Added _session-timout.md include
  articles/extensions/delegated-admin/v3/_session-timeout.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/delegated-admin/v3/manage-users.md
Labels: ready-for-review

#6837 Add _include for Magic Link browser limitations
  articles/connections/passwordless/_single-browser-magic-link.md
  articles/connections/passwordless/faq.md
  articles/connections/passwordless/ios-magic-link.md
  articles/connections/passwordless/regular-web-app-email-link.md
  articles/connections/passwordless/spa-email-link.md
  articles/connections/passwordless/user-guide.md
  articles/hosted-pages/login/auth0js.md
Labels: ready-for-review

#6907 Update Monitoring Mentions for Appliance
  articles/appliance/index.html
  config/sidebar.yml
Labels: do-not-merge

#6912 iOS biometric auth
  articles/libraries/auth0-swift/touchid-authentication.md
Labels: ready-for-review

#6913 Include phone number is only valid with SMS connections
  articles/user-profile/user-profile-structure.md
Labels: ready-for-review

#6915 Update user export tutorials for marketing
  articles/integrations/index.md
  articles/integrations/marketing/adobe-campaign/index.md
  articles/integrations/marketing/alterian/index.md
  articles/integrations/marketing/constant-contact/index.md
  articles/integrations/marketing/eloqua/index.md
  articles/integrations/marketing/index.md
  articles/integrations/marketing/mailchimp/index.md
  articles/integrations/marketing/marketo/index.md
  articles/integrations/marketing/sailthru/index.md
  articles/integrations/marketing/salesforce-marketing-cloud/index.md
  articles/integrations/marketing/salesforce/index.md
  articles/integrations/marketing/watson-campaign-automation/index.md
Labels: ready-for-review

#6792 Fix bias in randomString()
  articles/api-auth/tutorials/nonce.md
Labels: ready-for-review

#6917 Update Appliance Monitoring Docs
  articles/appliance/dashboard/index.md
  articles/appliance/dashboard/instrumentation.md
  articles/appliance/instrumentation.md
  articles/appliance/instrumentation/add-grafana-users.md
  articles/appliance/instrumentation/available-metrics.md
  articles/appliance/instrumentation/components.md
  articles/appliance/instrumentation/index.md
  articles/appliance/instrumentation/visualize-data.md
  articles/appliance/monitoring/authenticated-endpoints.md
  articles/appliance/monitoring/index.md
  config/redirects.js
  media/articles/appliance/instrumentation/general-data.png
  media/articles/appliance/instrumentation/grafana-users-1.png
  media/articles/appliance/instrumentation/grafana-users-2.png
  media/articles/appliance/instrumentation/grafana-users-3.png
  media/articles/appliance/instrumentation/grafana-users-4.png
  media/articles/appliance/instrumentation/tag-dashboard.png
Labels: do-not-merge

#6918 Wrong information provided
  articles/user-profile/user-profile-structure.md
Labels: ready-for-review, update-needed

#6919 Updates for WP v3.8.0
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/invalid-state.md
  articles/cms/wordpress/troubleshoot.md
Labels: ready-for-review

#6930 Edit Penetration Test Policy doc
  articles/policies/penetration-testing.md
Labels: ready-for-review

#6289 Browser-based vs native login docs
  articles/api-auth/grant/authorization-code-pkce.md
  articles/design/browser-based-vs-native-experience-on-mobile.md
Labels: ready-for-review

#6931 Added feature availability panel.
  articles/connections/database/custom-db/index.md
Labels: ready-for-review

#6932 Add how to reach out if free account compromised per Community post
  articles/support/index.md
Labels: ready-for-review

#6937 Update twitter account for community
  articles/support/index.md
Labels: ready-for-review

#6973 Remove SPA Quickstarts
  articles/api-auth/tutorials/silent-authentication.md
  articles/logout/index.md
  articles/quickstart/spa/angularjs/01-login.md
  articles/quickstart/spa/angularjs/02-user-profile.md
  articles/quickstart/spa/angularjs/03-calling-an-api.md
  articles/quickstart/spa/angularjs/04-authorization.md
  articles/quickstart/spa/angularjs/05-token-renewal-download.md
  articles/quickstart/spa/angularjs/05-token-renewal.md
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
  articles/quickstart/spa/angularjs/_includes/_install_angular_auth0.md
  articles/quickstart/spa/angularjs/download.md
  articles/quickstart/spa/angularjs/index.yml
  articles/quickstart/spa/aurelia/01-login.md
  articles/quickstart/spa/aurelia/_includes/_centralized_login.md
  articles/quickstart/spa/aurelia/download.md
  articles/quickstart/spa/aurelia/index.yml
  articles/quickstart/spa/ember/01-login.md
  articles/quickstart/spa/ember/_includes/_centralized_login.md
  articles/quickstart/spa/ember/download.md
  articles/quickstart/spa/ember/index.yml
  articles/quickstart/spa/jquery/01-login.md
  articles/quickstart/spa/jquery/02-user-profile.md
  articles/quickstart/spa/jquery/03-calling-an-api.md
  articles/quickstart/spa/jquery/04-authorization.md
  articles/quickstart/spa/jquery/05-token-renewal-download.md
  articles/quickstart/spa/jquery/05-token-renewal.md
  articles/quickstart/spa/jquery/_includes/_centralized_login.md
  articles/quickstart/spa/jquery/download.md
  articles/quickstart/spa/jquery/index.yml
  articles/support/matrix.md
  articles/users/normalized/oidc/index.md
  config/redirects.js
Labels: quickstart

#6967 Updated anomaly-detection
  articles/anomaly-detection/index.md
Labels: ready-for-review

#6979 Rewrote monitoring section, fixed index page
  articles/monitoring/how-to-monitor-auth0.md
  articles/monitoring/index.md
  articles/monitoring/sending-events-to-keenio.md
  articles/monitoring/sending-events-to-segmentio.md
  articles/monitoring/sending-events-to-splunk.md
  articles/monitoring/track-signups-enrich-user-profile-generate-leads.md
  articles/monitoring/tracking-new-leads-in-salesforce-and-raplead.md
  media/articles/tutorials/rapleaf-salesforce.png
Labels: ready-for-review

#6978 Add New Best Practices
  articles/best-practices/application-settings.md
  articles/best-practices/connection-settings.md
  articles/best-practices/index.md
  articles/best-practices/operations.md
  articles/best-practices/rules.md
  articles/best-practices/search-best-practices.md
  articles/best-practices/tenant-settings.md
  articles/best-practices/user-data-storage-best-practices.md
  articles/compliance/gdpr/features-aiding-compliance/data-portability.md
  articles/compliance/gdpr/features-aiding-compliance/right-to-access-data.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/index.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/rules/current/management-api.md
  articles/users/concepts/overview-user-metadata.md
  articles/users/guides/manage-user-metadata.md
  articles/users/guides/read-metadata.md
  articles/users/guides/set-metadata-properties-on-creation.md
  articles/users/guides/update-user-profiles-using-your-database.md
  articles/users/references/metadata-field-name-rules.md
  articles/users/references/user-profile-structure.md
  articles/users/search/v2/index.md
  articles/users/search/v3/index.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review
