Repository auth0/docs, pull requests merged in 2018-05, with the labels that each got.

#6132 Adding a line of clarification to the migration
  articles/migrations/index.md
Labels: ready-for-review

#6128 Fix code snippet
  articles/architecture-scenarios/implementations/spa-api/api-implementation-nodejs.md
Labels: ready-for-review

#6127 typo fix
  articles/design/creating-invite-only-applications.md
Labels: ready-for-review

#6126 Adding status monitors
  articles/monitoring/how-to-monitor-auth0.md
Labels: ready-for-review

#6135 Update _ip_ranges.md
  articles/libraries/_includes/_ip_ranges.md
Labels: ready-for-review

#6136 Fix article
  articles/api/authentication/legacy/_delegation.md
  articles/api/management/v2/tokens.md
  articles/applications/addons.md
  articles/applications/connections.md
  articles/architecture-scenarios/application/web-app-sso/index.md
  articles/architecture-scenarios/application/web-app-sso/part-2.md
  articles/cms/wordpress/configuration.md
  articles/connections/calling-an-external-idp-api.md
  articles/dashboard/creating-users-in-the-management-portal.md
  articles/logout/index.md
  articles/protocols/oidc/index.md
  articles/protocols/saml/identity-providers/ssocircle.md
  articles/protocols/saml/samlsso-auth0-to-auth0.md
  articles/rules/current/metadata-in-rules.md
  articles/sso/legacy/index.md
  articles/tokens/access-token.md
Labels: ready-for-review

#6129 Update kerberos.md
  articles/connector/kerberos.md
Labels: ready-for-review

#6120 Example for getting tokens for new API
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review

#6094 Adding deprecation error reference and linking from migration guides
  articles/errors/deprecation-errors.md
  articles/libraries/_includes/_verifying_migration.md
  media/articles/errors/depnotes-legacy-lock-context-data.png
  media/articles/errors/depnotes-logs.png
  media/articles/errors/depnotes-mgt-api-legacy-lock.png
  media/articles/errors/depnotes-mgt-api-ssodata.png
  media/articles/errors/depnotes-ssodata-context-data.png
  media/articles/errors/libraries/dashboard-logs.png
  media/articles/errors/libraries/management-api-logs-results.png
  media/articles/errors/libraries/management-api-logs.png
  media/articles/errors/libraries/management-api-set-token.png
Labels: ready-for-review

#6150 Updating library versions
  config/vars.yml
Labels: ready-for-review

#6146 Add how-to on changing session expiration length
  articles/integrations/aws/sso.md
Labels: ready-for-review

#6139 First draft of the deprecation guidance doc
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/migrations/index.md
Labels: ready-for-review

#6145 Clarify only one tenant is deleted.
  articles/support/_delete-tenant.md
Labels: ready-for-review

#6144 Clarify child account policy
  articles/dev-lifecycle/setting-up-env.md
Labels: ready-for-review

#6142 Appliance: Internet Requirements
  articles/appliance/infrastructure/faq.md
  articles/appliance/infrastructure/internet-restricted-deployment.md
  articles/getting-started/deployment-models.md
Labels: ready-for-review

#6031 Add link to metadata handling in custom DBs
  articles/connections/database/custom-db.md
Labels: ready-for-review

#6008 Move mfa endpoints to authentication api section
  articles/api/authentication/_multifactor-authentication.md
  articles/api/authentication/api-authz/_get-token.md
  articles/api/authentication/index.md
Labels: ready-for-review

#6140 Fix Golang jwks multi-key logic error
  articles/quickstart/backend/golang/01-authorization.md
Labels: quickstart

#6154 Add caveat about Try All Rules button
  articles/rules/current/index.md
Labels: ready-for-review

#6155 Fixing highlighting + line length by removing code block
  articles/migrations/guides/legacy-lock-api-deprecation.md
Labels: ready-for-review

#6015 Update 03-calling-an-api.md for Angular2
  articles/quickstart/spa/angular2/03-calling-an-api.md
Labels: quickstart

#5998 Update 03-calling-an-api.md for AngularJS
  articles/quickstart/spa/angularjs/03-calling-an-api.md
Labels: quickstart

#6166 Updating notice
  articles/_includes/_lock_auth0js_deprecations_notice.md
Labels: ready-for-review

#6172 Update Hooks pages
  articles/hooks/extensibility-points/pre-user-registration.md
  articles/hooks/overview.md
Labels: do-not-merge

#6173 Fixed QS ports
  articles/quickstart/spa/aurelia/dashboard-default.md
  articles/quickstart/spa/jquery/dashboard-default.md
  articles/quickstart/spa/vanillajs/dashboard-default.md
  articles/quickstart/spa/vuejs/dashboard-default.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
Labels: quickstart

#5912 Update 01-authorization.md
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart

#6175 Rename applications to clients
  articles/api-auth/dynamic-client-registration.md
  articles/api-auth/index.md
  articles/api-auth/intro.md
  articles/api-auth/tutorials/adoption/index.md
  articles/api-auth/user-consent.md
  articles/applications/index.md
  config/redirects.js
Labels: do-not-merge

#6179 Improved the Calling your API doc
  articles/quickstart/backend/_includes/_api_using.md
Labels: quickstart

#6164 adding safari info about cross origin auth
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#6186 Angular QS fixes
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart, ready-for-review

#6190 search user v3: include a new breaking change
  articles/users/search/v3/index.md
Labels: ready-for-review

#6188 Fixing broken image URL
  articles/design/creating-invite-only-applications.md
Labels: ready-for-review

#6180 Update Xamarin Quickstart for 2.0.0
  articles/quickstart/native/windows-uwp-csharp/01-login.md
  articles/quickstart/native/wpf-winforms/01-login.md
  articles/quickstart/native/xamarin/01-login.md
  snippets/native-platforms/xamarin/dependencies.md
  snippets/native-platforms/xamarin/setup.md
Labels: quickstart

#5946 Upstream params
  articles/connections/_quickstart-links.md
  articles/connections/index.md
  articles/connections/pass-parameters-to-idps.md
  config/sidebar.yml
Labels: update-needed

#6194 Updating deprecation errors
  articles/errors/deprecation-errors.md
Labels: ready-for-review

#6171 list "ready" events for signin and signup pages
  articles/libraries/lock/v11/api.md
Labels: ready-for-review

#6213 Info re: Types of Appliance Releases
  articles/appliance/admin/updating-the-appliance.md
Labels: do-not-merge

#6157 Notes on IP Addresses when using Hooks, Rules, Custom DB Conn.
  articles/_includes/_ip_whitelist.md
  articles/connections/database/custom-db.md
  articles/hooks/overview.md
  articles/rules/current/index.md
Labels: ready-for-review

#6219 Updating the Appliance
  articles/appliance/admin/updating-the-appliance.md
Labels: do-not-merge
