Repository auth0/docs, pull requests merged in 2019-06, with the labels that each got.

#7383 JavaScript Quickstart: Logout from Auth0 authorization server
  articles/quickstart/spa/vanillajs/01-login.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart

#7688 Update glossary.json
  config/glossary.json
Labels: do-not-merge

#7711 Clarifying wording to not indicate a requirement
  articles/custom-domains/self-managed-certificates.md
Labels: ready-for-review

#7546 Universal Login i18n docs
  articles/i18n/index.md
  articles/universal-login/i18n.md
  articles/universal-login/new-experience-limitations.md
  articles/universal-login/new.md
  config/sidebar.yml
Labels: do-not-merge

#7594 Updates for WP-Auth0 3.11.0
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/installation.md
  articles/cms/wordpress/troubleshoot.md
  articles/cms/wordpress/user-migration.md
  media/articles/cms/wordpress/auth0-custom-database-config.png
Labels: ready-for-review

#7721 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#7724 Removed deprecated links
  articles/multifactor-authentication/developer/index.md
Labels: ready-for-review

#7723 Update installation.md
  articles/appliance/infrastructure/installation.md
Labels: ready-for-review

#7086 Update Kerberos Lock examples
  articles/connector/kerberos.md
Labels: do-not-merge

#7717 Add instructions on how to test APIs
  articles/quickstart/backend/java-spring-security/01-authorization.md
Labels: quickstart

#7722 Shorten, fix typos
  config/glossary.json
Labels: ready-for-review

#7720 Update Azure API Gateway tutorial
  articles/integrations/azure-api-management/configure-azure.md
Labels: ready-for-review

#7719 Updating MFA API documentation
  articles/multifactor-authentication/api/_includes/_authenticator-before-start.md
  articles/multifactor-authentication/api/_includes/_get_mfa_token.md
  articles/multifactor-authentication/api/_includes/_recovery_codes.md
  articles/multifactor-authentication/api/_includes/_request_association.md
  articles/multifactor-authentication/api/_includes/_successful_confirmation.md
  articles/multifactor-authentication/api/challenges.md
  articles/multifactor-authentication/api/email.md
  articles/multifactor-authentication/api/index.md
  articles/multifactor-authentication/api/manage.md
  articles/multifactor-authentication/api/oob.md
  articles/multifactor-authentication/api/otp.md
Labels: ready-for-review

#7715 Implementation Resources new content
  articles/architecture-scenarios/implementation-resources.md
  articles/architecture-scenarios/index.md
  config/sidebar.yml
  phase-1-implementation-milestones.png
Labels: ready-for-review

#7725 Updated Spring Security API Quickstart documentation to use Gradle
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/java-spring-security/index.yml
Labels: quickstart

#7730 co-authentication updates
  articles/_includes/_embedded_login_warning.md
  articles/api/authentication/_login.md
  articles/cms/wordpress/troubleshoot.md
  articles/cross-origin-authentication/fingerprinting.md
  articles/cross-origin-authentication/index.md
  articles/guides/login/migration-sso.md
  articles/guides/login/universal-vs-embedded.md
  articles/libraries/lock/v11/index.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/security/bulletins/cve-2018-6874.md
Labels: ready-for-review

#7734 Removed embedded login link from React quickstart
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#7659 Symfony Web App Quickstart: Add logout implementation
  articles/quickstart/webapp/symfony/01-login.md
  articles/quickstart/webapp/symfony/download.md
Labels: quickstart

#7664 PHP Web App Quickstart: Add logout implementation
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/download.md
Labels: quickstart

#7690 ASP.NET OWIN Web App Quickstart: Update download instructions
  articles/quickstart/webapp/aspnet-owin/_includes/_setup.md
  articles/quickstart/webapp/aspnet-owin/download.md
Labels: quickstart

#7691 ASP.NET Core 1.1 Web App Quickstart: Update download instructions
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core-v1_1/download.md
Labels: quickstart

#7694 ASP.NET Core 2 Web App Quickstart: Update download instructions
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/download.md
Labels: quickstart

#7698 Django Web App Quickstart: Update download instructions
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/django/download.md
Labels: quickstart

#7702 Go Web App Quickstart: Update download instructions
  articles/quickstart/webapp/golang/01-login.md
  articles/quickstart/webapp/golang/download.md
Labels: quickstart

#7703 Node.js Web App Quickstart: Update download instructions
  articles/quickstart/webapp/nodejs/01-login.md
  articles/quickstart/webapp/nodejs/download.md
Labels: quickstart

#7704 Laravel Web App Quickstart: Update download instructions
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/laravel/download.md
Labels: quickstart

#7708 Python Web App Quickstart: Update download instructions
  articles/quickstart/webapp/python/01-login.md
  articles/quickstart/webapp/python/download.md
Labels: quickstart

#7709 Rails Web App Quickstart: Update download instructions
  articles/quickstart/webapp/rails/01-login.md
  articles/quickstart/webapp/rails/download.md
Labels: quickstart

#7743 Fixed logout_url includes for aspnet-core quickstarts
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
Labels: quickstart

#7729 Improve the WordPress installation instructions
  articles/cms/wordpress/installation.md
  media/articles/cms/wordpress/setup-wizard-social-modal.png
Labels: ready-for-review

#7753 Updated Spring MVC Security Quickstart to support updated sample
  articles/quickstart/webapp/java-spring-security-mvc/01-login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
Labels: quickstart

#7748 Fix link
  articles/private-saas-deployment/private-cloud/index.md
Labels: ready-for-review

#7747 Update LinkedIn Social Connection Setup Doc
  articles/connections/social/linkedin.md
Labels: ready-for-review

#7740 Updating screenshot
  articles/universal-login/password-reset.md
  media/articles/universal-login/password-reset.png
Labels: ready-for-review

#7759 Removing outdated video until it is redone
  articles/connections/database/custom-db/index.md
Labels: ready-for-review

#7760 Defining Application-Specific Access
  articles/dashboard/manage-dashboard-admins.md
Labels: ready-for-review

#7764 Fix broken logo for G Suite
  articles/connections/enterprise/google-apps.md
Labels: ready-for-review

#7763 Fix redirect
  config/redirects.js
Labels: ready-for-review

#7776 Added auth0-spa-js installation instructions
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/_includes/_install_auth0-spa-js.md
Labels: quickstart

#7783 Sign in with apple connection
  articles/connections/social/apple.md
  media/articles/connections/social/apple/apple_connection.png
  media/connections/apple.svg
Labels: ready-for-review

#7775 clean commit of sidebar changes
  articles/architecture-scenarios/_includes/_base-intro.md
  articles/architecture-scenarios/_includes/_base-ways-to-integrate.md
  articles/architecture-scenarios/_includes/_implementation-checklists.md
  articles/architecture-scenarios/b2b.md
  articles/architecture-scenarios/b2c.md
  config/sidebar.yml
Labels: do-not-merge

#7771 Remove warning about delay on client secret rotation
  articles/dashboard/guides/applications/rotate-client-secret.md
Labels: ready-for-review, tiny

#7792 fix react error from glossary tags
  articles/api-auth/tutorials/adoption/password.md
  articles/api-auth/tutorials/adoption/refresh-tokens.md
  articles/migrations/guides/_get-token-auth0js.md
  articles/migrations/guides/calling-api-with-idtokens.md
Labels: ready-for-review

#7710 Conditionally include logout URL based on returnTo variable
  articles/quickstart/spa/_includes/_getting_started.md
Labels: quickstart

#7809 Remove text that went with removed video
  articles/connections/database/custom-db/index.md
Labels: ready-for-review, tiny

#7796 Fix broken link
  articles/multifactor-authentication/custom.md
Labels: ready-for-review, tiny

#7797 Correct subheading for appliance
  articles/appliance/index.html
Labels: ready-for-review, tiny

#7812 Add warning to PSaaS Custom Domains
  articles/appliance/custom-domains/index.md
Labels: ready-for-review, tiny

#7810 Add user code config info to device docs
  articles/dashboard/guides/tenants/configure-device-user-code-settings.md
  articles/dashboard/guides/tenants/configure-session-lifetime-settings.md
  articles/dashboard/guides/tenants/enable-sso-tenant.md
  articles/flows/guides/device-auth/call-api-device-auth.md
  articles/flows/guides/device-auth/includes/request-device-code.md
  media/articles/dashboard/guides/tenants/tenant-settings-advanced-device-user-code.png
  media/articles/dashboard/guides/tenants/tenant-settings-advanced-login-session-management.png
  media/articles/dashboard/guides/tenants/tenant-settings.png
Labels: ready-for-review, small

#7813 Implement new content from Prof Services
  articles/services/index.md
  config/sidebar.yml
  media/articles/services/Auth0-Services-Advanced.pdf
  media/articles/services/Auth0-Services-Basic.pdf
  media/articles/services/Auth0-Services-Discovery-Workshop.pdf
  media/articles/services/Auth0-Services-HealthCheck.pdf
  media/articles/services/Auth0-Services-Premier-Success.pdf
  media/articles/services/Auth0-Services-Standard.pdf
Labels: ready-for-review

#7816 Add checklist files and new links
  articles/architecture-scenarios/checklists.md
  media/articles/architecture-scenarios/checklists/Analyze-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/Build-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/Deploy-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/Design-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/Monitor-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/Test-Checklist.xlsx
  media/articles/architecture-scenarios/checklists/file_type_icons-02.png
Labels: small

#7801 B2b profile mgmt phase 1
  articles/architecture-scenarios/_includes/_architecture/_introduction.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_introduction.md
  articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
  articles/architecture-scenarios/implementation/b2b/b2b-profile-mgmt.md
Labels: do-not-merge

#7818 Remove OIDC conformant notice
  articles/api-auth/apis.md
  articles/api-auth/dynamic-client-registration.md
  articles/api-auth/grant/authorization-code-pkce.md
  articles/api-auth/grant/authorization-code.md
  articles/api-auth/grant/implicit.md
  articles/api-auth/grant/password.md
  articles/api-auth/index.md
  articles/api-auth/tutorials/authorization-code-grant-pkce.md
  articles/api-auth/tutorials/authorization-code-grant.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/api-auth/tutorials/implicit-grant.md
  articles/api-auth/tutorials/multifactor-resource-owner-password.md
  articles/api-auth/tutorials/nonce.md
  articles/api-auth/tutorials/password-grant.md
  articles/api-auth/tutorials/silent-authentication.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
  articles/api-auth/tutorials/verify-access-token.md
  articles/api-auth/user-consent.md
  articles/api-auth/which-oauth-flow-to-use.md
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
  articles/getting-started/the-implementation-process.md
Labels: ready-for-review, small

#7807 B2B phase 1 & 2 provisioning
  articles/architecture-scenarios/_includes/_b2b-planning.md
  articles/architecture-scenarios/_includes/_provisioning/_deprovisioning.md
  articles/architecture-scenarios/_includes/_provisioning/_introduction.md
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
Labels: do-not-merge

#7819 Unresolved review comments
  articles/architecture-scenarios/_includes/_architecture/_introduction.md
  articles/architecture-scenarios/_includes/_branding/_custom-domain-naming.md
  articles/architecture-scenarios/_includes/_branding/_introduction.md
  articles/architecture-scenarios/_includes/_branding/_password-reset.md
  articles/architecture-scenarios/_includes/_logout/_introduction.md
  articles/architecture-scenarios/_includes/_operations/_introduction.md
  articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
  articles/architecture-scenarios/implementation/b2b/b2b-operations.md
Labels: do-not-merge, in-review

#7822 Added new planning guide links
  articles/architecture-scenarios/_includes/_b2b-planning.md
  articles/architecture-scenarios/_includes/_planning.md
  articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
  articles/architecture-scenarios/implementation/b2b/b2b-authorization.md
  articles/architecture-scenarios/implementation/b2b/b2b-branding.md
  articles/architecture-scenarios/implementation/b2b/b2b-deployment.md
  articles/architecture-scenarios/implementation/b2b/b2b-logout.md
  articles/architecture-scenarios/implementation/b2b/b2b-operations.md
  articles/architecture-scenarios/implementation/b2b/b2b-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
  articles/architecture-scenarios/implementation/b2b/b2b-qa.md
  articles/architecture-scenarios/implementation/b2c/b2c-architecture.md
  articles/architecture-scenarios/implementation/b2c/b2c-authentication.md
  articles/architecture-scenarios/implementation/b2c/b2c-authorization.md
  articles/architecture-scenarios/implementation/b2c/b2c-branding.md
  articles/architecture-scenarios/implementation/b2c/b2c-deployment.md
  articles/architecture-scenarios/implementation/b2c/b2c-logout.md
  articles/architecture-scenarios/implementation/b2c/b2c-operations.md
  articles/architecture-scenarios/implementation/b2c/b2c-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2c/b2c-provisioning.md
  articles/architecture-scenarios/implementation/b2c/b2c-qa.md
  media/articles/architecture-scenarios/planning/B2B-Project-Planning.pdf
  media/articles/architecture-scenarios/planning/B2C-Project-Planning.pdf
Labels: do-not-merge

#7754 updated context-object.md
  articles/rules/references/context-object.md
Labels: ready-for-review, tiny

#7831 Changed auth0-spa-js CDN URL
  config/vars.yml
Labels: tiny

#7634 PSaaS Custom Domain Migration
  articles/private-saas-deployment/custom-domain-migration.md
Labels: ready-for-review

#7833 Update glossary definitions
  config/glossary.json
Labels: ready-for-review

#7828 Change app types link to more applicable one
  articles/applications/concepts/app-types-auth0.md
  articles/protocols/saml/saml-idp-generic.md
Labels: ready-for-review, tiny

#7830 Remove screenshot
  articles/protocols/saml/samlsso-auth0-to-auth0.md
Labels: ready-for-review, tiny

#7832 Add textual steps under diagram
  articles/connector/overview.md
Labels: ready-for-review, tiny

#7834 Removed link and clarified test user to create
  articles/protocols/saml/adfs.md
Labels: ready-for-review, tiny

#7835 Update checklists.md
  articles/architecture-scenarios/checklists.md
Labels: ready-for-review, tiny

#7785 SPA SDK
  articles/_includes/_libraries_support_sdks.html
  articles/libraries/auth0-spa-js/index.md
  articles/libraries/index.md
  config/sidebar.yml
Labels: do-not-merge, ready-for-review

#7733 New Angular quickstart docs for auth0-spa-js
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/angular2/01-login.md
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/02-user-profile.md
  articles/quickstart/spa/angular2/03-calling-an-api.md
  articles/quickstart/spa/angular2/04-authorization.md
  articles/quickstart/spa/angular2/05-token-renewal-download.md
  articles/quickstart/spa/angular2/05-token-renewal.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/angular2/download.md
  articles/quickstart/spa/angular2/index.yml
Labels: quickstart

#7781 New Plain JavaScript auth0-spa-js quickstart docs
  articles/quickstart/spa/vanillajs/01-login.md
  articles/quickstart/spa/vanillajs/02-calling-an-api.md
  articles/quickstart/spa/vanillajs/02-user-profile.md
  articles/quickstart/spa/vanillajs/03-calling-an-api.md
  articles/quickstart/spa/vanillajs/04-authorization.md
  articles/quickstart/spa/vanillajs/05-token-renewal-download.md
  articles/quickstart/spa/vanillajs/05-token-renewal.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/download.md
  articles/quickstart/spa/vanillajs/index.yml
Labels: medium, quickstart

#7769 React quickstart docs with auth0-spa-js
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/react/02-user-profile.md
  articles/quickstart/spa/react/03-calling-an-api.md
  articles/quickstart/spa/react/04-authorization.md
  articles/quickstart/spa/react/05-token-renewal.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/react/download.md
  articles/quickstart/spa/react/index.yml
Labels: medium, quickstart

#7814 OIDC Connection Docs
  articles/connections/enterprise/oidc.md
  media/articles/connections/enterprise/oidc/oidc-details.png
  media/articles/connections/enterprise/oidc/oidc-small.png
Labels: do-not-merge

#7839 Fixed follow-on links for React and Angular in SPA Quickstart docs
  articles/quickstart/spa/angular2/index.yml
  articles/quickstart/spa/react/index.yml
Labels: quickstart, tiny

#7795 Learn Identity video pages
  articles/videos/learn-identity/01-introduction-to-identity.md
  articles/videos/learn-identity/02-oidc-and-oauth.md
  articles/videos/learn-identity/03-web-sign-in.md
  articles/videos/learn-identity/04-calling-an-api.md
  articles/videos/learn-identity/05-desktop-and-mobile-apps.md
  articles/videos/learn-identity/06-single-page-apps.md
  articles/videos/learn-identity/index.md
  config/sections.yml
  config/sidebar.yml
  media/articles/learn-identity/learn-identity-intro.jpg
Labels: ready-for-review

#7836 Update --strip option for new product changes
  articles/extensions/deploy-cli/_includes/_strip-option.md
  articles/extensions/deploy-cli/guides/import-export-directory-structure.md
  articles/extensions/deploy-cli/guides/import-export-yaml-file.md
Labels: ready-for-review, tiny

#7837 Remove limitation because functionality added in latest release
  articles/extensions/deploy-cli/_includes/_limitations.md
Labels: ready-for-review, tiny

#7838 Fix broken link
  articles/libraries/index.md
Labels: ready-for-review, tiny

#7845 Removed unnecessary reference to onRedirectCallback
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: tiny

#7848 Add android auth0 account instance creation snippet
  articles/quickstart/native/android/_includes/_login.md
Labels: tiny

#7852 ia refactor: monitoring (/monitor)
  articles/guides-tutorials/monitor/_includes/_monitor-private-cloud.md
  articles/guides-tutorials/monitor/adldap-connector.md
  articles/guides-tutorials/monitor/applications.md
  articles/guides-tutorials/monitor/check-auth0-status.md
  articles/guides-tutorials/monitor/check-external-services.md
  articles/guides-tutorials/monitor/check-supporting-services.md
  articles/guides-tutorials/monitor/index.md
  articles/guides-tutorials/monitor/logs/index.md
  articles/guides-tutorials/monitor/logs/migrate-logs-v2-v3.md
  articles/guides-tutorials/monitor/logs/query-syntax.md
  articles/guides-tutorials/monitor/scom-adldap-connector.md
  articles/guides-tutorials/monitor/scom.md
  articles/guides-tutorials/monitor/send-events-to-keenio.md
  articles/guides-tutorials/monitor/send-events-to-segmentio.md
  articles/guides-tutorials/monitor/send-events-to-splunk.md
  articles/guides-tutorials/monitor/track-leads-salesforce.md
  articles/guides-tutorials/monitor/track-signups-salesforce.md
  config/temp-redirects.js
  config/temp-redirects.json
  config/temp-sidebars/monitor-sidebar.yml
  config/temp-sidebars/troubleshoot-sidebar.yml
Labels: ready-for-review

#7859 Added onRedirectCallback sample + explanation to React QS
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#7856 Remove broken links
  articles/api-auth/tutorials/silent-authentication.md
Labels: ready-for-review, tiny

#7858 Fix screenshot link
  articles/architecture-scenarios/mobile-api/part-2.md
Labels: ready-for-review, tiny

#7860 Add note re: external timeouts
  articles/best-practices/rules.md
Labels: ready-for-review, tiny

#7857 Fix capitalization of auth0.js
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review, small

#7861 Remove topics and add redirect
  articles/topics/_topic.md
  articles/topics/extensibility.md
  articles/topics/guides.md
  articles/topics/identity-glossary.md
  config/redirects.js
Labels: ready-for-review, small

#7862 Create Codeowners for quickstarts
  .github/CODEOWNERS
Labels: quickstart, tiny

#7726 Deprecations page
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/migrations/index.md
  articles/migrations/past-migrations.md
  articles/product-lifecycle/deprecation-eol.md
  articles/product-lifecycle/index.md
  articles/product-lifecycle/migrations.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7866 Add common error response to silent authentication
  articles/api-auth/tutorials/silent-authentication.md
Labels: ready-for-review, tiny

#7867 Amendments to the React SPA tutorial inline with the sample
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#7868 Amendment to Angular QS configuration based on user feedback
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart, tiny

#7840 Architecture Landing Page Redesign Tests
  articles/architecture-scenarios/_includes/_authentication/_introduction.md
  articles/architecture-scenarios/_includes/_authorization/_introduction.md
  articles/architecture-scenarios/_includes/_base-intro.md
  articles/architecture-scenarios/_includes/_base-ways-to-integrate.md
  articles/architecture-scenarios/_includes/_implementation-checklists.md
  articles/architecture-scenarios/_includes/_planning.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_account-verification.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_blocking-users.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_de-provisioning.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_introduction.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_linking-accounts.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_metadata.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_password-reset.md
  articles/architecture-scenarios/_includes/_provisioning/_deprovisioning.md
  articles/architecture-scenarios/_includes/_provisioning/_introduction.md
  articles/architecture-scenarios/_includes/_provisioning/_self-signup.md
  articles/architecture-scenarios/_includes/_provisioning/_social-signup.md
  articles/architecture-scenarios/_includes/_provisioning/_user-migration.md
  articles/architecture-scenarios/b2b.md
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/checklists.md
  articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
  articles/architecture-scenarios/implementation/b2b/b2b-authentication.md
  articles/architecture-scenarios/implementation/b2b/b2b-authorization.md
  articles/architecture-scenarios/implementation/b2b/b2b-branding.md
  articles/architecture-scenarios/implementation/b2b/b2b-deployment.md
  articles/architecture-scenarios/implementation/b2b/b2b-logout.md
  articles/architecture-scenarios/implementation/b2b/b2b-operations.md
  articles/architecture-scenarios/implementation/b2b/b2b-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
  articles/architecture-scenarios/implementation/b2b/b2b-qa.md
  articles/architecture-scenarios/implementation/b2c/b2c-architecture.md
  articles/architecture-scenarios/implementation/b2c/b2c-authentication.md
  articles/architecture-scenarios/implementation/b2c/b2c-authorization.md
  articles/architecture-scenarios/implementation/b2c/b2c-branding.md
  articles/architecture-scenarios/implementation/b2c/b2c-deployment.md
  articles/architecture-scenarios/implementation/b2c/b2c-logout.md
  articles/architecture-scenarios/implementation/b2c/b2c-operations.md
  articles/architecture-scenarios/implementation/b2c/b2c-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2c/b2c-provisioning.md
  articles/architecture-scenarios/implementation/b2c/b2c-qa.md
  articles/architecture-scenarios/index.md
  articles/architecture-scenarios/mobile-api/index.md
  media/articles/architecture-scenarios/b2b.png
  media/articles/architecture-scenarios/checklists/file_type_icons-02.png
  media/articles/architecture-scenarios/planning/file_type_icons-04.png
Labels: large, ready-for-review

#7870 Minor improvements to UL pages
  articles/universal-login/_implement_universal_login.md
  articles/universal-login/classic.md
  articles/universal-login/index.md
  articles/universal-login/new.md
Labels: ready-for-review

#7874 Fix logout URL instructions for Spring Security MVC Quickstart
  articles/quickstart/webapp/java-spring-security-mvc/download.md
Labels: quickstart

#7872 Delete Google doc
  articles/integrations/configuration-to-query-users-from-google-apps.md
Labels: ready-for-review, tiny

#7871 Add sign requests instructions for ADFS SAML
  articles/protocols/saml/adfs.md
Labels: ready-for-review, small

#7876 Angular Quickstart: Update download instructions
  articles/quickstart/spa/angular2/download.md
Labels: quickstart

#7846 AngularJS Quickstart: Update download instructions
  articles/quickstart/spa/angularjs/01-login.md
  articles/quickstart/spa/angularjs/download.md
Labels: quickstart

#7847 Vue JS Quickstart: Add returnTo URL
  articles/quickstart/spa/vuejs/01-login.md
Labels: quickstart

#7787 Chrome Extension Quickstart: Logout from Auth0 authorization server
  articles/quickstart/native/chrome/01-login.md
  articles/quickstart/native/chrome/download.md
Labels: quickstart

#7735 Windows Universal App Quickstart: Add logout handling
  articles/quickstart/native/windows-uwp-csharp/01-login.md
  articles/quickstart/native/windows-uwp-csharp/download.md
  articles/quickstart/native/windows-uwp-csharp/index.yml
  snippets/native-platforms/windows-uwp-csharp/setup.md
Labels: quickstart

#7741 WinForms/WPF Quickstart: Add logout handling
  articles/quickstart/native/wpf-winforms/01-login.md
  articles/quickstart/native/wpf-winforms/download.md
  snippets/native-platforms/wpf-winforms/setup.md
Labels: quickstart

#7788 Xamarin Quickstart: Add logout handling
  articles/quickstart/native/xamarin/01-login.md
  articles/quickstart/native/xamarin/download.md
  articles/quickstart/native/xamarin/index.yml
Labels: quickstart

#7881 Fixed an issue with string literal expansion in WPF QS
  articles/quickstart/native/wpf-winforms/01-login.md
Labels: quickstart, tiny

#7873 Minor changes to Laravel Login quickstart
  articles/quickstart/webapp/laravel/01-login.md
Labels: small

#7882 Fixed incorrect use of tenant vs namespace across the SPA quickstarts
  articles/quickstart/spa/_includes/_calling_api_create_backend.md
  articles/quickstart/spa/_includes/_calling_api_modify_backend.md
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/02-calling-an-api.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/03-calling-an-api.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart, tiny
