Repository auth0/docs, pull requests merged in 2019-11, with the labels that each got.

#8441 Update Java EE Quickstart article for RS256
  articles/quickstart/webapp/java-ee/_includes/_login.md
  articles/quickstart/webapp/java-ee/_includes/_setup.md
Labels: quickstart, small

#8450 Added detail to the iOS instructions around Auth0.plist
  articles/quickstart/native/_includes/_ios_config.md
  articles/quickstart/native/ios-objc/_includes/_config.md
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_config.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
Labels: quickstart, tiny

#8458 Remove "/callback" from the Getting Started include settings in Angul…
  articles/quickstart/spa/angular2/01-login.md
Labels: quickstart, tiny

#8455 Added link to AWS Lambda Developer Guide
  articles/integrations/aws-api-gateway/custom-authorizers/_aws-dev-guide-link.md
  articles/integrations/aws-api-gateway/custom-authorizers/index.md
  articles/integrations/aws-api-gateway/custom-authorizers/part-4.md
Labels: ready-for-review, tiny

#8457 Add note pointing out auth0.js handles nonce and state params
  articles/api-auth/tutorials/nonce.md
Labels: ready-for-review, tiny

#8461 Remove reference to webtasks
  articles/hooks/index.md
Labels: ready-for-review, tiny

#8462 Update warning messages to discuss private cloud
  articles/users/search/v2/index.md
  articles/users/search/v3/index.md
Labels: ready-for-review, tiny

#8443 Update Servlet Quickstart for RS256
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_setup.md
Labels: quickstart, small

#8213 Updates to Password Change doc
  articles/connections/database/password-change.md
  media/articles/connections/database/manual-password-reset.png
  media/articles/connections/database/password-reset-email.png
Labels: ready-for-review, small

#8452 Add info on JWT policies
  articles/integrations/azure-api-management/configure-azure.md
Labels: ready-for-review, small

#8464 Update Custom Email Providers for Sparkpost EU Release
  articles/email/providers.md
  media/articles/dashboard/emails/providers/emails-providers-list.png
  media/articles/dashboard/emails/providers/emails-providers-settings-sparkpost.png
Labels: ready-for-review, small

#8465 Scala Web App update logout [QS-102]
  articles/quickstart/webapp/scala/01-login.md
  articles/quickstart/webapp/scala/download.md
Labels: quickstart

#8426 Update SIWA quickstart
  articles/quickstart/native/ios-swift-siwa/_includes/_login_centralized.md
Labels: quickstart, tiny

#8472 Minor changes to clarify a few steps
  articles/identity-labs/01-web-sign-in/exercise-01.md
  articles/identity-labs/01-web-sign-in/exercise-02.md
  articles/identity-labs/02-calling-an-api/exercise-01.md
  articles/identity-labs/02-calling-an-api/exercise-02.md
  articles/identity-labs/02-calling-an-api/exercise-03.md
Labels: small

#8468 Go Web App update dependecy installation [QS-292]
  articles/quickstart/backend/golang/01-authorization.md
Labels: quickstart

#8471 Update Chrome Extension Quickstart
  articles/quickstart/native/chrome/01-login.md
Labels: quickstart

#8476 Fixed callback URLs in download for Angular2, Vue
  articles/quickstart/spa/angular2/download.md
  articles/quickstart/spa/vuejs/download.md
Labels: quickstart

#8431 Use Access Token to link and unlink user accounts [QS-289]
  articles/quickstart/native/ios-objc/07-linking-accounts.md
Labels: [Goalie] Review Required, quickstart, tiny

#8453 Update the login overview doc for clarity
  articles/login/index.md
Labels: medium, ready-for-review

#8483 Change definition for locale
  articles/users/normalized/oidc/index.md
Labels: ready-for-review, small

#8486 Fix stray http callbacks in quickstarts section
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
  articles/quickstart/webapp/symfony/01-login.md
Labels: ready-for-review, tiny

#8484 Incorporate feedback from customer
  articles/architecture-scenarios/mobile-api/part-2.md
  articles/architecture-scenarios/spa-api/part-2.md
  articles/rules/references/user-object.md
Labels: ready-for-review, small

#8488 Remove on-prem references
  articles/appliance/monitoring/index.md
Labels: ready-for-review, small

#8490 Fix typo
  articles/api-auth/tutorials/password-grant.md
Labels: ready-for-review, small

#8432 SPA Quickstart Typos fixes, Grammar Suggestions and Paths Corrections
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  articles/quickstart/webapp/aspnet-core-v1_1/03-authorization.md
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_login.md
  articles/quickstart/webapp/aspnet-core/02-user-profile.md
  articles/quickstart/webapp/aspnet-core/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/02-user-profile.md
  articles/quickstart/webapp/aspnet-owin/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
  articles/quickstart/webapp/aspnet-owin/_includes/_setup.md
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/golang/01-login.md
  articles/quickstart/webapp/java-ee/_includes/_login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/nodejs/01-login.md
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart

#8263 Update error messages
  articles/api/authentication/errors/_errors.md
Labels: ready-for-review, small

#8494 Expand details on data residency
  articles/private-cloud/index.md
Labels: ready-for-review, small

#8429 Create Azure CDN and Cloudflare as proxies for custom domains tutorials
  articles/custom-domains/self-managed-certificates.md
  articles/custom-domains/set-up-azure-cdn.md
  articles/custom-domains/set-up-cloudflare.md
Labels: medium, ready-for-review

#8482 Launch Preparation - Replacement PR
  articles/architecture-scenarios/_includes/_branding/_custom-domain-naming.md
  articles/architecture-scenarios/_includes/_launch/_compliance.md
  articles/architecture-scenarios/_includes/_launch/_introduction.md
  articles/architecture-scenarios/_includes/_launch/_launch.md
  articles/architecture-scenarios/_includes/_launch/_operations.md
  articles/architecture-scenarios/_includes/_launch/_support.md
  articles/architecture-scenarios/_includes/_launch/_tenant-check.md
  articles/architecture-scenarios/_includes/_launch/_testing.md
  articles/architecture-scenarios/_includes/_qa/_load-testing.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-compliance.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-launch.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-operations.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-support.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-tenantcheck.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch/b2c-launch-testing.md
  articles/architecture-scenarios/index.md
  config/sidebar.yml
Labels: large, ready-for-review

#8151 Use react router history.push
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, small

#8480 Update Ionic 3 quickstart [QS-383]
  articles/quickstart/native/ionic3/01-login.md
  articles/quickstart/native/ionic3/download.md
  articles/quickstart/native/ionic3/index.yml
Labels: quickstart

#6924 Extra info about mapping a claim to `User.Identity.Name`
  articles/quickstart/backend/aspnet-core-webapi/01-authorization.md
Labels: quickstart

#8397 Add info re: current_user scope rate limits
  articles/api/management/v2/get-access-tokens-for-spas.md
  articles/policies/rate-limits.md
Labels: do-not-merge, small

#8492 Custom Domain content updates
  articles/cms/wordpress/configuration.md
  articles/connections/enterprise/adfs.md
  articles/connections/passwordless/guides/implement-passwordless.md
  articles/connections/passwordless/index.md
  articles/custom-domains/_additional-steps.md
  articles/custom-domains/_provide-domain-name.md
  articles/custom-domains/_subscription.md
  articles/custom-domains/_warning-repeat-steps.md
  articles/custom-domains/additional-configuration.md
  articles/custom-domains/auth0-managed-certificates.md
  articles/custom-domains/index.md
  articles/custom-domains/self-managed-certificates.md
  articles/custom-domains/set-up-azure-cdn.md
  articles/custom-domains/set-up-cloudflare.md
  articles/custom-domains/set-up-cloudfront.md
  articles/custom-domains/troubleshoot.md
  articles/guides/login/universal-vs-embedded.md
  config/sidebar.yml
Labels: medium, ready-for-review

#8508 EventBridge integration doc
  articles/integrations/aws-eventbridge.md
Labels: do-not-merge, medium

#8503 Create cookie-attributes.md
  articles/_includes/_samesite_none.md
  articles/cross-origin-authentication/index.md
  articles/design/web-apps-vs-web-apis-cookies-vs-tokens.md
  articles/sessions/concepts/cookie-attributes.md
  articles/sessions/concepts/cookies.md
  articles/sessions/concepts/session-layers.md
  articles/sessions/concepts/session-lifetime.md
  articles/sessions/index.md
  articles/sessions/references/example-short-lived-session-mgmt.md
  articles/sessions/references/sample-use-cases-sessions.md
  articles/users/index.md
  config/sidebar.yml
  media/articles/sessions/cookie-fresh-interaction.png
  media/articles/sessions/cookie-return-interaction.png
Labels: ready-for-review, small

#8515 Fixed Swift Quickstart issues
  articles/quickstart/native/_includes/_ios_dependency_centralized.md
  articles/quickstart/native/ios-swift/03-user-sessions.md
  articles/quickstart/native/ios-swift/04-calling-apis.md
  articles/quickstart/native/ios-swift/05-authorization.md
  articles/quickstart/native/ios-swift/07-linking-accounts.md
  articles/quickstart/native/ios-swift/08-touch-id-authentication.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_product_bundle_note.md
Labels: medium

#8517 Fix typos in update cookie-attributes.md
  articles/_includes/_samesite_none.md
  articles/sessions/concepts/cookie-attributes.md
Labels: ready-for-review, tiny

#8511 Combine AD and LDAP enterprise connection guides
  articles/api-auth/tutorials/password-grant.md
  articles/architecture-scenarios/b2b-b2e.md
  articles/architecture-scenarios/web-app-sso/part-2.md
  articles/connections/enterprise/active-directory-ldap.md
  articles/connections/enterprise/ldap.md
  articles/connector/overview.md
  articles/connector/test-dc.md
  config/redirects.js
Labels: ready-for-review, small

#8516 Rules use cases
  articles/rules/index.md
  articles/rules/references/use-cases.md
  config/sidebar.yml
Labels: medium, ready-for-review

#8520 Update cookie-attributes.md
  articles/sessions/concepts/cookie-attributes.md
Labels: ready-for-review, tiny

#8481 Add AWS session tags doc
  articles/dashboard/guides/applications/set-up-addon-saml2-aws.md
  articles/integrations/aws/index.md
  articles/integrations/aws/session-tags.md
Labels: do-not-merge

#8518 Updated rules objects content
  articles/rules/_includes/_user-prop-identities.md
  articles/rules/index.md
  articles/rules/references/context-object.md
  articles/rules/references/legacy.md
  articles/rules/references/user-object.md
Labels: ready-for-review, tiny

#8512 Reorganize DAE docs; add corrections
  articles/authorization/concepts/sample-use-cases-rules.md
  articles/dashboard/guides/applications/update-app-connections.md
  articles/dashboard/guides/connections/set-up-connections-database.md
  articles/dashboard/guides/connections/test-connections-database.md
  articles/dashboard/guides/extensions/delegated-admin-create-app.md
  articles/dashboard/guides/extensions/delegated-admin-install-extension.md
  articles/dashboard/guides/extensions/delegated-admin-use-extension.md
  articles/dashboard/guides/extensions/sso-dashboard-create-app.md
  articles/dashboard/guides/users/create-users.md
  articles/extensions/delegated-admin/v3/index.md
Labels: medium, ready-for-review

#8522 [SDK-735] Reworded include to remove reference to access tokens in cookies
  articles/quickstart/spa/_includes/_calling_api_access_token.md
Labels: quickstart, tiny

#8507 Update Django API quickstart [QS-392]
  articles/quickstart/backend/django/01-authorization.md
  articles/quickstart/backend/django/index.yml
Labels: quickstart

#8526 Remove ASP.NET Core 1.1 - deprecated
  articles/quickstart/backend/aspnet-core-webapi-v1_1/01-authorization.md
  articles/quickstart/backend/aspnet-core-webapi-v1_1/02-using.md
  articles/quickstart/backend/aspnet-core-webapi-v1_1/03-troubleshooting.md
  articles/quickstart/backend/aspnet-core-webapi-v1_1/download.md
  articles/quickstart/backend/aspnet-core-webapi-v1_1/index.yml
Labels: quickstart

#8519 Update b2c.md - added Launch Preparation to index
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/implementation/b2c/b2c-launch.md
  config/sidebar.yml
Labels: ready-for-review, tiny

#8527 Passwordless doc - Fixed broken link
  articles/connections/passwordless/guides/implement-passwordless.md
Labels: ready-for-review, tiny

#8530 Fix Swift Quickstart issues
  articles/quickstart/native/ios-swift/03-user-sessions.md
  articles/quickstart/native/ios-swift/05-authorization.md
  articles/quickstart/native/ios-swift/08-touch-id-authentication.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
Labels: quickstart, small

#8528 Added warning to ROPG docs
  articles/api-auth/_includes/_ropg-warning.md
  articles/api-auth/grant/password.md
  articles/api-auth/tutorials/password-grant.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
Labels: ready-for-review, small

#8463 rememberLastLogin isn't applicable if you have Seamless SSO enabled
  articles/libraries/lock/v11/configuration.md
Labels: tiny, update-needed

#8529 Fix Objective C Quickstart issues [QS-411]
  articles/quickstart/native/ios-objc/03-user-sessions.md
  articles/quickstart/native/ios-objc/04-calling-apis.md
  articles/quickstart/native/ios-objc/05-authorization.md
  articles/quickstart/native/ios-objc/07-linking-accounts.md
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
Labels: medium, quickstart

#8534 add import part to Getting Started part for auth0-spa-js
  articles/libraries/auth0-spa-js/index.md
Labels: tiny
