Repository auth0/docs, pull requests merged in 2019-03, with the labels that each got.

#7308 Pen testing updates
  articles/policies/penetration-testing.md
Labels: ready-for-review

#7320 Add warning, edits to Managing Tenant Admins page
  articles/dashboard/manage-dashboard-admins.md
Labels: ready-for-review

#7331 Private Cloud Overview
  articles/appliance/overview.md
Labels: ready-for-review

#7329 Fix typo
  articles/appliance/monitoring/index.md
Labels: ready-for-review

#7328 Minor text changes, code sample fix and link fix
  articles/authorization/concepts/authz-rules.md
  articles/authorization/concepts/rbac.md
  articles/authorization/concepts/sample-use-cases-rules.md
  articles/authorization/guides/api/edit-role-definitions.md
Labels: ready-for-review

#7333 Authz fix
  articles/authorization/guides/dashboard/add-permissions-apis.md
  articles/authorization/guides/dashboard/delete-permissions-apis.md
Labels: ready-for-review

#7340 Add device auth option param
  articles/libraries/lock/v11/sending-authentication-parameters.md
Labels: ready-for-review

#7327 Replace rules supported modules with link to auth0-extensions "Can I Require"
  articles/rules/_includes/_supported-modules.md
  articles/rules/index.md
  articles/rules/references/modules.md
Labels: ready-for-review

#7342 Clarify blurb on client secret for mobile/native apps
  articles/flows/concepts/mobile-login-flow.md
Labels: ready-for-review

#7335 Update token storage doc
  articles/security/store-tokens.md
Labels: ready-for-review

#7322 Updating README with a couple of clarifications about where things live
  README.md
Labels: ready-for-review

#7348 Update Authz core number of roles per user
  articles/authorization/concepts/core-vs-extension.md
Labels: ready-for-review

#7347 Clarify steps involved in entering MFA passcode
  articles/multifactor-authentication/index.md
  articles/multifactor-authentication/troubleshooting.md
Labels: ready-for-review

#7350 Remove comma
  articles/tokens/set-access-token-lifetime.md
Labels: ready-for-review

#7337 webtask.io reference removed from hooks docs
  articles/hooks/index.md
Labels: update-needed

#7356 Remove ref to Demand Service
  articles/support/index.md
Labels: do-not-merge

#7358 Add caveat re: tenant display information
  articles/universal-login/error-pages.md
Labels: ready-for-review

#7360 Add links to libraries
  articles/users/guides/redirect-users-after-login.md
Labels: ready-for-review

#7368 Added connection parameters to API flows
  articles/api/authentication/api-authz/_authz-client.md
Labels: ready-for-review

#7369 Update common-threats.md
  articles/security/common-threats.md
Labels: ready-for-review

#7287 Update sms-gateway.md
  articles/connections/passwordless/sms-gateway.md
Labels: update-needed

#7355 Updates to Google social connection guide
  articles/connections/_call-api.md
  articles/connections/_find-auth0-domain-redirects.md
  articles/connections/guides/set-up-connections-social.md
  articles/connections/guides/test-connections-social.md
  articles/connections/social/google.md
  media/articles/connections/social/connection-social-applications.png
  media/articles/connections/social/connection-social-list-configured.png
  media/articles/connections/social/connection-social-list-unconfigured.png
  media/articles/connections/social/connection-social-settings.png
  media/articles/connections/social/connection-social-try-choose-account.png
  media/articles/connections/social/connection-social-try-success.png
Labels: ready-for-review

#7354 Update billing.md
  articles/policies/billing.md
Labels: do-not-merge

#7377 Add information on customizing Lock in wp-auth0
  articles/cms/wordpress/troubleshoot.md
Labels: ready-for-review

#7362 [ULP-709] Microsoft Account Migration
  articles/migrations/guides/liveid-api-deprecation.md
  media/articles/connections/social/microsoft-account/microsoft-account-azureid.png
Labels: do-not-merge

#7387 QS-61: Added 'api' to 'sample_download_required_data'
  articles/quickstart/spa/vuejs/03-calling-an-api.md
Labels: quickstart

#7388 Fix issue with Github source path in VueJS QS
  articles/quickstart/spa/vuejs/03-calling-an-api.md
Labels: quickstart

#7382 Update Shopify connection doc
  articles/connections/social/shopify.md
  media/articles/connections/social/shopify/shopify-devportal-1.png
  media/articles/connections/social/shopify/shopify-devportal-2.png
  media/articles/connections/social/shopify/shopify-devportal-3.png
  media/articles/connections/social/shopify/shopify-devportal-4.png
  media/articles/connections/social/shopify/shopify-devportal-5.png
  media/articles/connections/social/shopify/shopify-devportal-6.png
  media/articles/connections/social/shopify/shopify-devportal-7.png
  media/articles/connections/social/shopify/shopify-devportal-8.png
  media/articles/connections/social/shopify/shopify-devportal-9.png
Labels: ready-for-review

#7389 Change title for Angular QS
  articles/quickstart/spa/angular2/index.yml
Labels: quickstart

#7371 Update Facebook social connection guide
  articles/connections/guides/create-multiple-tenants.md
  articles/connections/guides/test-connections-social.md
  articles/connections/social/facebook.md
  media/articles/connections/dashboard-create-tenant.png
  media/articles/connections/tenant-create.png
Labels: ready-for-review

#7392 Remove scenarios under construction
  articles/architecture-scenarios/index.md
Labels: ready-for-review

#7393 Fixed broken links
  articles/applications/concepts/add-ons.md
  articles/authorization/guides/dashboard/add-permissions-apis.md
  articles/connections/database/password-strength.md
Labels: ready-for-review

#7394 Added new delegated admin role
  articles/extensions/delegated-admin/v3/index.md
Labels: ready-for-review

#7396 Updates to Shopify connection guide to match formatting and language of other guides
  articles/connections/social/shopify.md
Labels: ready-for-review

#7395 Updates to Google connection doc to match formatting of other guides
  articles/connections/_call-api.md
  articles/connections/social/google.md
Labels: ready-for-review

#7397 Update LinkedIn social connection guide
  articles/connections/social/linkedin.md
Labels: ready-for-review

#7398 Removed AOL references
  articles/connections/social/aol.md
  articles/logout/guides/logout-idps.md
Labels: ready-for-review

#7399 Update Microsoft connection guide
  articles/connections/social/microsoft-account.md
Labels: ready-for-review

#7379 Add user migration guide
  articles/cms/wordpress/how-does-it-work.md
  articles/cms/wordpress/installation.md
  articles/cms/wordpress/troubleshoot.md
  articles/cms/wordpress/user-migration.md
  media/articles/cms/wordpress/auth0-incoming-ip-addresses.png
  media/articles/cms/wordpress/fingerprint_logo.png
  media/articles/cms/wordpress/migration-ip-whitelist-setting-field.png
Labels: ready-for-review

#7400 Weibo
  articles/connections/social/weibo.md
  media/articles/connections/social/weibo/click-advanced.png
  media/articles/connections/social/weibo/click-basic.png
  media/articles/connections/social/weibo/confirmation.png
  media/articles/connections/social/weibo/create-app.png
  media/articles/connections/social/weibo/development-page.png
  media/articles/connections/social/weibo/enable-clients.png
  media/articles/connections/social/weibo/enter-callback.png
  media/articles/connections/social/weibo/enter-keys.png
  media/articles/connections/social/weibo/get-app-key-secret.png
  media/articles/connections/social/weibo/select-web-app.png
  media/articles/connections/social/weibo/try-connection.png
Labels: ready-for-review

#7386 Added rate limits for Authentication API for enterprise tenants
  articles/policies/rate-limits.md
Labels: ready-for-review

#7406 Check access control rules impact on password grant
  articles/api-auth/tutorials/password-grant.md
Labels: ready-for-review

#7376 Add Facebook API changes notification
  articles/migrations/guides/facebook-graph-api-deprecation.md
  articles/migrations/index.md
  media/articles/connections/social/facebook/facebook-connection-permissions.png
Labels: ready-for-review

#7418 Add rate limits line to load test policy
  articles/policies/load-testing.md
Labels: ready-for-review

#7318 Fixed incorrect reference to authConfig in VueJS Quickstart sample 03
  articles/quickstart/spa/vuejs/03-calling-an-api.md
Labels: quickstart

#7423 Update validate scopes rule example
  articles/architecture-scenarios/spa-api/part-2.md
Labels: ready-for-review

#7416 AngularJS Quickstart: Logout from Auth0 authorization server
  articles/quickstart/spa/angularjs/01-login.md
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
Labels: quickstart

#7408 Angular 2 Quickstart: Logout from Auth0 authorization server
  articles/quickstart/spa/angular2/01-login.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart
