Repository auth0/docs, pull requests merged in 2019-12, with the labels that each got.

#8538 Fixing API and SPA documentation issues
  articles/quickstart/backend/_includes/_api_create_new.md
  articles/quickstart/backend/_includes/_api_create_new_2.md
  articles/quickstart/backend/_includes/_api_troubleshooting.md
  articles/quickstart/backend/_includes/_api_using.md
  articles/quickstart/backend/django/01-authorization.md
  articles/quickstart/backend/falcor/01-authorization.md
  articles/quickstart/backend/golang/01-authorization.md
  articles/quickstart/backend/hapi/01-authorization.md
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/java-spring-security/download.md
  articles/quickstart/backend/java-spring-security5/01-authorization.md
  articles/quickstart/backend/java-spring-security5/download.md
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/backend/laravel/download.md
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/backend/symfony/01-authorization.md
  articles/quickstart/backend/webapi-owin/01-authorization.md
  articles/quickstart/backend/webapi-owin/03-troubleshooting.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
  articles/quickstart/webapp/nancyfx/01-login.md
  articles/quickstart/webapp/nancyfx/download.md
Labels: medium, quickstart

#8537 Fix SIWA iOS Quickstart issues [QS-413]
  articles/quickstart/native/ios-swift-siwa/_includes/_login_centralized.md
Labels: quickstart, small

#8531 Added includes notes to extensions
  articles/extensions/_includes/_deployment-extension.md
  articles/extensions/_includes/_embedded-clients-array.md
  articles/extensions/bitbucket-deploy.md
  articles/extensions/github-deploy.md
  articles/extensions/gitlab-deploy.md
  articles/extensions/visual-studio-team-services-deploy.md
Labels: ready-for-review, small

#8539 Angular QS - fix file paths
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: tiny

#8540 Angular QS - fix Calling API file paths
  articles/quickstart/spa/angular2/02-calling-an-api.md
Labels: tiny

#8541 Add redirect for MFA troubleshooting
  config/redirects.js
Labels: ready-for-review, tiny

#8445 Add custom database connections best practices
  articles/best-practices/application-settings.md
  articles/best-practices/connection-settings.md
  articles/best-practices/custom-db-connections-scripts.md
  articles/best-practices/custom-db-connections/anatomy.md
  articles/best-practices/custom-db-connections/environment.md
  articles/best-practices/custom-db-connections/execution.md
  articles/best-practices/custom-db-connections/index.md
  articles/best-practices/custom-db-connections/security.md
  articles/best-practices/custom-db-connections/size.md
  articles/best-practices/debugging.md
  articles/best-practices/deployment.md
  articles/best-practices/error-handling.md
  articles/best-practices/index.md
  articles/best-practices/operations.md
  articles/best-practices/performance.md
  articles/best-practices/rules.md
  articles/best-practices/search-best-practices.md
  articles/best-practices/tenant-settings.md
  articles/best-practices/testing.md
  articles/best-practices/user-data-storage-best-practices.md
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/index.md
  articles/connections/database/custom-db/templates/index.md
  articles/users/concepts/overview-user-metadata.md
  config/sidebar.yml
Labels: large, ready-for-review

#8536 Add ASP.NET Core 3 Quickstart
  articles/quickstart/webapp/aspnet-core-3/01-login.md
  articles/quickstart/webapp/aspnet-core-3/02-user-profile.md
  articles/quickstart/webapp/aspnet-core-3/03-authorization.md
  articles/quickstart/webapp/aspnet-core-3/_includes/_login.md
  articles/quickstart/webapp/aspnet-core-3/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core-3/download.md
  articles/quickstart/webapp/aspnet-core-3/index.yml
Labels: quickstart

#8548 Add redirect for broken link
  config/redirects.js
Labels: ready-for-review, tiny

#8552 Add scope param to first config object.
  articles/quickstart/webapp/php/01-login.md
Labels: quickstart, tiny

#8549 [IPS-881] remove first-time id_token behavior reference for SIWA
  articles/connections/apple-siwa/troubleshooting.md
Labels: tiny

#8547 Add existing pages to the sidebar navigation
  config/sidebar.yml
Labels: ready-for-review, small

#8560 Remove link to non-authoritative source
  articles/cross-origin-authentication/index.md
Labels: ready-for-review, tiny

#8553 Update custom social extensions doc
  articles/extensions/custom-social-extensions.md
  media/articles/extensions/custom-social-connections.png
  media/articles/extensions/installed-custom-social-extension.png
  media/articles/extensions/installed-management-api-webhook-extension.png
  media/articles/extensions/installing-custom-social-connections.png
  media/articles/extensions/new-custom-social-connection.png
Labels: medium, ready-for-review

#8568 Fix formatting of warning in best practices
  articles/best-practices/custom-db-connections/security.md
Labels: ready-for-review, tiny

#8567 Update rules/guides/redirect.md
  articles/rules/guides/redirect.md
Labels: ready-for-review, tiny

#8566 Update Rate Limits doc for clarity
  articles/policies/rate-limits.md
Labels: medium, ready-for-review

#8288 Added identifier first page
  articles/universal-login/identifier-first.md
  articles/universal-login/new-experience-limitations.md
  media/articles/universal-login/idp-domains.png
Labels: ready-for-review, update-needed

#8565 Update 01-authorization.md
  articles/quickstart/backend/aspnet-core-webapi/01-authorization.md
Labels: quickstart

#8577 Added missing space
  articles/_includes/_rbac_vs_extensions.md
Labels: tiny

#8575 Typo fix
  articles/integrations/sso/_template.md
Labels: ready-for-review, tiny

#8578 Create draft of post change password hook
  articles/connections/database/password-change.md
  articles/hooks/concepts/extensibility-points.md
  articles/hooks/guides/post-change-password.md
  articles/hooks/index.md
Labels: medium, ready-for-review

#8581 Added Silent Auth with MFA
  articles/api-auth/tutorials/silent-authentication.md
  articles/multifactor-authentication/custom.md
Labels: ready-for-review, small

#8571 Update rules debug and api guides
  articles/rules/guides/debug.md
  articles/rules/guides/management-api.md
  articles/rules/guides/metadata.md
Labels: medium, ready-for-review

#8573 Updated third-party apps sections
  articles/_includes/_enable-third-party-apps-info.md
  articles/api-auth/apis.md
  articles/api-auth/dynamic-client-registration.md
  articles/api-auth/restrict-access-api.md
  articles/api-auth/tutorials/client-credentials.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
  articles/api-auth/user-consent.md
  articles/api/management/guides/applications/view-ownership.md
  articles/api/management/v2/create-m2m-app.md
  articles/api/management/v2/get-access-tokens-for-production.md
  articles/api/management/v2/get-access-tokens-for-spas.md
  articles/api/management/v2/get-access-tokens-for-test.md
  articles/application-auth/current/mobile-desktop.md
  articles/applications/concepts/app-types-auth0.md
  articles/applications/concepts/app-types-confidential-public.md
  articles/applications/concepts/app-types-first-third-party.md
  articles/applications/concepts/application-grant-types.md
  articles/applications/concepts/multiple-tenants.md
  articles/applications/connections.md
  articles/applications/guides/enable-third-party-apps.md
  articles/applications/index.md
  articles/applications/reference/grant-types-auth0-mapping.md
  articles/architecture-scenarios/_includes/_authorization/_api-integration.md
  articles/best-practices/application-settings.md
  articles/dashboard/guides/applications/register-app-m2m.md
  articles/dashboard/guides/applications/register-app-native.md
  articles/dashboard/guides/applications/register-app-regular-web.md
  articles/dashboard/guides/applications/register-app-spa.md
  articles/dashboard/guides/connections/view-connections.md
  articles/dashboard/guides/tenants/create-multiple-tenants.md
  articles/dashboard/reference/settings-application.md
  articles/dashboard/reference/views-api.md
  articles/design/creating-invite-only-applications.md
  articles/flows/guides/device-auth/includes/troubleshooting.md
  articles/getting-started/set-up-api.md
  articles/integrations/azure-api-management/configure-auth0.md
  articles/libraries/_includes/_embedded_sso.md
  articles/monitoring/guides/monitor-applications.md
  articles/multifactor-authentication/step-up-authentication/step-up-for-apis.md
  articles/multifactor-authentication/step-up-authentication/step-up-for-web-apps.md
  articles/protocols/saml/saml-configuration/troubleshoot/common-saml-errors.md
  articles/protocols/saml/saml-idp-generic.md
  articles/tokens/id-tokens.md
  articles/tokens/jwt-claims.md
  config/redirects.js
  config/sidebar.yml
Labels: large, ready-for-review

#8544 User Metadata updates
  articles/best-practices/index.md
  articles/best-practices/metadata-best-practices.md
  articles/best-practices/user-data-storage-best-practices.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/index.md
  articles/microsites/manage-users/define-maintain-custom-user-data.md
  articles/microsites/manage-users/manage-users-and-user-profiles.md
  articles/rules/guides/metadata.md
  articles/users/_includes/_connection-synch-note.md
  articles/users/concepts/overview-user-metadata.md
  articles/users/concepts/overview-user-profile.md
  articles/users/guides/bulk-user-exports.md
  articles/users/guides/manage-user-metadata.md
  articles/users/guides/read-metadata.md
  articles/users/guides/set-metadata-properties-on-creation.md
  articles/users/guides/update-metadata-properties-with-management-api.md
  articles/users/guides/update-user-profiles-using-your-database.md
  articles/users/index.md
  articles/users/references/bulk-import-database-schema-examples.md
  articles/users/references/metadata-field-name-rules.md
  articles/users/references/user-data-storage-scenario.md
  articles/users/references/user-profile-structure.md
  articles/users/search/v3/query-syntax.md
  config/sidebar.yml
Labels: medium, ready-for-review

#8588 Update post change password hook doc based on feedback
  articles/hooks/guides/post-change-password.md
Labels: ready-for-review, small

#8590 Fixing link to Branding section
  articles/universal-login/new.md
Labels: ready-for-review, tiny

#8535 Fix Android Quickstart issues [QS-412]
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/07-authorization.md
  articles/quickstart/native/android/_includes/_auth0.md
  articles/quickstart/native/android/_includes/_gradle.md
  articles/quickstart/native/android/_includes/_login.md
Labels: large, quickstart

#8595 remove "Use `metadata` with custom database scripts" section
  articles/best-practices/metadata-best-practices.md
Labels: ready-for-review

#8583 Fix panel markup
  articles/best-practices/custom-db-connections/anatomy.md
Labels: ready-for-review, tiny

#8564 [CF-53] Update API1 deprecation docs
  articles/_includes/_version_warning_api.md
  articles/api/management/v1/use-cases.md
  articles/api/management/v2/changes.md
  articles/migrations/guides/management-api-v1-v2.md
  config/redirects.js
  media/articles/migrations/apiv1-log-example.png
  media/articles/migrations/apiv1-log-query.png
  media/articles/migrations/apiv1-toggle.png
Labels: in-review

#8600 Reinstate /oauth/ro errors
  articles/api/authentication/errors/_oauth-ro.md
  articles/api/authentication/index.md
Labels: ready-for-review, small

#8603 Remove password_expiration option from connection options doc
  articles/connections/references/options-mgmt-api.md
Labels: ready-for-review, tiny

#8605 Updated Get Started - The Basics
  articles/getting-started/the-basics.md
Labels: ready-for-review, tiny
