Repository auth0/docs, pull requests merged in 2019-08, with the labels that each got.

#8049 Broken link in add-permissions-apis.md
  articles/dashboard/guides/apis/add-permissions-apis.md
Labels: ready-for-review, tiny

#8050 Clarified sentence auth0.js linking users
  articles/libraries/auth0js/v9/index.md
Labels: ready-for-review, tiny

#8052 Update deprecation notices for /delegation endpoint
  articles/_includes/_deprecate-delegation.md
  articles/_includes/_deprecate-impersonation.md
  articles/_includes/_uses-delegation.md
  articles/addons/azure-blob-storage.md
  articles/addons/azure-mobile-services.md
  articles/addons/azure-sb.md
  articles/addons/index.md
  articles/addons/salesforce-sandbox.md
  articles/addons/salesforce.md
  articles/addons/sap-odata.md
  articles/api/authentication/legacy/_delegation.md
  articles/applications/application-settings/_adv-settings.md
  articles/best-practices/application-settings.md
  articles/dashboard/guides/applications/set-up-addons.md
  articles/dashboard/reference/settings-application.md
  articles/integrations/aws-api-gateway/delegation/_delegation-version-warning.md
  articles/integrations/aws/tokens.md
  articles/libraries/lock-android/_includes/_lock-version.md
  articles/libraries/lock-android/v1/delegation-api.md
  articles/libraries/lock-android/v1/refresh-jwt-tokens.md
  articles/libraries/lock-android/v2/refresh-jwt-tokens.md
  articles/libraries/lock-ios/v1/delegation-api.md
  articles/libraries/lock-ios/v1/save-and-refresh-jwt-tokens.md
  articles/libraries/lock-ios/v2/migration.md
  articles/tokens/delegation.md
  articles/tokens/refresh-token/legacy/index.md
Labels: ready-for-review

#8037 Cleaned up adfs files
  articles/connections/enterprise/adfs.md
  articles/protocols/saml/adfs.md
  articles/protocols/saml/index.html
  articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-sp.md
  articles/protocols/saml/saml-configuration/troubleshoot/common-saml-errors.md
  articles/protocols/saml/saml-configuration/troubleshoot/index.md
  media/articles/protocols/saml-adfs/adfs-saml-properties.png
Labels: medium, ready-for-review

#8029 QS-115 | Implement tenant-level logout in iOS-Objective C QS tutorial/sample
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
Labels: do-not-merge, quickstart

#8051 Add missing link to spa sdk page
  articles/libraries/auth0-spa-js/index.md
Labels: ready-for-review, tiny

#8055 Fix redirect_uri typo in code samples
  articles/api-auth/tutorials/authorization-code-grant.md
  articles/api-auth/tutorials/hybrid-flow.md
  articles/application-auth/current/mobile-desktop.md
  articles/application-auth/current/server-side-web.md
  articles/application-auth/legacy/server-side-web.md
  articles/architecture-scenarios/mobile-api/part-3.md
  articles/flows/guides/auth-code-pkce/includes/request-tokens.md
  articles/flows/guides/auth-code/includes/request-tokens.md
Labels: ready-for-review, tiny

#8056 Rename Spring Security API QS to Spring Security 4
  articles/quickstart/backend/java-spring-security/index.yml
Labels: quickstart, tiny

#8058 Fix component filename extension on React QS
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#8059 Fix jwt dependency import on DJANGO QS
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart, tiny

#8054 Copyedits to Libraries index page
  articles/libraries/index.md
Labels: ready-for-review

#8033 update default author on quickstarts
  articles/quickstart/config.yml
Labels: quickstart, tiny

#8066 Add missing "Loading" div on React SPA QS
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#8070 Minor update to get people to the advanced customization page
  articles/universal-login/classic.md
Labels: ready-for-review, small

#8075 Remove angularjs redirect
  config/redirects.js
Labels: tiny

#7994 Update Quickstart authors
  articles/quickstart/backend/aspnet-core-webapi-v1_1/index.yml
  articles/quickstart/backend/aspnet-core-webapi/index.yml
  articles/quickstart/backend/django/index.yml
  articles/quickstart/backend/golang/index.yml
  articles/quickstart/backend/java-spring-security/index.yml
  articles/quickstart/backend/nodejs/index.yml
  articles/quickstart/backend/python/index.yml
  articles/quickstart/backend/rails/index.yml
  articles/quickstart/backend/webapi-owin/index.yml
  articles/quickstart/native/ionic3/index.yml
  articles/quickstart/spa/angularjs/index.yml
  articles/quickstart/webapp/aspnet-core-v1_1/index.yml
  articles/quickstart/webapp/aspnet-core/index.yml
  articles/quickstart/webapp/aspnet-owin/index.yml
  articles/quickstart/webapp/django/index.yml
  articles/quickstart/webapp/golang/index.yml
  articles/quickstart/webapp/java-spring-mvc/index.yml
  articles/quickstart/webapp/java-spring-security-mvc/index.yml
  articles/quickstart/webapp/java/index.yml
  articles/quickstart/webapp/nodejs/index.yml
  articles/quickstart/webapp/python/index.yml
  articles/quickstart/webapp/rails/index.yml
Labels: quickstart

#8071 OIDC connection improvements
  articles/connections/enterprise/oidc.md
  media/articles/connections/enterprise/oidc/oidc-details.png
  media/articles/connections/enterprise/oidc/oidc-small.png
Labels: do-not-merge

#8087 Updated screenshots
  articles/users/guides/configure-automatic-migration.md
  articles/users/references/user-migration-scenarios.md
  media/articles/user-profile/user1.png
  media/articles/user-profile/user4.png
  media/articles/user-profile/user5.png
  media/articles/user-profile/user6.png
  media/articles/users/dashboard.png
  media/articles/users/user-profile.png
  media/articles/users/users-tab.png
Labels: medium, ready-for-review

#8088 Update rate-limits.md
  articles/policies/rate-limits.md
Labels: ready-for-review, tiny

#8077 Fix broken links in sidebar
  config/sidebar.yml
Labels: ready-for-review, tiny

#8076 Format Flows landing page
  articles/flows/index.md
Labels: ready-for-review, small

#8073 Fix token request format and token endpoints in flow docs
  articles/flows/guides/auth-code-pkce/includes/refresh-tokens.md
  articles/flows/guides/auth-code-pkce/includes/request-tokens.md
  articles/flows/guides/auth-code/includes/refresh-tokens.md
  articles/flows/guides/auth-code/includes/request-tokens.md
  articles/flows/guides/client-credentials/includes/request-token.md
  articles/flows/guides/device-auth/includes/refresh-tokens.md
  articles/flows/guides/device-auth/includes/request-device-code.md
  articles/flows/guides/device-auth/includes/request-tokens.md
  articles/flows/guides/implicit/includes/refresh-tokens.md
  articles/flows/guides/implicit/includes/request-tokens.md
  config/sidebar.yml
Labels: ready-for-review

#8061 Custom Database Connection Best Practices
  articles/best-practices/custom-db-connections-scripts.md
  articles/best-practices/index.md
  articles/connections/database/custom-db/_includes/_bp-error-object.md
  articles/connections/database/custom-db/_includes/_panel-bcrypt-hash-encryption.md
  articles/connections/database/custom-db/_includes/_panel-feature-availability.md
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/error-handling.md
  articles/connections/database/custom-db/index.md
  articles/connections/database/custom-db/overview-custom-db-connections.md
  articles/connections/database/custom-db/templates/change-email.md
  articles/connections/database/custom-db/templates/change-password.md
  articles/connections/database/custom-db/templates/create.md
  articles/connections/database/custom-db/templates/delete.md
  articles/connections/database/custom-db/templates/get-user.md
  articles/connections/database/custom-db/templates/index.md
  articles/connections/database/custom-db/templates/login.md
  articles/connections/database/custom-db/templates/verify.md
  articles/connections/database/index.md
  articles/users/concepts/overview-user-migration.md
  config/sidebar.yml
  media/articles/connections/database/custom-database-connections.png
  media/articles/connections/database/custom-database.png
  media/articles/connections/database/database-connections.png
  media/articles/connections/database/db-connections-page.png
  media/articles/connections/database/import-scripts.png
  media/articles/connections/database/import-users.png
  media/articles/connections/database/migrated-users.png
  media/articles/connections/database/mysql/db-connection-configurate.png
  media/articles/connections/database/mysql/db-connection-login-script.png
  media/articles/connections/database/mysql/db-connection-parameters.png
  media/articles/connections/database/mysql/db-connection-try-ok.png
Labels: large, ready-for-review

#8034 Private Cloud Updates
  articles/getting-started/deployment-models.md
  articles/logs/migrate-logs-v2-v3.md
  articles/migrations/guides/extensibility-node8.md
  articles/private-cloud/add-ons.md
  articles/private-cloud/custom-domain-migration.md
  articles/private-cloud/index.md
  articles/private-cloud/managed-private-cloud/index.md
  articles/private-cloud/onboarding/index.md
  articles/private-cloud/onboarding/managed-private-cloud/index.md
  articles/private-cloud/onboarding/managed-private-cloud/infrastructure.md
  articles/private-cloud/onboarding/managed-private-cloud/ip-domain-port-list.md
  articles/private-cloud/onboarding/managed-private-cloud/remote-access-options.md
  articles/private-cloud/onboarding/private-cloud.md
  articles/private-cloud/standard-private-cloud/index.md
  config/redirects.js
  config/sidebar.yml
  media/articles/private-cloud/one-jumphost.png
  media/articles/private-cloud/two-jumphosts.png
Labels: large, ready-for-review

#8020 Added example for progressive profiling using rules
  articles/libraries/custom-signup.md
  articles/rules/guides/redirect.md
  articles/users/concepts/overview-progressive-profiling.md
  articles/users/guides/implement-progressive-profiling.md
  articles/users/index.md
  config/redirects.js
  config/sidebar.yml
  media/articles/rules/birthday.png
  media/articles/rules/core-fields.png
Labels: medium, ready-for-review

#8090 Minor improvements to ID Token index
  articles/tokens/id-token.md
Labels: ready-for-review, small

#8091 Fix link to implicit flow
  articles/protocols/oauth2/index.md
Labels: ready-for-review, tiny

#8081 Link to the spa sdk
  articles/security/store-tokens.md
Labels: ready-for-review, tiny

#8084 Clarify custom domain per tenant faq
  articles/custom-domains/index.md
Labels: ready-for-review, tiny

#8089 Remove line about sms being impossible to breach
  articles/connections/passwordless/faq.md
Labels: ready-for-review, tiny

#8082 Link to anomaly detection ip block endpoint
  articles/connections/database/rate-limits.md
Labels: ready-for-review, small

#8083 Update warning about production rate limits
  articles/dev-lifecycle/setting-up-env.md
Labels: ready-for-review, small

#8093 Update PHP quickstart to explain vendor/autoload
  articles/quickstart/webapp/php/01-login.md
Labels: quickstart, tiny

#8092 Fix typos
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#8097 Add links to OIDC Handbook
  articles/api-auth/tutorials/adoption/single-sign-on.md
  articles/protocols/oidc/identity-providers/okta.md
  articles/protocols/oidc/index.md
  articles/protocols/oidc/openid-connect-discovery.md
  articles/scopes/current/oidc-scopes.md
Labels: ready-for-review, tiny

#8095 Update troubleshooting section
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart, tiny

#8094 Update laravel api qs
  articles/quickstart/backend/_includes/_api_create_new.md
  articles/quickstart/backend/_includes/_api_scopes_access_resources.md
  articles/quickstart/backend/laravel/01-authorization.md
  media/articles/server-apis/configure-permissions.png
  media/articles/server-apis/configure-scopes.png
Labels: medium, quickstart

#8096 Added notes to the Angular QS
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart

#7869 Adding Line connection
  articles/connections/social/line.md
  media/articles/connections/social/line/line_connection.png
  media/connections/line.png
Labels: do-not-merge

#8102 Fix run instructions in download docs
  articles/quickstart/backend/java-spring-security/download.md
Labels: quickstart, tiny

#8100 Update image
  media/articles/connector/install/adldap-connector-setup.png
Labels: ready-for-review, tiny

#8098 Update shopify.md
  articles/connections/social/shopify.md
Labels: ready-for-review, tiny

#8104 Remove Passwordless samples
  articles/connections/passwordless/regular-web-app-email-code.md
  articles/connections/passwordless/regular-web-app-email-link.md
  articles/connections/passwordless/regular-web-app-sms.md
  articles/connections/passwordless/spa-email-code.md
  articles/connections/passwordless/spa-email-link.md
  articles/connections/passwordless/spa-sms.md
  articles/connections/passwordless/spa.md
  articles/dev-centers/java.md
Labels: ready-for-review, small

#8114 Fix spelling errors in Laravel API Quickstart
  articles/quickstart/backend/laravel/01-authorization.md
Labels: quickstart, tiny

#8103 Update index.md
  articles/protocols/oidc/index.md
Labels: ready-for-review, tiny

#8111 removed node8 migration pages - previously pr/8086
  articles/appliance/extensibility-node8.md
  articles/dashboard/dashboard-tenant-settings.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/troubleshoot.md
  articles/migrations/guides/extensibility-node8.md
  articles/product-lifecycle/migrations.md
Labels: ready-for-review, small

#8086 removed node8 migration pages and all found links to those pages
  articles/appliance/extensibility-node8.md
  articles/dashboard/dashboard-tenant-settings.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/troubleshoot.md
  articles/migrations/guides/extensibility-node8.md
  articles/product-lifecycle/migrations.md
Labels: do-not-merge

#8115 Update logo_name from java to spring
  articles/quickstart/webapp/java-spring-mvc/index.yml
  articles/quickstart/webapp/java-spring-security-mvc/index.yml
Labels: quickstart, tiny

#8116 Broken links fixed - script best practices
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/templates/index.md
Labels: ready-for-review, tiny

#8122 fix download instructions Go quickstart
  articles/quickstart/backend/golang/download.md
Labels: quickstart

#8119 Update Go quickstart to use oidc package
  articles/quickstart/webapp/golang/01-login.md
  articles/quickstart/webapp/golang/index.yml
  snippets/server-platforms/golang/dependencies.md
Labels: quickstart

#8124 Update features table
  articles/getting-started/deployment-models.md
Labels: ready-for-review

#8134 Fix claim namespace in article to match sample
  articles/quickstart/webapp/aspnet-core-v1_1/03-authorization.md
  articles/quickstart/webapp/aspnet-core/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/03-authorization.md
Labels: quickstart, small

#8131 Clarify when the user.multifactor array is updated
  articles/rules/references/user-object.md
Labels: ready-for-review, tiny

#8138 Remove on-prem options info
  articles/appliance/appliance-overview.md
Labels: ready-for-review

#8137 Added clarification to Management API Token for SPAs doc
  articles/api/management/v2/get-access-tokens-for-spas.md
Labels: ready-for-review, small

#8140 Fix broken link and add warning to pre-deploy checklist
  articles/pre-deployment/tests/required.md
Labels: ready-for-review, tiny

#8136 Add Lock warning to OIDC connection
  articles/connections/enterprise/oidc.md
Labels: ready-for-review, tiny

#8135 Remove link to missing doc
  articles/connections/enterprise/oidc.md
Labels: ready-for-review, tiny

#8142 Fix typo on VueJS QS snippet
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart, tiny

#8148 Clarify information from secondary identites
  articles/link-accounts/index.md
Labels: update-needed

#8163 Fix Laravel API quickstart to be more clear about the testing applica…
  articles/quickstart/backend/laravel/01-authorization.md
  media/articles/server-apis/authorize-m2m-for-api.png
Labels: quickstart, tiny

#8165 Clarifying opening line
  articles/getting-started/set-up-api.md
Labels: ready-for-review, tiny

#8166 Fix URL construction on Node QS
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart, tiny

#8159 Handle webtask changes
  articles/_includes/_test-this-endpoint.md
  articles/_includes/_webtask.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/best-practices/custom-db-connections-scripts.md
  articles/best-practices/operations.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/connections/calling-an-external-idp-api.md
  articles/connections/database/custom-db/_includes/_panel-feature-availability.md
  articles/connections/database/custom-db/overview-custom-db-connections.md
  articles/connections/database/index.md
  articles/connector/scom-monitoring.md
  articles/dashboard/dashboard-tenant-settings.md
  articles/getting-started/whats-next.md
  articles/hooks/_includes/set-up-webtask-cli.md
  articles/hooks/guides/delete-hooks-using-dashboard.md
  articles/integrations/aws-api-gateway/custom-authorizers/index.md
  articles/integrations/aws-api-gateway/delegation/index.md
  articles/rules/guides/debug.md
  articles/rules/guides/redirect.md
  articles/rules/references/legacy.md
  articles/troubleshoot/basics.md
  config/redirects.js
Labels: medium, ready-for-review

#8167 Add rule to integrate RBAC core and DAE roles
  articles/_includes/_rbac_methods.md
  articles/_includes/_rbac_vs_extensions.md
  articles/authorization/concepts/sample-use-cases-rules.md
  articles/extensions/delegated-admin/v3/index.md
Labels: medium, ready-for-review

#8177 Update index.md
  articles/videos/get-started/index.md
Labels: ready-for-review, tiny

#8178 Typo fix b2c-architecture.md
  articles/architecture-scenarios/implementation/b2c/b2c-architecture.md
Labels: ready-for-review, tiny
