Repository auth0/docs, pull requests merged in 2019-07, with the labels that each got.

#7885 Javascript Quickstart: Update download instructions
  articles/quickstart/spa/vanillajs/download.md
Labels: quickstart

#7884 React Quickstart: Update download instructions and fix callback URL
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/download.md
Labels: quickstart

#7851 New og:image tags for Learn Identity section
  articles/videos/learn-identity/01-introduction-to-identity.md
  articles/videos/learn-identity/02-oidc-and-oauth.md
  articles/videos/learn-identity/03-web-sign-in.md
  articles/videos/learn-identity/04-calling-an-api.md
  articles/videos/learn-identity/05-desktop-and-mobile-apps.md
  articles/videos/learn-identity/06-single-page-apps.md
  articles/videos/learn-identity/index.md
  media/articles/learn-identity/learn-identity-og-image.jpg
Labels: small

#7887 Update 01-login.md
  articles/quickstart/webapp/nodejs/01-login.md
Labels: tiny

#7886 Update android snippets to use latest sdk version
  articles/libraries/auth0-android/configuration.md
  articles/libraries/auth0-android/index.md
  articles/quickstart/native/android/02-custom-login-form.md
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/_includes/_api_authz.md
  articles/quickstart/native/android/_includes/_login.md
Labels: tiny

#7890 Fixed incorrect path for code snippet
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart, tiny

#7892 Remove PSaaS-related Warning Label
  articles/custom-domains/index.md
Labels: ready-for-review, tiny

#7894 Remove link to SDK
  articles/security/store-tokens.md
Labels: ready-for-review, tiny

#7896 Update oidc connection image
  articles/connections/enterprise/oidc.md
Labels: ready-for-review, tiny

#7901 Removed the link to the embedded login sample from the Angular JS quickstart
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
Labels: tiny

#7905 Enhancements to delete tenant policy
  articles/policies/restore-deleted-tenant.md
Labels: ready-for-review

#7738 Update logout-applications.md
  articles/logout/guides/logout-applications.md
Labels: ready-for-review, tiny

#7904 Update PSaaS Overview
  articles/private-saas-deployment/index.md
Labels: ready-for-review, tiny

#7903 Ia test
  articles/authorization/index.md
  articles/branding-customization/index.md
  articles/configure/index.md
  articles/deploy/checklist.md
  articles/deploy/index.md
  articles/extend-integrate/index.md
  articles/getting-started/create-tenant.md
  articles/getting-started/index.md
  articles/getting-started/set-up-api.md
  articles/getting-started/set-up-app/index.md
  articles/login/embedded/index.md
  articles/login/index.md
  articles/protocols/saml/identity-providers/index.md
  config/cards.yml
  config/sidebar.yml
Labels: do-not-merge

#7908 Add updated PDF from legal
  media/articles/services/Auth0-Services-Discovery-Workshop.pdf
Labels: ready-for-review, tiny

#7906 Fixing broken link
  articles/flows/index.md
Labels: ready-for-review, tiny

#7907 Fixing Link
  articles/flows/guides/auth-code/includes/authorize-user-add-login.md
Labels: ready-for-review, tiny

#7913 Fixing another API link
  articles/flows/guides/device-auth/includes/request-device-code.md
Labels: ready-for-review, tiny

#7914 Adding email as a factor to list
  articles/multifactor-authentication/factors/_factors-index
Labels: ready-for-review, tiny

#7915 Clarifying application setting instructions
  articles/flows/guides/device-auth/call-api-device-auth.md
Labels: ready-for-review, tiny

#7917 Fix sidebar navigation 404
  config/sidebar.yml
Labels: ready-for-review

#7919 Fix broken links
  articles/protocols/saml/identity-providers/index.md
  config/sidebar.yml
Labels: do-not-merge

#7921 Updated Tenant Settings
  articles/dashboard/dashboard-tenant-settings.md
  media/articles/tutorials/tenant-settings/device-flow-user-code-format.png
  media/articles/tutorials/tenant-settings/login-logout.png
  media/articles/tutorials/tenant-settings/session-timeout.png
  media/articles/tutorials/tenant-settings/tenant-advanced-extensibility.png
  media/articles/tutorials/tenant-settings/tenant-advanced-migrations.png
  media/articles/tutorials/tenant-settings/tenant-advanced-settings.png
Labels: in-review, small

#7912 Fix view population after login
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart, tiny

#7898 Videos
  articles/videos/get-started/01-architecture-your-tenant.md
  articles/videos/get-started/02-provision-user-stores.md
  articles/videos/get-started/03-provision-import-users.md
  articles/videos/get-started/04_01-authenticate-how-it-works.md
  articles/videos/get-started/04_02-authenticate-spa-example.md
  articles/videos/get-started/05_01-authorize-id-tokens-access-control.md
  articles/videos/get-started/05_02-authorize-get-validate-id-tokens.md
  articles/videos/get-started/06-user-profiles.md
  articles/videos/get-started/07_01-brand-how-it-works.md
  articles/videos/get-started/07_02-brand-signup-login-pages.md
  articles/videos/get-started/08-brand-emails-error-pages.md
  articles/videos/get-started/10-logout.md
  articles/videos/get-started/index.md
  articles/videos/index.md
  config/sections.yml
  config/sidebar.yml
Labels: ready-for-review

#7923 Update Custom DB Script Templates index.md
  articles/connections/database/custom-db/templates/index.md
Labels: ready-for-review, tiny

#7926 Update custom.md
  articles/multifactor-authentication/custom.md
Labels: ready-for-review, tiny

#7927 Update index.md
  articles/extensions/account-link.md
  articles/users/concepts/overview-user-metadata.md
  articles/users/concepts/overview-user-migration.md
  articles/users/index.md
Labels: ready-for-review, small

#7928 Update dashboard-tenant-settings.md
  articles/dashboard/dashboard-tenant-settings.md
Labels: ready-for-review, tiny

#7925 Replaced outdated screenshots
  media/articles/multifactor-authentication/mfa-dashboard-1.png
  media/articles/multifactor-authentication/mfa-dashboard-2.png
Labels: ready-for-review, tiny

#7922 Edit doc (Update Root Attributes for Users) for clarity and ease of navigation
  articles/api/management/guides/users/update-root-attributes-users.md
Labels: small

#7932 I was able to see the rendered component
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#7935 Update cards.yml
  config/cards.yml
Labels: ready-for-review, tiny

#7938 Fixed spelling issue in React quickstart
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#7939 Fix typo on Javascript Login Quickstart
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: tiny

#7940 Change requests policy for public cloud
  articles/getting-started/deployment-models.md
Labels: ready-for-review, tiny

#7933 Update auth0-oidc.md
  articles/connections/social/auth0-oidc.md
Labels: ready-for-review, tiny

#7941 Update dashboard overview
  articles/getting-started/_list-processes.md
  articles/getting-started/dashboard-overview.md
  articles/getting-started/overview.md
  media/articles/getting-started/auth0-dashboard.png
  media/articles/getting-started/client-types.png
  media/articles/getting-started/overview.png
Labels: ready-for-review, small

#7911 Update android quickstarts - Include Logout instructions
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/android/_includes/_auth0.md
  articles/quickstart/native/android/_includes/_lock.md
  articles/quickstart/native/android/_includes/_login.md
Labels: medium, quickstart

#7944 Corrected path for signing-algorithms
  articles/dashboard/reference/settings-api.md
  articles/dashboard/reference/settings-application.md
  config/sidebar.yml
Labels: ready-for-review, tiny

#7930 Added port config to Angular sample
  articles/quickstart/spa/angular2/02-calling-an-api.md
Labels: quickstart

#7947 Added link to the FAQ on various docs
  articles/libraries/_includes/_spa_js_faq.md
  articles/libraries/auth0-spa-js/index.md
  articles/quickstart/spa/_includes/_install_auth0-spa-js.md
Labels: quickstart, tiny

#7948 Updated screenshots
  articles/cms/wordpress/configuration.md
  media/articles/cms/wordpress/app-advanced-settings.png
  media/articles/cms/wordpress/application-listing.png
  media/articles/cms/wordpress/auth0-app-settings.png
  media/articles/cms/wordpress/database-connection-listing.png
  media/articles/cms/wordpress/db-connection-apps.png
  media/articles/cms/wordpress/db-connection-listing.png
  media/articles/cms/wordpress/grant-app-access-to-api.png
Labels: ready-for-review, small

#7949 Authz Core/DAE/Authz Ext updates
  articles/_includes/_rbac_methods.md
  articles/_includes/_rbac_vs_extensions.md
  articles/api/management/guides/roles/add-permissions-roles.md
  articles/authorization/concepts/core-vs-extension.md
  articles/authorization/concepts/rbac.md
  articles/authorization/concepts/sample-use-cases-rules.md
  articles/authorization/concepts/troubleshooting.md
  articles/authorization/guides/how-to.md
  articles/authorization/guides/manage-permissions.md
  articles/authorization/guides/manage-roles.md
  articles/authorization/guides/manage-users.md
  articles/authorization/index.md
  articles/dashboard/guides/roles/add-permissions-roles.md
  articles/extensions/authorization-extension/v2/api-access.md
  articles/extensions/authorization-extension/v2/implementation/configuration.md
  articles/extensions/authorization-extension/v2/implementation/installation.md
  articles/extensions/authorization-extension/v2/implementation/setup.md
  articles/extensions/authorization-extension/v2/import-export-data.md
  articles/extensions/authorization-extension/v2/index.md
  articles/extensions/authorization-extension/v2/migration.md
  articles/extensions/authorization-extension/v2/rules.md
  articles/extensions/authorization-extension/v2/troubleshooting.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/index.md
Labels: ready-for-review

#7950 Log warnings
  articles/extensions/realtime-webtask-logs.md
Labels: ready-for-review, small

#7953 Update Which OAuth 2.0 flow should I use?
  articles/api-auth/which-oauth-flow-to-use.md
Labels: ready-for-review

#7955 Cordova Quickstart: Logout from Auth0 authorization server
  articles/quickstart/native/cordova/01-login.md
  articles/quickstart/native/cordova/download.md
  articles/quickstart/native/cordova/index.yml
  snippets/native-platforms/cordova/use.md
Labels: quickstart

#7954 Update Android Custom Fields with Root level profile attributes
  articles/libraries/lock-android/v2/configuration.md
  articles/libraries/lock-android/v2/custom-fields.md
Labels: ready-for-review, small

#7959 Update React Native Quickstart dependencies
  articles/quickstart/native/react-native/index.yml
Labels: quickstart

#7900 Gradle include file for adding the Android dependency
  articles/libraries/auth0-android/index.md
  articles/libraries/auth0-android/save-and-refresh-tokens.md
  articles/quickstart/native/android/_includes/_api_authz.md
  articles/quickstart/native/android/_includes/_auth0.md
  articles/quickstart/native/android/_includes/_gradle.md
  updates/2019-07-01.yml
Labels: large, quickstart

#7604 [IUM-468] update documentations for username validation
  articles/connections/database/require-username.md
Labels: ready-for-review

#7863 Create new Rules Best Practice guidance
  articles/best-practices/rules.md
  media/articles/rules/rules-best-practice-dashboard.png
  media/articles/rules/rules-best-practice-pipeline.png
Labels: large, ready-for-review

#7958 Add paid feature warning for custom domain
  articles/custom-domains/set-up-cloudfront.md
Labels: ready-for-review, tiny

#7943 Update the-basics.md
  articles/dashboard/guides/applications/register-app-m2m.md
  articles/getting-started/the-basics.md
Labels: ready-for-review, small

#7966 Fix typo on ionic QS
  articles/quickstart/native/ionic3/01-login.md
Labels: quickstart, tiny

#7737 PSaaS Onboarding
  articles/private-saas-deployment/index.md
  articles/private-saas-deployment/infra.md
  articles/private-saas-deployment/onboarding/index.md
  articles/private-saas-deployment/onboarding/managed-private-cloud.md
  articles/private-saas-deployment/onboarding/private-cloud.md
Labels: large, ready-for-review

#7971 Add X509 to instrumentation
  articles/appliance/instrumentation.md
Labels: ready-for-review, tiny

#7969 Delete infra.md
  articles/private-saas-deployment/infra.md
Labels: ready-for-review, tiny

#7979 Change passwordlessVerify to passwordlessLink in code samples
  articles/connections/passwordless/regular-web-app-email-code.md
  articles/connections/passwordless/regular-web-app-sms.md
  articles/connections/passwordless/spa-email-code.md
Labels: ready-for-review, tiny

#7978 Changed wording per Jose and Mauricio
  articles/policies/load-testing.md
Labels: ready-for-review, tiny

#7976 Fix typos
  articles/appliance/monitoring/authenticated-endpoints.md
Labels: ready-for-review, tiny

#7962 Clarify root attributes
  articles/_includes/_users_update_normalized_profile_attributes.md
  articles/users/normalized/auth0/update-root-attributes.md
  articles/users/references/user-profile-structure.md
Labels: ready-for-review, small

#7984 Update root profile endpoint reference link
  articles/libraries/lock-android/v2/custom-fields.md
Labels: tiny

#7985 Corrected payload description
  articles/tokens/guides/id-token/validate-id-token.md
Labels: ready-for-review, tiny

#7986 Add info about tenant-level settings affecting login_required error.
  articles/api-auth/tutorials/silent-authentication.md
Labels: ready-for-review, tiny

#7987 Fix typos
  articles/dashboard/guides/applications/enable-sso-app.md
  articles/protocols/saml/saml-apps/index.md
Labels: ready-for-review, tiny

#7989 Add prefix and backslash to Django QS issuer template
  articles/quickstart/backend/django/01-authorization.md
Labels: tiny

#7982 Add screenshot to Get Started video course
  articles/videos/get-started/index.md
  media/articles/videos/get-started/get-started.png
Labels: ready-for-review, tiny

#7990 Patch ionic3 QS
  articles/quickstart/native/ionic3/01-login.md
Labels: small

#7963 Wrap certificate at 64 chars to avoid ValueError from cryptography module
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart

#7956 Add missing python endpoint to the quickstart
  snippets/server-apis/python/use.md
Labels: quickstart, small

#7897 React Native Quickstart: Add logout and update download instructions
  articles/quickstart/native/react-native/00-login.md
  articles/quickstart/native/react-native/download.md
Labels: quickstart

#7999 CSAT: Password Reset Page
  articles/universal-login/password-reset.md
  media/articles/universal-login/password-reset.png
Labels: large, ready-for-review

#8002 Vanilla SPA QS: Use /api/external to match other articles
  articles/quickstart/spa/vanillajs/02-calling-an-api.md
Labels: tiny

#8001 Remove user attributes not available in rules
  articles/rules/references/user-object.md
Labels: ready-for-review, small

#7988 PSaaS Navigation
  articles/private-saas-deployment/custom-domain-migration.md
  articles/private-saas-deployment/index.md
  config/sidebar.yml
Labels: ready-for-review, small

#7992 Add image metadata
  articles/videos/get-started/index.md
Labels: ready-for-review

#7997 Clarify logout behavior
  articles/logout/guides/logout-auth0.md
Labels: ready-for-review, small

#8000 Fix URL typo
  articles/api/management/guides/roles/view-role-users.md
Labels: ready-for-review, tiny

#8006 05_01 description fix
  articles/videos/get-started/05_01-authorize-id-tokens-access-control.md
  articles/videos/get-started/index.md
Labels: ready-for-review, tiny

#8003 Fix endpoints after API2 alias updates
  articles/api/management/guides/roles/add-permissions-roles.md
  articles/api/management/guides/roles/create-roles.md
  articles/api/management/guides/roles/delete-roles.md
  articles/api/management/guides/roles/edit-role-definitions.md
  articles/api/management/guides/roles/remove-role-permissions.md
  articles/api/management/guides/roles/view-role-permissions.md
  articles/api/management/guides/users/assign-permissions-users.md
  articles/api/management/guides/users/assign-roles-users.md
  articles/api/management/guides/users/remove-user-permissions.md
  articles/api/management/guides/users/remove-user-roles.md
  articles/api/management/guides/users/view-user-permissions.md
  articles/api/management/guides/users/view-user-roles.md
  articles/api/management/v2/changes.md
  articles/api/management/v2/get-access-tokens-for-spas.md
  articles/applications/concepts/app-types-first-third-party.md
  articles/link-accounts/index.md
  articles/link-accounts/suggested-linking/index.md
  articles/link-accounts/user-initiated-linking.md
  articles/link-accounts/user-initiated-linking/index.md
  articles/migrations/guides/account-linking.md
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/users/guides/bulk-user-exports.md
  articles/users/search/v2/index.md
  articles/users/search/v3/get-users-by-email-endpoint.md
  articles/users/search/v3/get-users-by-id-endpoint.md
  articles/users/search/v3/get-users-endpoint.md
  articles/users/search/v3/migrate-search-v2-v3.md
  articles/users/search/v3/sort-search-results.md
  articles/users/search/v3/view-search-results-by-page.md
Labels: medium, ready-for-review

#8008 Add search best practices guidelines
  articles/best-practices/search-best-practices.md
Labels: ready-for-review, small

#8007 Update brute-force protection docs
  articles/anomaly-detection/guides/enable-disable-brute-force-protection.md
  media/articles/anomaly-detection/brute-force-shield.png
Labels: ready-for-review, small

#8005 Fix param typo
  articles/api-auth/tutorials/authorization-code-grant-pkce.md
Labels: ready-for-review

#8011 Fix typo on React QS
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: tiny

#7973 Spring 5 API Quickstart article
  articles/quickstart/backend/_includes/_api_create_new.md
  articles/quickstart/backend/_includes/_api_using.md
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/java-spring-security5/01-authorization.md
  articles/quickstart/backend/java-spring-security5/02-using.md
  articles/quickstart/backend/java-spring-security5/03-troubleshooting.md
  articles/quickstart/backend/java-spring-security5/download.md
  articles/quickstart/backend/java-spring-security5/index.yml
Labels: medium

#8010 Fix API link in Authz how-to
  articles/authorization/guides/how-to.md
Labels: ready-for-review, tiny

#8018 Added video links to Architecture Scenarios
  articles/architecture-scenarios/_includes/_architecture/_introduction.md
  articles/architecture-scenarios/_includes/_authentication/_introduction.md
  articles/architecture-scenarios/_includes/_authorization/_introduction.md
  articles/architecture-scenarios/_includes/_branding/_introduction.md
  articles/architecture-scenarios/_includes/_logout/_introduction.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_introduction.md
  articles/architecture-scenarios/_includes/_provisioning/_introduction.md
  articles/architecture-scenarios/implementation-resources.md
  articles/architecture-scenarios/index.md
Labels: ready-for-review, small

#8013 Removing MFA clarifications
  articles/multifactor-authentication/reset-user.md
  articles/multifactor-authentication/troubleshooting.md
Labels: ready-for-review

#8012 Cull docs page down to topics related to the title
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
Labels: ready-for-review

#7968 Add Infra section and reorg MPC folder
  articles/private-saas-deployment/onboarding/managed-private-cloud/index.md
  articles/private-saas-deployment/onboarding/managed-private-cloud/infrastructure.md
  articles/private-saas-deployment/onboarding/managed-private-cloud/ip-domain-port-list.md
Labels: medium, ready-for-review

#8009 Quickstart Angular Rx rewrite
  articles/quickstart/spa/angular2/02-calling-an-api.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/angular2/index.yml
Labels: quickstart

#7946 Remove all references to 'grained' access control, and reword a few t…
  articles/architecture-scenarios/_includes/_authorization/_api-integration.md
  articles/architecture-scenarios/_includes/_authorization/_introduction.md
Labels: ready-for-review, small

#8021 Update b2b-provisioning.md broken link
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
Labels: ready-for-review, tiny

#7952 Update delete-reset-tenant.md
  articles/policies/restore-deleted-tenant.md
  articles/support/_delete-tenant.md
  articles/support/cancel-paid-subscriptions.md
  articles/support/delete-reset-tenant.md
  articles/support/removing-auth0-exporting-data.md
  articles/support/reset-account-password.md
  articles/support/subscription.md
Labels: ready-for-review, small

#8027 Update extending.md
  articles/cms/wordpress/extending.md
Labels: ready-for-review

#8017 Adding examples passage
  articles/rules/index.md
Labels: ready-for-review

#8016 Adding to UL doc some basic instructions on calling authorize
  articles/universal-login/index.md
Labels: ready-for-review

#8030 Adding caveat about new universal login
  articles/connections/social/devkeys.md
Labels: ready-for-review

#8038 Fix punctuation, flow
  articles/cross-origin-authentication/index.md
Labels: ready-for-review, tiny

#8041 Update sms-gateway.md
  articles/connections/passwordless/sms-gateway.md
Labels: ready-for-review, tiny

#8040 Create auth0-spa-js migration page
  articles/libraries/auth0-spa-js/index.md
  articles/libraries/auth0-spa-js/migrate-from-auth0js.md
  config/sidebar.yml
Labels: do-not-merge
