Repository auth0/docs, pull requests merged in 2019-05, with the labels that each got.

#7572 Update bulk-user-exports.md
  articles/users/guides/bulk-user-exports.md
Labels: ready-for-review

#7575 Clarifying copy
  articles/users/guides/redirect-users-after-login.md
Labels: ready-for-review

#7582 Fix link to image
  articles/migrations/guides/facebook-graph-api-deprecation.md
Labels: ready-for-review

#7581 Fix typo
  articles/migrations/index.md
Labels: ready-for-review

#7567 Update manage-user-metadata.md
  articles/users/guides/manage-user-metadata.md
Labels: ready-for-review

#7583 Update RBAC redirect
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7245 [React Native Quickstart Guide] Remove --dev option from yarn install command
  articles/quickstart/native/react-native/00-login.md
  articles/quickstart/native/react-native/_includes/_install.md
Labels: quickstart

#7590 Fix link and add redirect
  articles/users/guides/manage-users-using-the-management-api.md
  config/redirects.js
Labels: ready-for-review

#7585 Update rules user object reference
  articles/rules/references/user-object.md
Labels: ready-for-review

#7587 Update custom oauth2 provider doc
  articles/connections/social/oauth2.md
Labels: ready-for-review

#7588 Update get user profile API endpoint
  articles/api/authentication/_userinfo.md
Labels: ready-for-review

#7591 Fix link and update redirect
  articles/microsites/manage-users/manage-users-and-user-profiles.md
  config/redirects.js
Labels: ready-for-review

#7601 Update configuration.md
  articles/cms/wordpress/configuration.md
Labels: ready-for-review

#7420 Fix: scoping storage bug
  articles/quickstart/spa/angular2/04-authorization.md
Labels: quickstart

#7598 Update screenshot
  media/articles/sessions/tenant-settings-advanced-login-session-management.png
Labels: ready-for-review

#7609 Update images in flow docs to reflect correct /token endpoint
  media/articles/flows/concepts/auth-sequence-auth-code-pkce.png
  media/articles/flows/concepts/auth-sequence-auth-code.png
  media/articles/flows/concepts/auth-sequence-hybrid.png
  media/articles/microsites/overview-flow-add-login-native-mobile-app.png
  media/articles/microsites/overview-flow-add-login-regular-web-app.png
  media/articles/microsites/overview-flow-call-api-m2m-app.png
  media/articles/microsites/overview-flow-call-api-native-mobile-app.png
  media/articles/microsites/overview-flow-call-api-regular-web-app.png
Labels: ready-for-review

#7437 IUM-272: Update signup endpoint documentation
  articles/api/authentication/_sign-up.md
Labels: ready-for-review

#7223 Update user profile docs for updatable root attributes
  articles/_includes/_users_update_normalized_profile_attributes.md
  articles/api/management/guides/connections/configure-connection-sync.md
  articles/api/management/guides/connections/retrieve-connection-options.md
  articles/api/management/guides/users/set-root-attributes-user-import.md
  articles/api/management/guides/users/set-root-attributes-user-signup.md
  articles/api/management/guides/users/update-root-attributes-users.md
  articles/connections/index.md
  articles/dashboard/guides/applications/update-grant-types.md
  articles/dashboard/guides/connections/configure-connection-sync.md
  articles/extensions/user-import-export.md
  articles/libraries/custom-signup.md
  articles/rules/_includes/_user-prop-identities.md
  articles/rules/references/legacy.md
  articles/rules/references/user-object.md
  articles/users/_includes/_user-prop-identities.md
  articles/users/concepts/overview-user-metadata.md
  articles/users/guides/bulk-user-exports.md
  articles/users/guides/bulk-user-imports.md
  articles/users/guides/change-user-pictures.md
  articles/users/guides/manage-users-using-the-dashboard.md
  articles/users/guides/manage-users-using-the-management-api.md
  articles/users/guides/read-metadata.md
  articles/users/guides/update-user-profiles-using-your-database.md
  articles/users/normalized/auth0/identify-users.md
  articles/users/normalized/auth0/index.md
  articles/users/normalized/auth0/normalized-user-profile-schema.md
  articles/users/normalized/auth0/retrieve-user-profiles.md
  articles/users/normalized/auth0/sample-user-profiles.md
  articles/users/normalized/auth0/store-user-data.md
  articles/users/normalized/auth0/update-root-attributes.md
  articles/users/references/bulk-import-database-schema-examples.md
  articles/users/references/user-data-storage-scenario.md
  articles/users/references/user-profile-structure.md
  articles/users/search/v3/index.md
  config/redirects.js
  config/sidebar.yml
  media/articles/connections/allow-update-normalized-user-profile.png
Labels: ready-for-review

#7633 Fix broken link
  articles/connections/social/oauth2.md
Labels: ready-for-review

#7618 Update enable-sso-tenant.md
  articles/dashboard/guides/tenants/enable-sso-tenant.md
Labels: ready-for-review

#7639 Add more context for token and SPA; reorganize example
  articles/api/management/v2/get-access-tokens-for-spas.md
Labels: ready-for-review

#7642 Adding video tutorial to WordPress docs
  articles/cms/wordpress/index.md
Labels: ready-for-review

#7650 Update VSTS deploy doc
  articles/extensions/visual-studio-team-services-deploy.md
Labels: ready-for-review

#7651 Update SLD
  articles/support/sld.md
Labels: ready-for-review

#7655 Add tenant logs migration to migrations index page
  articles/migrations/index.md
Labels: ready-for-review

#7657 Update Browser Testing link
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#7658 Update terms and screenshots
  articles/architecture-scenarios/_includes/_api-configure-scopes.md
  media/articles/architecture-scenarios/mobile-api/add-permissions.png
  media/articles/architecture-scenarios/mobile-api/add-scopes.png
Labels: ready-for-review

#7661 Rewrite Reset Password doc for clarity
  articles/support/reset-account-password.md
Labels: ready-for-review

#7656 Update signatureAlgorithm values
  articles/protocols/saml/saml-configuration/saml-assertions.md
Labels: ready-for-review

#7652 Fix redirects
  config/redirects.js
Labels: ready-for-review

#7663 Update classic.md
  articles/universal-login/classic.md
Labels: ready-for-review

#7665 Change password reset requirement
  articles/users/guides/bulk-user-imports.md
Labels: ready-for-review

#7666 Added details about compatible passwords
  articles/users/references/bulk-import-database-schema-examples.md
Labels: ready-for-review

#7667 Include details about compatible passwords
  articles/users/references/user-profile-structure.md
Labels: ready-for-review

#7669 Add grace period end dates for logs migration
  articles/migrations/index.md
Labels: ready-for-review

#7670 Add clarification note
  articles/connections/social/github.md
Labels: ready-for-review

#7662 Add logout docs to Java Quickstart and update common callback URL QS docs to be consistent
  articles/_includes/_callback_url.md
  articles/_includes/_logout_url.md
  articles/quickstart/webapp/_includes/_getting_started.md
  articles/quickstart/webapp/java/01-login.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/java/download.md
Labels: quickstart

#7506 Add app selector tag to download model; clarify code samples
  articles/_includes/_new_app.md
  articles/quickstart/webapp/_includes/_getting_started.md
  articles/quickstart/webapp/aspnet-core-v1_1/01-login.md
  articles/quickstart/webapp/aspnet-core/01-login.md
  articles/quickstart/webapp/aspnet-owin/01-login.md
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/download.md
Labels: quickstart, ready-for-review

#7593 Update Workday SAML SSO requirements
  articles/protocols/saml/saml-apps/workday.md
Labels: do-not-merge

#7671 Add include describing how to find Auth0 domain
  articles/connections/social/37signals.md
  articles/connections/social/amazon.md
  articles/connections/social/auth0-oidc.md
  articles/connections/social/baidu.md
  articles/connections/social/bitbucket.md
  articles/connections/social/box.md
  articles/connections/social/docomo.md
  articles/connections/social/dropbox.md
  articles/connections/social/dwolla.md
  articles/connections/social/exact.md
  articles/connections/social/fitbit.md
  articles/connections/social/github.md
  articles/connections/social/goodreads.md
  articles/connections/social/paypal.md
  articles/connections/social/planning-center.md
  articles/connections/social/renren.md
  articles/connections/social/salesforce.md
  articles/connections/social/soundcloud.md
  articles/connections/social/thecity.md
  articles/connections/social/twitter.md
  articles/connections/social/vkontakte.md
  articles/connections/social/weibo.md
  articles/connections/social/wordpress.md
  articles/connections/social/yahoo.md
  articles/connections/social/yammer.md
  articles/connections/social/yandex.md
Labels: ready-for-review

#7361 Google Apps replacements
  articles/api/management/v1/index.md
  articles/api/management/v1/reference.md
  articles/applications/concepts/multiple-tenants.md
  articles/architecture-scenarios/b2b.md
  articles/architecture-scenarios/b2e.md
  articles/cms/index.md
  articles/cms/wordpress/index.md
  articles/connections/enterprise/google-apps.md
  articles/connections/social/google.md
  articles/custom-domains/additional-configuration.md
  articles/custom-domains/index.md
  articles/getting-started/the-basics.md
  articles/guides/login/universal-vs-embedded.md
  articles/integrations/configuration-to-query-users-from-google-apps.md
  articles/integrations/office-365-custom-provisioning.md
  articles/libraries/lock-ios/v1/index.md
  articles/libraries/lock/v11/selecting-the-connection-for-multiple-logins.md
  articles/protocols/saml/index.html
  articles/protocols/saml/saml-apps/google-apps.md
  articles/protocols/saml/saml-apps/index.md
  articles/rules/references/context-object.md
  articles/users/guides/impersonate-users-using-the-impersonation-api.md
Labels: ready-for-review

#7672 Update migrate-search-v2-v3.md
  articles/users/search/v3/migrate-search-v2-v3.md
Labels: ready-for-review

#7685 Fix typo "click-jacking" to "clickjacking"
  articles/migrations/guides/clickjacking-protection.md
Labels: ready-for-review

#7584 PSaaS Landing and Add-On Pages
  articles/private-cloud/index.md
  articles/private-saas-deployment/add-ons.md
  articles/private-saas-deployment/index.md
  articles/private-saas-deployment/managed-private-cloud/index.md
  articles/private-saas-deployment/private-cloud/index.md
  config/redirects.js
Labels: do-not-merge

#7687 Add logout docs to Spring MVC and Spring Security Webapp Quickstarts
  articles/quickstart/webapp/java-spring-mvc/01-login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-mvc/download.md
  articles/quickstart/webapp/java-spring-security-mvc/01-login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/download.md
Labels: quickstart

#7695 Remove outdated/unnecessary screenshot
  articles/logout/guides/logout-applications.md
Labels: ready-for-review

#7696 Add user exports job to rate limits
  articles/policies/rate-limits.md
Labels: ready-for-review

#7686 Add warning about auth0 namespaces for custom claims
  articles/extensions/delegated-admin/v3/index.md
Labels: ready-for-review

#7700 Remove deprecated deployment options for VM infrastructure
  articles/appliance/infrastructure/virtual-machines.md
Labels: ready-for-review

#7701 Update psaas faq on CSR files for SSL certs
  articles/appliance/infrastructure/faq.md
Labels: ready-for-review
