Repository auth0/docs, pull requests merged in 2019-01, with the labels that each got.

#7097 Adjust callback URL configuration for WP-Auth0
  articles/cms/wordpress/configuration.md
Labels: ready-for-review

#7100 Update plugin migration steps
  articles/cms/wordpress/troubleshoot.md
Labels: ready-for-review

#7103 Fix issue renewing session after log out
  snippets/application-platforms/vuejs/use.md
Labels: quickstart

#7102 Adding MFA guardian redirects
  config/redirects.js
Labels: ready-for-review

#6902 Removed portion about enforcing namespacing when using OIDC flows
  articles/api-auth/tutorials/adoption/scope-custom-claims.md
Labels: ready-for-review

#7106 Fix broken links for Management API
  articles/api/management/v2/get-access-tokens-for-production.md
Labels: ready-for-review

#7105 Adding a MFA troubleshooting guide
  articles/multifactor-authentication/index.md
  articles/multifactor-authentication/troubleshooting.md
  config/sidebar.yml
Labels: ready-for-review

#7116 Add custom domain example to redirect rule page
  articles/rules/guides/redirect.md
Labels: ready-for-review

#7111 Updated the docs in line with the new sample code
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  snippets/application-platforms/vuejs/use.md
Labels: quickstart

#7109 Deploy CLI Tool new documentation
  articles/extensions/deploy-cli/_includes/_limitations.md
  articles/extensions/deploy-cli/_includes/_strip-option.md
  articles/extensions/deploy-cli/guides/call-deploy-cli-programmatically.md
  articles/extensions/deploy-cli/guides/import-export-directory-structure.md
  articles/extensions/deploy-cli/guides/import-export-yaml-file.md
  articles/extensions/deploy-cli/guides/incorporate-deploy-cli-into-build-environment.md
  articles/extensions/deploy-cli/guides/install-deploy-cli.md
  articles/extensions/deploy-cli/index.md
  articles/extensions/deploy-cli/references/deploy-cli-options.md
  articles/extensions/deploy-cli/references/environment-variables-keyword-mappings.md
  articles/extensions/deploy-cli/references/whats-new-v2.md
  articles/extensions/github-deploy.md
  config/sidebar.yml
  media/articles/extensions/deploy-cli/step1-extensions-overview.png
  media/articles/extensions/deploy-cli/step2-extension-link.png
  media/articles/extensions/deploy-cli/step3-auth0-deploy-cli-homepage.png
  updates/2019-01-07.yml
Labels: ready-for-review

#7122 Fix broken link to third-party-applications
  articles/applications/enable-third-party-applications.md
Labels: ready-for-review

#7124 removed the dead-link
  articles/appliance/index.html
  config/sidebar.yml
Labels: ready-for-review

#7092 Add "email" to scope
  articles/quickstart/webapp/aspnet-core/02-user-profile.md
Labels: quickstart

#7042 Remove use of local storage in JavaScript quickstart
  articles/quickstart/spa/vanillajs/02-user-profile.md
  articles/quickstart/spa/vanillajs/03-calling-an-api.md
  articles/quickstart/spa/vanillajs/04-authorization.md
  articles/quickstart/spa/vanillajs/05-token-renewal.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/download.md
Labels: quickstart

#7126 Add note about auth0-notifications domain blacklisting
  articles/_includes/_email-domain-blacklist.md
  articles/dev-lifecycle/local-testing-and-development.md
  articles/email/testing.md
Labels: ready-for-review

#7120 Added security bulletin for rules
  articles/security/bulletins/2019-01-10_rules.md
  articles/security/bulletins/index.md
Labels: ready-for-review

#7006 Twitter social connector updates for new Twitter dev site
  articles/connections/social/twitter.md
  media/articles/connections/social/twitter/twitter-api-1.png
  media/articles/connections/social/twitter/twitter-api-10.png
  media/articles/connections/social/twitter/twitter-api-2.png
  media/articles/connections/social/twitter/twitter-api-3.png
  media/articles/connections/social/twitter/twitter-api-4.png
  media/articles/connections/social/twitter/twitter-api-5.png
  media/articles/connections/social/twitter/twitter-api-6.png
  media/articles/connections/social/twitter/twitter-api-7.png
  media/articles/connections/social/twitter/twitter-api-8.png
  media/articles/connections/social/twitter/twitter-api-9.png
Labels: ready-for-review

#7132 Add new filter: auth0_die_on_login_output
  articles/cms/wordpress/extending.md
Labels: ready-for-review

#7135 Update Rules Modules
  articles/rules/references/modules.md
Labels: ready-for-review

#7128 Add note to suggest how to handle rate limiting
  articles/hooks/index.md
  articles/policies/rate-limits.md
  articles/rules/index.md
Labels: ready-for-review

#7137 Remove reference to New Relic
  articles/appliance/dashboard/settings.md
Labels: ready-for-review

#7138 Remove IE 11 support for Dashboard
  articles/support/matrix.md
Labels: ready-for-review

#7139 MFA Duo addition
  articles/multifactor-authentication/factors/duo.md
Labels: ready-for-review

#7140 Typo fix cli doc
  CONTRIBUTING.md
  articles/integrations/using-auth0-to-secure-a-cli.md
Labels: ready-for-review

#7099 Rework Search v3 content
  articles/api/management/v2/tokens.md
  articles/best-practices/search-best-practices.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/index.md
  articles/policies/data-export.md
  articles/users/concepts/overview-user-migration.md
  articles/users/guides/bulk-user-exports.md
  articles/users/guides/bulk-user-imports.md
  articles/users/guides/configure-automatic-migration.md
  articles/users/guides/create-users.md
  articles/users/guides/manage-users-using-the-dashboard.md
  articles/users/guides/read-metadata.md
  articles/users/index.md
  articles/users/references/bulk-import-database-schema-examples.md
  articles/users/references/user-migration-scenarios.md
  articles/users/search/v3/_valid-access-token.md
  articles/users/search/v3/get-users-by-email-endpoint.md
  articles/users/search/v3/get-users-by-id-endpoint.md
  articles/users/search/v3/get-users-endpoint.md
  articles/users/search/v3/index.md
  articles/users/search/v3/migrate-search-v2-v3.md
  articles/users/search/v3/query-syntax.md
  articles/users/search/v3/sort-search-results.md
  articles/users/search/v3/view-search-results-by-page.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7117 Appliance Deprecation: Docker Registry Port 5000
  articles/appliance/extensions.md
  articles/appliance/infrastructure/extensions.md
  articles/appliance/infrastructure/security.md
  articles/appliance/modules.md
  articles/appliance/webtasks/index.md
Labels: do-not-merge

#7145 docs-371: Passwordless custom domains
  articles/connections/passwordless/_custom-domains.md
  articles/connections/passwordless/_introduction.md
  articles/connections/passwordless/ios-magic-link.md
  articles/connections/passwordless/regular-web-app-email-code.md
  articles/connections/passwordless/regular-web-app-email-link.md
  articles/connections/passwordless/regular-web-app-sms.md
  articles/connections/passwordless/spa-email-code.md
  articles/connections/passwordless/spa-email-link.md
  articles/connections/passwordless/spa-sms.md
  articles/guides/login/universal-vs-embedded.md
Labels: ready-for-review

#7159 Fixed email_verified authorization callback
  articles/best-practices/rules.md
  articles/security/bulletins/2019-01-10_rules.md
Labels: ready-for-review

#7154 Update user-consent.md
  articles/api-auth/user-consent.md
Labels: ready-for-review

#7156 Add smoke test details
  articles/appliance/admin/updating-the-appliance.md
Labels: ready-for-review

#7155 Update enterprise support desc
  articles/support/index.md
Labels: ready-for-review

#7153 Clarify JS/Node usage for rules modules
  articles/rules/references/modules.md
Labels: ready-for-review

#7071 Update scopes docs
  articles/_includes/_checksession_polling.md
  articles/api-auth/config/using-the-auth0-dashboard.md
  articles/api-auth/config/using-the-management-api.md
  articles/api-auth/index.md
  articles/api-auth/restrict-requests-for-scopes.md
  articles/api-auth/tutorials/represent-multiple-apis.md
  articles/api/authorization-extension/_introduction.md
  articles/applications/machine-to-machine.md
  articles/extensions/authorization-extension/v2/rules.md
  articles/guides/migration-legacy-flows.md
  articles/libraries/auth0js/v8/migration-guide.md
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/migrations/guides/migration-oauthro-oauthtoken.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/webapp/django/01-login.md
  articles/scopes/current/api-scopes.md
  articles/scopes/current/custom-claims.md
  articles/scopes/current/guides/customize-consent-prompt.md
  articles/scopes/current/guides/define-api-scopes-dashboard.md
  articles/scopes/current/index.md
  articles/scopes/current/oidc-scopes.md
  articles/scopes/current/sample-use-cases.md
  articles/tokens/id-token.md
Labels: ready-for-review

#7146 Logout content rework
  articles/logout/_includes/_logout-endpoint.md
  articles/logout/guides/logout-applications.md
  articles/logout/guides/logout-auth0.md
  articles/logout/guides/logout-idps.md
  articles/logout/guides/logout-saml-idps.md
  articles/logout/guides/redirect-users-after-logout.md
  articles/logout/index.md
  articles/protocols/saml/saml-configuration/logout.md
  articles/quickstart/webapp/golang/01-login.md
  articles/quickstart/webapp/python/01-login.md
  articles/quickstart/webapp/rails/02-session-handling.md
  articles/quickstart/webapp/scala/01-login.md
  articles/users/guides/redirect-users-after-login.md
  articles/users/index.md
  config/sidebar.yml
  media/articles/logout/signing-out-scenario1.png
  media/articles/logout/signing-out-scenario2.png
  media/articles/logout/single-sign-out.png
Labels: ready-for-review

#7084 Add AngularJS Quickstart
  articles/quickstart/spa/angularjs/01-login.md
  articles/quickstart/spa/angularjs/02-user-profile.md
  articles/quickstart/spa/angularjs/03-calling-an-api.md
  articles/quickstart/spa/angularjs/04-authorization.md
  articles/quickstart/spa/angularjs/05-token-renewal-download.md
  articles/quickstart/spa/angularjs/05-token-renewal.md
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
  articles/quickstart/spa/angularjs/_includes/_install_angular_auth0.md
  articles/quickstart/spa/angularjs/download.md
  articles/quickstart/spa/angularjs/index.yml
Labels: quickstart

#7134 Update Logs docs
  articles/logs/index.md
  articles/logs/query-syntax.md
  config/sidebar.yml
Labels: ready-for-review

#7171 Fix User Search v3 documentation
  articles/users/search/v3/index.md
  config/sidebar.yml
Labels: ready-for-review

#7168 Update M2M APIs
  articles/applications/machine-to-machine.md
  media/articles/applications/m2m-apis.png
Labels: ready-for-review

#7167 Remove duplicate email scope and clarify "token"
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
Labels: ready-for-review

#7169 Typo: taken to token
  articles/tokens/set-access-token-lifetime.md
Labels: ready-for-review

#7162 Update configuration.md
  articles/cms/wordpress/configuration.md
Labels: ready-for-review

#7181 Re-adding the Guardian developer docs
  articles/multifactor-authentication/developer/custom-enrollment-ticket.md
  articles/multifactor-authentication/developer/index.md
  articles/multifactor-authentication/developer/libraries/android/index.md
  articles/multifactor-authentication/developer/libraries/ios/index.md
  articles/multifactor-authentication/developer/sns-configuration.md
Labels: ready-for-review

#7195 Update Javascrit Quickstart: fix typos
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart

#7200 Make instructions to bring in auth0.js via dependencies or CDN more explicit
  articles/quickstart/spa/_includes/_install_auth0js.md
Labels: quickstart

#7194 Add a redirect
  config/redirects.js
Labels: ready-for-review

#7118 Add Auth0-PHP to Libraries section
  articles/libraries/auth0-php/authentication-api.md
  articles/libraries/auth0-php/basic-use.md
  articles/libraries/auth0-php/index.md
  articles/libraries/auth0-php/jwt-validation.md
  articles/libraries/auth0-php/management-api.md
  articles/libraries/auth0-php/troubleshooting.md
  articles/libraries/index.md
Labels: ready-for-review

#6841 Break up JWT content
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
  articles/architecture-scenarios/mobile-api/part-3.md
  articles/best-practices/application-settings.md
  articles/flows/guides/mobile-login-flow/includes/refresh-tokens.md
  articles/flows/guides/mobile-login-flow/includes/request-tokens.md
  articles/flows/guides/regular-web-app-login-flow/includes/refresh-tokens.md
  articles/flows/guides/regular-web-app-login-flow/includes/request-tokens.md
  articles/flows/guides/single-page-login-flow/includes/authorize-user-add-login.md
  articles/flows/guides/single-page-login-flow/includes/authorize-user-call-api.md
  articles/flows/guides/single-page-login-flow/includes/refresh-tokens.md
  articles/flows/guides/single-page-login-flow/includes/request-tokens.md
  articles/microsites/add-login/add-login-regular-web-app.md
  articles/microsites/add-login/add-login-single-page-app.md
  articles/microsites/call-api/call-api-m2m-app.md
  articles/microsites/call-api/call-api-native-mobile-app.md
  articles/microsites/call-api/call-api-regular-web-app.md
  articles/microsites/call-api/call-api-single-page-app.md
  articles/microsites/protect-api/protect-api.md
  articles/migrations/index.md
  articles/tokens/concepts/token-best-practices.md
  articles/tokens/concepts/why-use-jwt.md
  articles/tokens/guides/id-token/validate-id-token.md
  articles/tokens/guides/jwt/parse-validate-jwt-programmatically.md
  articles/tokens/guides/jwt/verify-jwt-signature-using-jwks.md
  articles/tokens/guides/revoke-tokens.md
  articles/tokens/guides/update-signing-algorithm-application.md
  articles/tokens/id-token.md
  articles/tokens/index.html
  articles/tokens/jwks.md
  articles/tokens/jwt-claims.md
  articles/tokens/jwt.md
  articles/tokens/reference/jwt/jwks-properties.md
  articles/tokens/reference/jwt/jwt-structure.md
  updates/2017-09-08.yml
Labels: ready-for-review

#7185 Adding more info on wsfed certificate rollover
  articles/protocols/ws-fed/index.md
Labels: ready-for-review
