Repository auth0/docs, pull requests merged in 2019-02, with the labels that each got.

#7209 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#7210 docs-394-remove-screenshot
  articles/extensions/delegated-admin/v3/hooks/index.md
  media/articles/extensions/delegated-admin/dashboard-configuration.png
Labels: ready-for-review

#7212 PS-277 update authz scope validation rules
  articles/architecture-scenarios/spa-api/part-2.md
Labels: ready-for-review

#7170 Updated oauth/ro endpoints to passwordless/verify
  articles/api/authentication/_passwordless.md
  articles/api/authentication/errors/_passwordless-verify.md
  articles/api/authentication/index.md
Labels: ready-for-review

#7218 Update _centralized_login.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart

#7220 Update user-profile-structure.md
  articles/rules/_includes/_user-prop-identities.md
  articles/rules/references/user-object.md
  articles/users/_includes/_user-prop-identities.md
  articles/users/references/user-profile-structure.md
  articles/users/search/v3/query-syntax.md
Labels: ready-for-review

#7235 Fix references to extensibility points
  articles/topics/extensibility.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7238 Fix broken link
  articles/api/management/v2/create-m2m-app.md
Labels: ready-for-review

#7239 Fixed another broken link
  articles/api-auth/config/using-the-auth0-dashboard.md
  articles/api-auth/config/using-the-management-api.md
Labels: ready-for-review

#7240 Fix broken sidebar link for hooks
  articles/hooks/concepts/extensibility-points.md
  articles/hooks/concepts/post-user-registration-extensibility-point.md
  articles/hooks/concepts/pre-user-registration-extensibility-point.md
  articles/hooks/index.md
  config/sidebar.yml
Labels: ready-for-review

#7246 Update mitigate-csrf-attacks.md
  articles/protocols/oauth2/mitigate-csrf-attacks.md
Labels: ready-for-review

#7230 Updating Load Testing Policy
  articles/policies/load-testing.md
Labels: ready-for-review

#7174 Update .Net Core 2.1 Quickstart
  articles/quickstart/webapp/aspnet-core/02-user-profile.md
  articles/quickstart/webapp/aspnet-core/03-authorization.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/download.md
  articles/quickstart/webapp/aspnet-core/index.yml
Labels: quickstart

#7252 Update heading for CSRF Attacks
  articles/users/guides/impersonate-users-using-the-dashboard.md
Labels: ready-for-review

#7255 update-adobe-import-wizard-link
  articles/integrations/marketing/adobe-campaign/index.md
Labels: ready-for-review

#7256 change-link-text-M2M-quickstart
  articles/flows/concepts/m2m-flow.md
Labels: ready-for-review

#7257 Update block-and-unblock-users.md
  articles/users/guides/block-and-unblock-users.md
Labels: ready-for-review

#7251 Refresh Tokens
  articles/tokens/refresh-token/current/index.md
  articles/tokens/refresh-token/legacy/index.md
Labels: ready-for-review

#7261 New bulletin entry - CVE-2019-7644
  articles/security/bulletins/cve-2019-7644.md
  articles/security/bulletins/index.md
Labels: ready-for-review

#7258 Clarifying Duo setup and behavior
  articles/multifactor-authentication/factors/duo.md
Labels: ready-for-review

#7260 Update screenshot for customization
  media/articles/universal-login/login.png
Labels: ready-for-review

#7263 Moving warning above instructions to preempt problems
  articles/hooks/_includes/set-up-webtask-cli.md
Labels: ready-for-review

#7259 monitoring-auth0-rework
  articles/architecture-scenarios/b2b.md
  articles/architecture-scenarios/b2e.md
  articles/connector/scom-monitoring.md
  articles/monitoring/_includes/_monitor-appliance.md
  articles/monitoring/guides/check-external-services.md
  articles/monitoring/guides/check-status.md
  articles/monitoring/guides/monitor-applications.md
  articles/monitoring/guides/monitor-using-SCOM.md
  articles/monitoring/guides/send-events-to-keenio.md
  articles/monitoring/guides/send-events-to-segmentio.md
  articles/monitoring/guides/send-events-to-splunk.md
  articles/monitoring/guides/test-testall-endpoints.md
  articles/monitoring/guides/track-leads-salesforce.md
  articles/monitoring/guides/track-signups-salesforce.md
  articles/monitoring/how-to-monitor-auth0.md
  articles/monitoring/index.md
  articles/troubleshoot/basics.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7272 Re-adding Universal Login simple settings info
  articles/universal-login/index.md
Labels: ready-for-review

#7274 Clean up Auth0 OIDC Docs
  articles/connections/social/auth0-oidc.md
  media/articles/connections/social/auth0-oidc/child-app.png
  media/articles/connections/social/auth0-oidc/login-page.png
Labels: ready-for-review

#7217 Appliance: Set up federated access to Dashboard
  articles/appliance/admin/federated-access-to-manage.md
Labels: ready-for-review

#7276 Fixing a 404
  config/redirects.js
Labels: ready-for-review

#7275 Adding two support videos to relevant docs pages
  articles/custom-domains/index.md
  articles/protocols/saml/saml-configuration/special-configuration-scenarios/idp-initiated-sso.md
Labels: ready-for-review

#7280 Revert removal of GA/FBA integration docs
  articles/analytics/integrations/_install.md
  articles/analytics/integrations/_usage.md
  articles/analytics/integrations/facebook-analytics/index.md
  articles/analytics/integrations/google-analytics/index.md
  articles/analytics/integrations/index.md
  config/redirects.js
Labels: ready-for-review

#7281 Fixing redirect
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7283 Fixing a redirect issue
  articles/libraries/custom-signup.md
  config/redirects.js
Labels: ready-for-review

#7268 Add LinkedIn API V2 migration doc
  articles/migrations/guides/linkedin-api-deprecation.md
  media/articles/connections/social/linkedin/linkedin-connection-new.png
Labels: ready-for-review

#7285 Fixes to Google Analytics
  articles/analytics/integrations/_install.md
  articles/analytics/integrations/google-analytics/index.md
Labels: do-not-merge

#7288 Explains access token formats.
  articles/tokens/access-token-formats.md
  articles/tokens/overview-access-tokens.md
  articles/tokens/set-access-token-format.md
  articles/tokens/use-access-tokens.md
  config/redirects.js
Labels: ready-for-review

#7290 Penetration testing policy update
  articles/policies/penetration-testing.md
Labels: ready-for-review

#7291 Updating Guardian MFA page code snippets
  articles/universal-login/guardian.md
Labels: ready-for-review

#7286 Update Lock language list
  articles/libraries/lock/v11/i18n.md
Labels: ready-for-review

#7282 Remove docs for legacy versions of lock and auth0.js libraries
  articles/libraries/auth0js/index.yml
  articles/libraries/auth0js/v7/index.md
  articles/libraries/auth0js/v8/index.md
  articles/libraries/auth0js/v8/migration-guide.md
  articles/libraries/index.md
  articles/libraries/lock/index.yml
  articles/libraries/lock/v10/api.md
  articles/libraries/lock/v10/authentication-modes.md
  articles/libraries/lock/v10/configuration.md
  articles/libraries/lock/v10/customizing-error-messages.md
  articles/libraries/lock/v10/i18n.md
  articles/libraries/lock/v10/index.md
  articles/libraries/lock/v10/migration-guide.md
  articles/libraries/lock/v10/new-features.md
  articles/libraries/lock/v10/selecting-the-connection-for-multiple-logins.md
  articles/libraries/lock/v10/sending-authentication-parameters.md
  articles/libraries/lock/v10/ui-customization.md
  articles/libraries/lock/v9/api.md
  articles/libraries/lock/v9/authentication-modes.md
  articles/libraries/lock/v9/configuration.md
  articles/libraries/lock/v9/customizing-error-messages.md
  articles/libraries/lock/v9/i18n.md
  articles/libraries/lock/v9/index.md
  articles/libraries/lock/v9/migration-guide.md
  articles/libraries/lock/v9/selecting-the-connection-for-multiple-logins.md
  articles/libraries/lock/v9/sending-authentication-parameters.md
  articles/libraries/lock/v9/ui-customization.md
  articles/libraries/lock/v9/using-a-refresh-token.md
  articles/libraries/when-to-use-lock.md
  articles/support/matrix.md
  config/redirects.js
Labels: ready-for-review

#7296 Remove anchor link from redirects
  config/redirects.js
Labels: ready-for-review

#7297 Remove duplicate lock v9 redirect
  config/redirects.js
Labels: ready-for-review

#7293 Fixing circular links in universal login documentation
  articles/universal-login/index.md
Labels: ready-for-review

#7049 Updated Vue.js Quickstart docs
  articles/_includes/_logout_url.md
  articles/_includes/_web_origins.md
  articles/quickstart/spa/_includes/_calling_api_create_backend.md
  articles/quickstart/spa/_includes/_calling_api_modify_backend.md
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/_includes/_see_it_in_action.md
  articles/quickstart/spa/vuejs/01-login.md
  articles/quickstart/spa/vuejs/03-calling-an-api.md
  articles/quickstart/spa/vuejs/_includes/_auth_service_method_description.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/download.md
  articles/quickstart/spa/vuejs/index.yml
  snippets/application-platforms/vuejs/use.md
Labels: in-review, quickstart

#7229 .NET OWIN webapp quickstart: Change port and callback URL
  articles/quickstart/webapp/aspnet-owin/02-user-profile.md
  articles/quickstart/webapp/aspnet-owin/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/04-migrating.md
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
  articles/quickstart/webapp/aspnet-owin/_includes/_setup.md
Labels: quickstart

#7206 .Net Core 1.1: Change port to 3000 and callback URL to /callback
  articles/quickstart/webapp/aspnet-core-v1_1/03-authorization.md
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_login.md
  articles/quickstart/webapp/aspnet-core-v1_1/_includes/_setup.md
Labels: quickstart

#7201 Bump version numbers to latest SDK releases
  CONTRIBUTING.md
  config/vars.yml
Labels: quickstart

#7304 GitHub configuration instructions
  articles/protocols/saml/saml-apps/github-cloud.md
  articles/protocols/saml/saml-apps/github-server.md
  articles/protocols/saml/saml-apps/index.md
  media/articles/protocols/saml/github-cloud/client-addons.png
  media/articles/protocols/saml/github-cloud/usage.png
  media/articles/protocols/saml/github-server/client-addons.png
  media/articles/protocols/saml/github-server/usage.png
Labels: ready-for-review

#7273 Update session lifetime limits
  articles/integrations/sso/_template.md
  articles/sso/current/configure-session-lifetime-limits.md
  articles/sso/current/index.md
  articles/sso/current/introduction.md
  articles/sso/current/setup.md
  articles/sso/current/single-page-apps.md
  media/articles/sso/sso-session-mgmt-2.png
Labels: ready-for-review

#7303 Update _libraries_support_frameworks.html
  articles/_includes/_libraries_support_frameworks.html
Labels: ready-for-review
