Repository auth0/docs, pull requests merged in 2019-04, with the labels that each got.

#7438 Java Spring Quickstart: Include configuration logout URL snippet
  articles/quickstart/webapp/java-spring-mvc/01-login.md
Labels: quickstart

#7444 Replacing screenshots
  media/articles/api/tokens/copy-token.png
  media/articles/api/tokens/set-token.png
Labels: ready-for-review

#7442 Removing erroneous date
  articles/users/search/v3/migrate-search-v2-v3.md
Labels: ready-for-review

#7440 Fixing wording Hosted Pages -> Universal Login
  articles/api-auth/passwordless.md
Labels: ready-for-review

#7439 Removing outdated screenshot
  articles/email/custom.md
Labels: ready-for-review

#7434 QS-23: Cleaned up references to local storage for token storage
  articles/quickstart/spa/_includes/_auth_service_check_access_token_expiry.md
  articles/quickstart/spa/_includes/_auth_service_hash_fragment_information.md
  articles/quickstart/spa/_includes/_auth_service_method_description_auth0js.md
  articles/quickstart/spa/_includes/_auth_service_method_description_lock.md
  articles/quickstart/spa/_includes/_auth_service_method_description_no_callback.md
  articles/quickstart/spa/_includes/_auth_service_using_json_web_tokens.md
  articles/quickstart/spa/_includes/_custom_login_method_description.md
  articles/quickstart/spa/_includes/_persisting_state.md
  articles/quickstart/spa/angular2/custom-login-form.md
  articles/quickstart/spa/angular2/embedded-login.md
  articles/quickstart/spa/vuejs/_includes/_auth_service_method_description.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart, ready-for-review

#7178 Re-write for the Laravel API quickstart
  articles/quickstart/backend/laravel/01-authorization.md
Labels: quickstart, ready-for-review

#7204 Update Laravel Webapp Quickstart
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart, ready-for-review

#7446 Update add-permissions-roles.md
  articles/authorization/guides/api/add-permissions-roles.md
Labels: ready-for-review

#7448 SDLC Checklists
  articles/architecture-scenarios/checklists.md
  articles/architecture-scenarios/index.md
  config/sidebar.yml
Labels: ready-for-review

#7429 Django Quickstart: Logout from Auth0 authorization server
  articles/quickstart/webapp/django/01-login.md
Labels: quickstart

#7449 PHP Webapp Quickstart: Include configuration logout URL snippet
  articles/quickstart/webapp/php/01-login.md
Labels: quickstart

#7402 React quickstart: Logout from Auth0 authorization server
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#7378 NodeJS Quickstart: Logout from Auth0 authorization server
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart

#7454 Typo in Implementation Checklists
  articles/architecture-scenarios/checklists.md
Labels: ready-for-review

#7456 Fixed text to make content of article match title
  articles/api-auth/index.md
  articles/api-auth/restrict-access-api.md
  articles/scopes/current/api-scopes.md
  articles/scopes/current/index.md
  articles/scopes/current/sample-use-cases.md
  config/redirects.js
Labels: ready-for-review

#7455 Document options attribute
  articles/connections/references/_includes/_options-prop-pw-complexity.md
  articles/connections/references/_includes/_options-prop-pw-dictionary.md
  articles/connections/references/_includes/_options-prop-pw-expiration.md
  articles/connections/references/_includes/_options-prop-pw-history.md
  articles/connections/references/_includes/_options-prop-pw-no-pers-info.md
  articles/connections/references/_includes/_options-upstream-params.md
  articles/connections/references/_includes/_options-validation.md
  articles/connections/references/options-mgmt-api.md
Labels: ready-for-review

#7458 Adding Authorization Extension section
  articles/api/authentication/legacy/_linking.md
  articles/migrations/guides/extensibility-node8.md
Labels: ready-for-review

#7447 Update Spring Security Quickstart
  articles/quickstart/webapp/java-spring-security-mvc/01-login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
Labels: quickstart

#7460 Created session docs; updated SSO docs
  articles/api-auth/token-renewal-in-safari.md
  articles/api-auth/tutorials/adoption/single-sign-on.md
  articles/application-auth/current/mobile-desktop.md
  articles/applications/application-settings/_settings-pt2.md
  articles/cms/wordpress/configuration.md
  articles/libraries/lock/v11/authentication-modes.md
  articles/sessions/concepts/cookies.md
  articles/sessions/concepts/sample-use-cases-sessions-spas.md
  articles/sessions/concepts/sample-use-cases-sessions.md
  articles/sessions/concepts/session-lifetime.md
  articles/sessions/guides/api/configure-session-lifetime-settings.md
  articles/sessions/guides/dashboard/tenant/configure-session-lifetime-settings.md
  articles/sessions/index.md
  articles/sso/current/configure-session-lifetime-limits.md
  articles/sso/current/guides/enable-sso-application.md
  articles/sso/current/guides/enable-sso-tenant.md
  articles/sso/current/index.md
  articles/sso/current/introduction.md
  articles/sso/current/single-page-apps.md
  articles/sso/current/sso-auth0.md
  config/redirects.js
  config/sidebar.yml
  media/articles/applications/app-list.png
  media/articles/applications/app-settings-danger-zone-legacy.png
  media/articles/sessions/tenant-settings-advanced-login-session-management.png
  media/articles/sessions/tenant-settings.png
  media/articles/sessions/use-case-storezero.png
Labels: ready-for-review

#7465 JWT signing: typo fix and link to blog
  articles/tokens/concepts/why-use-jwt.md
Labels: ready-for-review

#7310 B2C Implementation Guide
  articles/architecture-scenarios/_includes/_rate-limit-policy.md
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/implementation/b2c/b2c-architecture.md
  articles/architecture-scenarios/implementation/b2c/b2c-authentication.md
  articles/architecture-scenarios/implementation/b2c/b2c-authorization.md
  articles/architecture-scenarios/implementation/b2c/b2c-branding.md
  articles/architecture-scenarios/implementation/b2c/b2c-logout.md
  articles/architecture-scenarios/implementation/b2c/b2c-planning.md
  articles/architecture-scenarios/implementation/b2c/b2c-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2c/b2c-provisioning.md
  articles/authorization/guides/dashboard/add-permissions-apis.md
  config/sidebar.yml
  media/articles/architecture-scenarios/b2c-project-plan-milestones.png
  phase-1-implementation-milestones.png
Labels: ready-for-review

#7463 Laravel Web App Quickstart: Logout from Auth0 authorization server
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart

#7412 removed user.logins_count from user object in rules
  articles/rules/references/user-object.md
  articles/users/references/user-profile-structure.md
Labels: ready-for-review, verified

#7474 Remove broken link
  articles/tokens/guides/revoke-tokens.md
Labels: ready-for-review

#7492 Update instructions on creating tenants
  articles/connections/guides/create-multiple-tenants.md
  media/articles/connections/dashboard-create-tenant.png
  media/articles/connections/tenant-create.png
Labels: ready-for-review

#7499 Updating the README for editing options
  README.md
Labels: ready-for-review

#7475 Add content-type headers to har examples
  articles/multifactor-authentication/api/oob.md
  articles/multifactor-authentication/api/otp.md
Labels: ready-for-review

#7436 Logout from Auth0 authorization server
  articles/quickstart/webapp/java/01-login.md
  articles/quickstart/webapp/java/_includes/_login.md
Labels: quickstart

#7482 Update Symfony Quickstart
  articles/quickstart/webapp/symfony/01-login.md
Labels: quickstart

#7493 Remove references to Appliance
  STYLEGUIDE.md
  WORDS.md
  articles/api/management/v2/changes.md
  articles/appliance/disaster-recovery-raci.md
  articles/applications/guides/enable-third-party-applications.md
  articles/compliance/gdpr/features-aiding-compliance/protect-user-data.md
  articles/connector/troubleshooting.md
  articles/custom-domains/index.md
  articles/email/templates.md
  articles/extensions/delegated-admin/v2/index.md
  articles/extensions/delegated-admin/v3/index.md
  articles/extensions/user-import-export.md
  articles/getting-started/the-basics.md
  articles/monitoring/_includes/_monitor-appliance.md
  articles/monitoring/_includes/_monitor-private-cloud.md
  articles/monitoring/guides/test-testall-endpoints.md
  articles/monitoring/index.md
  articles/onboarding/enterprise-support.md
  articles/policies/data-transfer.md
  articles/policies/penetration-testing.md
  articles/services/index.md
  articles/services/private-cloud-configuration.md
  articles/services/private-cloud-management.md
  articles/support/tickets.md
  articles/users/search/v3/index.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7500 Removed planning
  articles/architecture-scenarios/b2c.md
  articles/architecture-scenarios/implementation/b2c/b2c-architecture.md
  articles/architecture-scenarios/implementation/b2c/b2c-authentication.md
  articles/architecture-scenarios/implementation/b2c/b2c-authorization.md
  articles/architecture-scenarios/implementation/b2c/b2c-branding.md
  articles/architecture-scenarios/implementation/b2c/b2c-deployment.md
  articles/architecture-scenarios/implementation/b2c/b2c-logout.md
  articles/architecture-scenarios/implementation/b2c/b2c-operations.md
  articles/architecture-scenarios/implementation/b2c/b2c-planning.md
  articles/architecture-scenarios/implementation/b2c/b2c-profile-mgmt.md
  articles/architecture-scenarios/implementation/b2c/b2c-provisioning.md
  articles/architecture-scenarios/implementation/b2c/b2c-qa.md
  config/sidebar.yml
  media/articles/architecture-scenarios/b2c-project-plan-milestones.png
Labels: ready-for-review

#7503 Fix broken anchor link to AD/LDAP Connector
  articles/custom-domains/additional-configuration.md
Labels: ready-for-review

#7505 Remove single-page app SSO sample
  articles/sso/current/index.md
  articles/sso/current/single-page-apps.md
Labels: ready-for-review

#7511 Add authorization object to rules context object
  articles/rules/_includes/_context-prop-authorization.md
  articles/rules/references/context-object.md
Labels: ready-for-review

#7513 Remove future release references
  articles/api-auth/tutorials/adoption/single-sign-on.md
  articles/api-auth/user-consent.md
Labels: ready-for-review

#7510 Scala Play Web App Quickstart: Use docs variables
  articles/quickstart/webapp/scala/01-login.md
Labels: quickstart

#7508 Scala Weba App Quickstart: Update download instruccions
  articles/quickstart/webapp/scala/download.md
Labels: quickstart

#7507 Rails Web App Quickstart: include logout URL configuration snippet
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart

#7502 Python Web App Quickstart: include logout URL configuration snippet
  articles/quickstart/webapp/python/01-login.md
Labels: quickstart

#7517 Update b2c-operations.md
  articles/architecture-scenarios/implementation/b2c/b2c-operations.md
Labels: ready-for-review

#7384 Updates for 3.10.0 release
  articles/cms/wordpress/configuration.md
  articles/cms/wordpress/extending.md
  articles/cms/wordpress/jwt-authentication.md
  articles/cms/wordpress/troubleshoot.md
  articles/support/matrix.md
  media/articles/cms/wordpress/client-advanced-settings.png
Labels: ready-for-review

#7529 Tokens update work
  articles/api-auth/config/using-the-management-api.md
  articles/api-auth/tutorials/verify-access-token.md
  articles/api-auth/why-use-access-tokens-to-secure-apis.md
  articles/best-practices/rules.md
  articles/connections/database/custom-db/templates/index.md
  articles/connections/social/twitter.md
  articles/integrations/aws-api-gateway/custom-authorizers/index.md
  articles/integrations/aws-api-gateway/custom-authorizers/part-3.md
  articles/libraries/auth0-php/authentication-api.md
  articles/libraries/auth0-php/basic-use.md
  articles/migrations/guides/account-linking.md
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/migrations/guides/facebook-graph-api-deprecation.md
  articles/quickstart/backend/golang/01-authorization.md
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/spa/angular2/05-token-renewal.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/angularjs/05-token-renewal.md
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/05-token-renewal.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
  articles/quickstart/webapp/laravel/01-login.md
  articles/tokens/guides/access-token/get-access-tokens.md
  articles/tokens/guides/access-token/set-access-token-lifetime.md
  articles/tokens/guides/access-token/use-access-tokens.md
  articles/tokens/guides/id-token/get-id-tokens.md
  articles/tokens/guides/id-token/validate-id-token.md
  articles/tokens/id-token.md
  articles/tokens/jwt-claims.md
  articles/tokens/jwt.md
  articles/tokens/overview-access-tokens.md
  articles/tokens/reference/access-token/access-token-formats.md
  articles/tokens/refresh-token/current/index.md
  articles/troubleshoot/issues.md
  config/redirects.js
Labels: ready-for-review

#7531 Fixed word order in support/index.md
  articles/support/index.md
Labels: ready-for-review

#7515 Remove OIDC authentication introduction page
  articles/api-auth/intro.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#7533 Remove extra image
  articles/flows/concepts/auth-code-pkce.md
Labels: ready-for-review

#7520 Bumped Minimum version and updated the package name to match the QS solution
  articles/quickstart/native/react-native/00-login.md
  articles/quickstart/native/react-native/_includes/_config.md
  articles/quickstart/native/react-native/download.md
  articles/quickstart/native/react-native/index.yml
Labels: quickstart, ready-for-review

#7538 Update additional-configuration.md
  articles/custom-domains/additional-configuration.md
Labels: ready-for-review

#7542 Add note and fixed broken links
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/dashboard/index.md
  articles/logout/guides/logout-idps.md
  articles/logs/index.md
  articles/microsites/manage-users/define-maintain-custom-user-data.md
  articles/protocols/saml/adfs.md
  config/redirects.js
Labels: ready-for-review

#7543 Logout returnTo URL missing case
  articles/api/authentication/_logout.md
  articles/logout/guides/redirect-users-after-logout.md
Labels: ready-for-review

#7544 Update _userinfo.md
  articles/api/authentication/_userinfo.md
Labels: ready-for-review

#7545 Update user-profile-structure.md
  articles/users/references/user-profile-structure.md
Labels: ready-for-review

#7540 Add url encoded post params to example code
  articles/api-auth/tutorials/adoption/authorization-code.md
  articles/api-auth/tutorials/adoption/password.md
  articles/api-auth/tutorials/adoption/refresh-tokens.md
  articles/api-auth/tutorials/authorization-code-grant-pkce.md
  articles/api-auth/tutorials/authorization-code-grant.md
  articles/api-auth/tutorials/client-credentials.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/api-auth/tutorials/hybrid-flow.md
  articles/api-auth/tutorials/multifactor-resource-owner-password.md
  articles/api-auth/tutorials/password-grant.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
  articles/api/authentication/_multifactor-authentication.md
  articles/api/authentication/api-authz/_get-token.md
  articles/api/management/v1/index.md
  articles/api/management/v2/get-access-tokens-for-production.md
  articles/application-auth/current/mobile-desktop.md
  articles/application-auth/current/server-side-web.md
  articles/application-auth/legacy/server-side-web.md
  articles/architecture-scenarios/mobile-api/part-3.md
  articles/flows/guides/auth-code-pkce/includes/refresh-tokens.md
  articles/flows/guides/auth-code-pkce/includes/request-tokens.md
  articles/flows/guides/auth-code/includes/refresh-tokens.md
  articles/flows/guides/auth-code/includes/request-tokens.md
  articles/flows/guides/client-credentials/includes/request-token.md
  articles/flows/guides/implicit/includes/refresh-tokens.md
  articles/flows/guides/implicit/includes/request-tokens.md
  articles/multifactor-authentication/api/email.md
  articles/multifactor-authentication/api/manage.md
  articles/multifactor-authentication/api/oob.md
  articles/multifactor-authentication/api/otp.md
  articles/quickstart/backend/_includes/_api_using.md
  articles/tokens/guides/access-token/use-access-tokens.md
  articles/tokens/refresh-token/current/index.md
  articles/users/guides/impersonate-users-using-the-impersonation-api.md
Labels: ready-for-review

#7550 Removed useless table
  articles/cross-origin-authentication/index.md
Labels: ready-for-review

#7539 Added link to next tutorial from Vue.js Quickstart: 01-Login
  articles/quickstart/spa/vuejs/index.yml
Labels: quickstart

#7549 Update migrate-search-v2-v3.md
  articles/users/search/v3/migrate-search-v2-v3.md
Labels: ready-for-review
