Repository auth0/docs, pull requests merged in 2019-10, with the labels that each got.

#8285 Removed SDK installation instructions from React quickstart intro
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#8303 Fix security from stray revert
  articles/security/bulletins/2019-09-05_scopes.md
  articles/security/bulletins/index.md
  articles/security/store-tokens.md
Labels: ready-for-review, small

#8294 Fix arch scenarios from stray revert
  articles/architecture-scenarios/server-api/part-2.md
  articles/architecture-scenarios/server-api/part-3.md
Labels: ready-for-review, small

#8292 Fixes /api/info page from stray revert
  articles/api/info.md
Labels: ready-for-review, small

#8295 Fix authz typo after stray revert
  articles/authorization/concepts/core-vs-extension.md
Labels: ready-for-review, tiny

#8298 Fix ADFS connection powershell changes after stray revert
  articles/connections/enterprise/adfs.md
Labels: ready-for-review, small

#8299 Fix dev keys from stray revert
  articles/connections/social/devkeys.md
  articles/custom-domains/additional-configuration.md
  articles/dashboard/guides/applications/enable-sso-app.md
Labels: ready-for-review, small

#8300 Fix design typo from stray revert
  articles/design/using-auth0-with-multi-tenant-apps.md
Labels: ready-for-review, tiny

#8302 Fix device-auth limitations from stray revert
  articles/flows/guides/device-auth/includes/index.md
  articles/flows/guides/device-auth/includes/troubleshooting.md
Labels: ready-for-review, small

#8301 Fix batch size include + typos for extensions from stray revert
  articles/extensions/_includes/_batch-size.md
  articles/extensions/application-insight.md
  articles/extensions/azure-blob-storage.md
  articles/extensions/cloudwatch.md
  articles/extensions/deploy-cli/guides/incorporate-deploy-cli-into-build-environment.md
  articles/extensions/deploy-cli/references/environment-variables-keyword-mappings.md
  articles/extensions/logentries.md
  articles/extensions/loggly.md
  articles/extensions/logstash.md
  articles/extensions/mixpanel.md
  articles/extensions/papertrail.md
  articles/extensions/segment.md
  articles/extensions/splunk.md
  articles/extensions/sumologic.md
Labels: medium, ready-for-review

#8304 Fix libraries from stray revert
  articles/libraries/auth0-spa-js/index.md
  articles/libraries/lock/v11/api.md
Labels: ready-for-review, small

#8305 Fix SPA auth with cookies from stray revert
  articles/login/spa/authenticate-with-cookies.md
  articles/security/store-tokens.md
Labels: ready-for-review, small

#8308 Fix users from stray revert
  articles/users/concepts/overview-user-migration.md
  articles/users/guides/block-and-unblock-users.md
  articles/users/guides/bulk-user-exports.md
  articles/users/guides/bulk-user-imports.md
Labels: ready-for-review, small

#8297 Fix GDPR changes after stray revert
  articles/compliance/gdpr/features-aiding-compliance/user-consent/_redirect.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/webtask-redirect.md
Labels: medium, ready-for-review

#8307 Fix random additions logout through UL from stray revert
  articles/logout/index.md
  articles/logs/migrate-logs-v2-v3.md
  articles/policies/index.md
  articles/policies/rate-limits.md
  articles/policies/unsupported-requests.md
  articles/support/matrix.md
  articles/tokens/jwt-claims.md
  articles/universal-login/new-experience-limitations.md
  config/redirects.js
Labels: medium, ready-for-review

#8296 Fix rules screenshots after stray revert
  articles/dashboard/guides/rules/configure-variables.md
  articles/dashboard/guides/rules/create-rules.md
Labels: ready-for-review, tiny

#8309 Add missing images/var from stray revert
  articles/login/spa/authenticate-with-cookies.md
  config/vars.yml
  media/articles/login/spa/image1.png
  media/articles/login/spa/image2.png
  media/articles/login/spa/image3.png
  media/articles/login/spa/image4.png
  media/articles/login/spa/image5.png
  media/articles/login/spa/image6.png
  media/articles/login/spa/image7.png
  media/articles/login/spa/image8.png
  media/articles/login/spa/image9.png
Labels: ready-for-review, small

#8310 Fix quickstarts from stray revert
  articles/quickstart/backend/java-spring-security5/01-authorization.md
  articles/quickstart/native/android/00-login.md
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/_includes/_login.md
  articles/quickstart/native/android/download.md
  articles/quickstart/native/cordova/01-login.md
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
  articles/quickstart/native/ios-objc/download.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_product_bundle_note.md
  articles/quickstart/native/ios-swift/download.md
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/python/01-login.md
  articles/quickstart/webapp/rails/01-login.md
  articles/quickstart/webapp/rails/02-session-handling.md
Labels: large, ready-for-review

#8311 Fix rules (non-guides) from stray revert
  articles/rules/guides/redirect.md
  articles/rules/index.md
  articles/rules/references/user-object.md
Labels: ready-for-review, small

#8312 Fix rules (guides) from stray revert
  articles/api/management/guides/rules/create-rules.md
  config/redirects.js
Labels: ready-for-review, tiny

#8314 Fix passwordless from stray revert
  articles/connections/passwordless/_old/_includes/_setup-email.md
  articles/connections/passwordless/guides/configure-login-page-embedded.md
  articles/connections/passwordless/guides/implement-passwordless.md
  articles/connections/passwordless/guides/use-sms-gateway-passwordless.md
  articles/connections/passwordless/index.md
  articles/connections/passwordless/reference/troubleshoot.md
  articles/dashboard/guides/applications/set-up-cors.md
  config/redirects.js
Labels: medium, ready-for-review

#8315 fix link from SIWA quickstart to native app config docs
  articles/quickstart/native/ios-swift-siwa/00-login.md
Labels: bug

#8289 Minor updates, replacing default example of login, feedback addressed
  articles/libraries/auth0-spa-js/index.md
  articles/libraries/auth0-spa-js/migrate-from-auth0js.md
Labels: ready-for-review

#8317 Remove misleading note on enterprise rate limits
  articles/policies/rate-limits.md
Labels: ready-for-review, tiny

#8318 Update oauth/ro deprecation wording
  articles/migrations/guides/migration-oauthro-oauthtoken.md
Labels: ready-for-review, tiny

#8316 Update Invite-Only Applications email verification section
  articles/design/creating-invite-only-applications.md
Labels: ready-for-review, small

#8326 Update dashboard connections screenshots
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/overview-custom-db-connections.md
  articles/connections/database/index.md
  articles/users/guides/configure-automatic-migration.md
  articles/users/references/user-migration-scenarios.md
  media/articles/connections/database/custom-database.png
  media/articles/connections/database/import-scripts.png
  media/articles/connections/database/import-users.png
  media/articles/connections/database/migrated-users.png
  media/articles/dashboard/connections/database/connections-db-create.png
  media/articles/dashboard/connections/database/connections-db-list.png
  media/articles/dashboard/connections/database/connections-db-settings-apps.png
  media/articles/dashboard/connections/database/connections-db-settings-custom-1.png
  media/articles/dashboard/connections/database/connections-db-settings-custom-2.png
  media/articles/dashboard/connections/database/connections-db-settings-main-1.png
  media/articles/dashboard/connections/database/connections-db-settings-main-2.png
  media/articles/dashboard/connections/database/connections-db-settings-passwordpolicy-1.png
  media/articles/dashboard/connections/database/connections-db-settings-passwordpolicy-2.png
  media/articles/dashboard/users-roles/users-list.png
Labels: ready-for-review, small

#8329 Update using-auth0-to-secure-a-cli.md
  articles/integrations/using-auth0-to-secure-a-cli.md
Labels: ready-for-review

#8323 Minor updates to aws custom authorizers tutorial
  articles/integrations/aws-api-gateway/custom-authorizers/part-3.md
Labels: ready-for-review

#8332 Remove outdated screenshot
  articles/extensions/user-import-export.md
Labels: ready-for-review

#8243 Update logout Ionic 3 quickstart
  articles/quickstart/native/ionic3/01-login.md
  articles/quickstart/native/ionic3/index.yml
Labels: quickstart

#8113 Adding Identity Labs
  articles/identity-labs/01-web-sign-in/exercise-01.md
  articles/identity-labs/01-web-sign-in/exercise-02.md
  articles/identity-labs/01-web-sign-in/index.md
  articles/identity-labs/02-calling-an-api/exercise-01.md
  articles/identity-labs/02-calling-an-api/exercise-02.md
  articles/identity-labs/02-calling-an-api/exercise-03.md
  articles/identity-labs/02-calling-an-api/index.md
  articles/identity-labs/03-mobile-native-app/exercise-01.md
  articles/identity-labs/03-mobile-native-app/exercise-02.md
  articles/identity-labs/03-mobile-native-app/exercise-03.md
  articles/identity-labs/03-mobile-native-app/index.md
  articles/identity-labs/04-single-page-app/exercise-01.md
  articles/identity-labs/04-single-page-app/exercise-02.md
  articles/identity-labs/04-single-page-app/index.md
  articles/identity-labs/_includes/first-page-of-lab-note.md
  articles/identity-labs/_includes/git-clone-note.md
  articles/identity-labs/_includes/what-you-need.md
  articles/identity-labs/index.md
  articles/videos/index.md
  articles/videos/learn-identity/03-web-sign-in.md
  articles/videos/learn-identity/04-calling-an-api.md
  articles/videos/learn-identity/05-desktop-and-mobile-apps.md
  articles/videos/learn-identity/06-single-page-apps.md
  config/sections.yml
  config/sidebar.yml
  media/articles/identity-labs/lab-01-callback-url-config.png
  media/articles/identity-labs/lab-01-id-token-in-jwt-io.png
  media/articles/identity-labs/lab-01-logout-url-config.png
  media/articles/identity-labs/lab-01-network-trace-01.png
  media/articles/identity-labs/lab-01-network-trace-02.png
  media/articles/identity-labs/lab-01-network-trace-03.png
  media/articles/identity-labs/lab-01-network-trace-04.png
  media/articles/identity-labs/lab-01-starter-app-rendered.png
  media/articles/identity-labs/lab-02-api-allow-offline.png
  media/articles/identity-labs/lab-02-api-consent-initial.png
  media/articles/identity-labs/lab-02-api-token-expiration.png
  media/articles/identity-labs/lab-02-client-secret-config.png
  media/articles/identity-labs/lab-02-starter-app-rendered.png
  media/articles/identity-labs/lab-03-access-token-audience.png
  media/articles/identity-labs/lab-03-allow-offline-access.png
  media/articles/identity-labs/lab-03-call-api-button.png
  media/articles/identity-labs/lab-03-call-api-debug-area.png
  media/articles/identity-labs/lab-03-choose-device-and-run.png
  media/articles/identity-labs/lab-03-first-debug-area.png
  media/articles/identity-labs/lab-03-first-run.png
  media/articles/identity-labs/lab-03-login-confirmation.png
  media/articles/identity-labs/lab-03-plist.png
  media/articles/identity-labs/lab-03-project-settings-info-tab.png
  media/articles/identity-labs/lab-03-refresh-token-button.png
  media/articles/identity-labs/lab-04-consent-link-showing.png
  media/articles/identity-labs/lab-04-consent-prompt.png
  media/articles/identity-labs/lab-04-expenses-data-showing.png
  media/articles/identity-labs/lab-04-expenses-link-showing.png
  media/articles/identity-labs/lab-04-initial-load.png
  media/articles/identity-labs/lab-04-login-button-showing.png
  media/articles/identity-labs/lab-04-login-complete.png
  media/articles/identity-labs/lab-04-revoke-app.png
  media/articles/identity-labs/lab-04-silent-auth-request.png
  media/articles/identity-labs/lab-04-token-ep-post.png
  media/articles/identity-labs/lab-04-token-ep-response.png
Labels: in-review

#8342 Update logout Windows Universal App quickstart
  articles/quickstart/native/windows-uwp-csharp/01-login.md
  articles/quickstart/native/windows-uwp-csharp/download.md
Labels: quickstart

#8337 Fix screenshot
  media/articles/hosted-pages/consent-dialog.png
Labels: ready-for-review

#8343 Add doc on working with Private Cloud zones
  articles/private-cloud/index.md
  articles/private-cloud/managed-private-cloud/zones.md
  config/sidebar.yml
  media/articles/private-cloud/zones/zones-1.png
  media/articles/private-cloud/zones/zones-2.png
  media/articles/private-cloud/zones/zones-3.png
  media/articles/private-cloud/zones/zones-4.png
  media/articles/private-cloud/zones/zones-5.png
  media/articles/private-cloud/zones/zones-6.png
  media/articles/private-cloud/zones/zones-7.png
Labels: ready-for-review

#8349 Add info about global limits
  articles/policies/rate-limits.md
Labels: ready-for-review

#8351 Update default-login-url.md
  articles/universal-login/default-login-url.md
Labels: ready-for-review

#8345 [spa-js] Add info on how to access the raw id_token
  articles/libraries/auth0-spa-js/index.md
Labels: quickstart

#8063 Add Ionic 4 quickstart
  articles/quickstart/native/ionic4/01-login.md
  articles/quickstart/native/ionic4/download.md
  articles/quickstart/native/ionic4/index.yml
Labels: quickstart

#8348 Update react-native quickstarts
  articles/quickstart/native/react-native/00-login.md
  articles/quickstart/native/react-native/_includes/_config.md
  articles/quickstart/native/react-native/_includes/_install.md
  articles/quickstart/native/react-native/_includes/_intro.md
  articles/quickstart/native/react-native/_includes/_login.md
  articles/quickstart/native/react-native/download.md
  articles/quickstart/native/react-native/index.yml
  snippets/native-platforms/reactnative/setup.md
  snippets/native-platforms/reactnative/use.md
Labels: medium, quickstart

#8365 Update Professional Services packages
  articles/services/index.md
  media/articles/services/Auth0-Services-Advanced.pdf
  media/articles/services/Auth0-Services-Basic.pdf
  media/articles/services/Auth0-Services-Custom-Implementation.pdf
  media/articles/services/Auth0-Services-Discovery-Workshop.pdf
  media/articles/services/Auth0-Services-HealthCheck.pdf
  media/articles/services/Auth0-Services-Premier-Success.pdf
  media/articles/services/Auth0-Services-Standard.pdf
Labels: ready-for-review, small

#8357 Update logout [QS-95]
  articles/quickstart/webapp/golang/01-login.md
Labels: quickstart

#8359 Fix PHP dep for Laravel; remove unused Laravel snippets
  articles/quickstart/backend/laravel/index.yml
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/laravel/index.yml
  snippets/server-apis/php-laravel/dependencies.md
  snippets/server-apis/php-laravel/setup.md
  snippets/server-apis/php-laravel/use.md
  snippets/server-platforms/laravel/dependencies.md
  snippets/server-platforms/laravel/setup.md
  snippets/server-platforms/laravel/use.md
Labels: quickstart, tiny

#8367 Update doc
  articles/extensions/application-insight.md
  media/articles/extensions/appinsights/appinsights-properties.png
  media/articles/extensions/appinsights/conf-appinsights.png
  media/articles/extensions/appinsights/ext-mgmt-appinsights.png
  media/articles/extensions/appinsights/new-appinsights.png
  media/articles/extensions/appinsights/view-cron-details.png
  media/articles/extensions/appinsights/view-cron-jobs.png
Labels: ready-for-review

#8360 Update CODEOWNERS
  .github/CODEOWNERS
Labels: [Goalie] Review Required, tiny

#8354 Update index.md
  articles/custom-domains/index.md
Labels: ready-for-review

#8341 Update download instructions Ionic 3 quickstart
  articles/quickstart/native/ionic3/download.md
Labels: quickstart

#8373 Word misspelling correction on React SPA Quickstart
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart, tiny

#8376 SPA AngularJS Quickstart | Incorrect name/spelling of a directory
  articles/quickstart/spa/angularjs/_includes/_centralized_login.md
Labels: quickstart, tiny

#8352 Update 01-login.md
  articles/quickstart/webapp/python/01-login.md
Labels: [Goalie] Review Required, quickstart, tiny

#8381 Aws values
  articles/integrations/aws/sso.md
Labels: ready-for-review, tiny

#8379 Add a note about creating APIs before using
  articles/authorization/_includes/_predefine-permissions.md
Labels: ready-for-review, tiny

#8355 NodeJS EA QS
  articles/_includes/_new_app.md
  articles/quickstart/webapp/nodejs-ea/01-login.md
  articles/quickstart/webapp/nodejs-ea/download.md
  articles/quickstart/webapp/nodejs-ea/index.yml
Labels: quickstart

#8389 Added tracking data to PDF and XLSX links
  articles/architecture-scenarios/_includes/_implementation-checklists.md
  articles/architecture-scenarios/_includes/_planning.md
  articles/architecture-scenarios/b2b.md
Labels: ready-for-review, tiny

#8383 Updated redirect guidance
  articles/architecture-scenarios/_includes/_authentication/_application-integration.md
  articles/protocols/oauth2/redirect-users.md
  articles/users/guides/redirect-users-after-login.md
Labels: ready-for-review, small

#8366 Update ping7.md
  articles/protocols/saml/identity-providers/ping7.md
  media/articles/saml/identity-providers/ping7/ping-1.png
  media/articles/saml/identity-providers/ping7/ping-10.png
  media/articles/saml/identity-providers/ping7/ping-11.png
  media/articles/saml/identity-providers/ping7/ping-12.png
  media/articles/saml/identity-providers/ping7/ping-13.png
  media/articles/saml/identity-providers/ping7/ping-14.png
  media/articles/saml/identity-providers/ping7/ping-15.png
  media/articles/saml/identity-providers/ping7/ping-16.png
  media/articles/saml/identity-providers/ping7/ping-17.png
  media/articles/saml/identity-providers/ping7/ping-18.png
  media/articles/saml/identity-providers/ping7/ping-19.png
  media/articles/saml/identity-providers/ping7/ping-2.png
  media/articles/saml/identity-providers/ping7/ping-3.png
  media/articles/saml/identity-providers/ping7/ping-4.png
  media/articles/saml/identity-providers/ping7/ping-5.png
  media/articles/saml/identity-providers/ping7/ping-6.png
  media/articles/saml/identity-providers/ping7/ping-7.png
  media/articles/saml/identity-providers/ping7/ping-8.png
  media/articles/saml/identity-providers/ping7/ping-9.png
Labels: ready-for-review, small

#8390 Remove screenshots
  articles/connections/social/google.md
Labels: ready-for-review, tiny

#8330 Fix Rails WebApp QS logout by adding reset_session
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart, tiny

#7757 Fix TypeError in private-scoped endpoint
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart

#8395 Update install-other-platforms.md
  articles/connector/install-other-platforms.md
Labels: ready-for-review, tiny

#8396 Update 00-login.md
  articles/quickstart/native/react-native/00-login.md
Labels: [Goalie] Review Required, quickstart, tiny

#8393 Update 01-login.md
  articles/quickstart/webapp/laravel/01-login.md
Labels: [Goalie] Review Required, quickstart, tiny

#8362 Updating content and screenshot
  articles/connections/apple-siwa/add-siwa-to-native-app.md
  articles/connections/apple-siwa/add-siwa-to-web-app.md
  articles/connections/apple-siwa/set-up-apple.md
  articles/connections/social/apple.md
  config/redirects.js
  media/articles/connections/social/apple/apple-configurls2.png
Labels: ready-for-review

#8394 NodejsEA -> Express Webapp
  articles/quickstart/webapp/express/01-login.md
  articles/quickstart/webapp/express/download.md
  articles/quickstart/webapp/express/index.yml
Labels: quickstart

#7093 Change python-jose-cryptodome to python-jose
  articles/quickstart/backend/python/01-authorization.md
Labels: quickstart

#8400 Add file paths to code snippets
  articles/quickstart/native/cordova/01-login.md
  snippets/native-platforms/cordova/use.md
Labels: [Goalie] Review Required, quickstart, tiny

#8401 Fix broken passwordless and anomaly detection links
  articles/anomaly-detection/references/brute-force-protection-triggers-actions.md
  articles/api/authentication/_passwordless.md
  articles/api/authentication/legacy/_login.md
  articles/link-accounts/user-initiated-linking.md
  config/redirects.js
Labels: medium, ready-for-review

#6795 Update 01-authorization.md
  articles/quickstart/backend/golang/01-authorization.md
Labels: quickstart, ready-for-review, verified

#8399 Added amr definition and link
  articles/multifactor-authentication/step-up-authentication/step-up-for-apis.md
  articles/multifactor-authentication/step-up-authentication/step-up-for-web-apps.md
Labels: medium, ready-for-review

#8402 Update install-deploy-cli.md
  articles/extensions/deploy-cli/guides/install-deploy-cli.md
  articles/extensions/index.md
  media/articles/extensions/deploy-cli/deploy-cli-app-list.png
  media/articles/extensions/deploy-cli/deploy-cli-enable-permissions.png
  media/articles/extensions/deploy-cli/deploy-cli-find-extension.png
  media/articles/extensions/deploy-cli/deploy-cli-install-extension.png
  media/articles/extensions/deploy-cli/step1-extensions-overview.png
  media/articles/extensions/deploy-cli/step2-extension-link.png
  media/articles/extensions/deploy-cli/step3-auth0-deploy-cli-homepage.png
Labels: medium, ready-for-review

#8403 Added note about parental consent
  articles/_includes/_parental-consent.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock.md
  articles/scopes/current/guides/customize-consent-prompt.md
Labels: ready-for-review, small

#8413 Remove root profile attributes sentence as is no longer relevant
  articles/api/management/guides/users/set-root-attributes-user-signup.md
Labels: tiny

#8410 Address claim for OIDC is a JSON Object
  articles/users/normalized/oidc/index.md
Labels: ready-for-review, tiny

#8412 updated documentation for passwordless connections in hooks
  articles/hooks/concepts/post-user-registration-extensibility-point.md
  articles/hooks/concepts/pre-user-registration-extensibility-point.md
  articles/hooks/guides/use-the-post-user-registration-extensibility-point.md
  articles/hooks/guides/use-the-pre-user-registration-extensibility-point.md
  articles/hooks/index.md
  updates/2019-10-24.yml
Labels: medium, ready-for-review

#8415 Private Cloud Tenant Logs Search Warning
  articles/logs/index.md
Labels: ready-for-review, small

#8409 Update token-best-practices.md
  articles/tokens/concepts/token-best-practices.md
Labels: ready-for-review, tiny

#8411 Added more info to invalid state troubleshooting
  articles/cms/wordpress/invalid-state.md
Labels: ready-for-review, tiny

#8414 Moved note about SPAs and refresh tokens
  articles/api-auth/which-oauth-flow-to-use.md
  articles/flows/concepts/implicit.md
Labels: ready-for-review, tiny

#8416 Rework Analytics
  articles/analytics/_includes/_install.md
  articles/analytics/_includes/_usage.md
  articles/analytics/guides/facebook-analytics.md
  articles/analytics/guides/google-analytics.md
  articles/analytics/index.md
  articles/analytics/integrations/facebook-analytics/index.md
  articles/analytics/integrations/google-analytics/index.md
  articles/analytics/integrations/index.md
  articles/extend-integrate/index.md
  articles/integrations/index.md
  articles/monitoring/guides/monitor-applications.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small

#8421 Update Reset Tenants doc
  articles/support/_delete-tenant.md
  articles/support/_reset-tenant.md
  articles/support/delete-reset-tenant.md
Labels: medium, ready-for-review

#8425 Add missing parentheses
  articles/dashboard/reference/settings-application.md
Labels: ready-for-review, tiny

#8428 Clarify how to configure custom domains with auth0-spa-js
  articles/custom-domains/additional-configuration.md
Labels: ready-for-review, tiny

#8430 Update app-types-first-third-party.md
  articles/applications/concepts/app-types-first-third-party.md
Labels: ready-for-review, tiny

#8424 Update sample-use-cases.md
  articles/scopes/current/sample-use-cases.md
Labels: ready-for-review, tiny

#8423 Update sidebar.yml
  config/sidebar.yml
Labels: ready-for-review, tiny

#8417 Update how-auth0-versions-software.md
  articles/support/how-auth0-versions-software.md
Labels: ready-for-review, tiny

#8418 Disambiguate "token" usage in JS Quickstart
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart, tiny

#8436 Update Spring MVC Security Quickstart to use RS256
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
Labels: quickstart, small

#8408 Add doc on Managed PC deployment diffs and customer-hosted RACI
  articles/private-cloud/managed-private-cloud/raci.md
Labels: medium, ready-for-review

#8438 Code Yellow - Add Talk to Sales CTA
  articles/api/authentication/index.md
  articles/tokens/refresh-token/current/index.md
Labels: ready-for-review

#8435 Update Yahoo connections doc
  articles/connections/social/yahoo.md
  media/articles/connections/social/yahoo/api-permissions.png
  media/articles/connections/social/yahoo/client-id-and-secret.png
  media/articles/connections/social/yahoo/create-an-app.png
  media/articles/connections/social/yahoo/enter-fields.png
Labels: ready-for-review, small

#8447 Fix broken link to API scopes doc
  articles/dashboard/reference/views-api.md
Labels: ready-for-review, tiny

#8448 Revert "Update install-other-platforms.md"
  articles/connector/install-other-platforms.md
Labels: ready-for-review, tiny

#8454 Native SIWA: Enable the connection for the application
  articles/connections/apple-siwa/add-siwa-to-native-app.md
Labels: ready-for-review, tiny
