Repository auth0/docs, pull requests merged in 2019-09, with the labels that each got.

#8181 Android QS: Clarify source of variable value
  articles/quickstart/native/android/06-calling-apis.md
Labels: quickstart, tiny

#8173 Added fix for QS-291
  articles/quickstart/backend/falcor/download.md
Labels: quickstart

#8164 Update Rails QS for CSRF troubleshooting
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart, tiny

#8192 Clarifying remember last login option
  articles/libraries/lock/v11/configuration.md
Labels: ready-for-review, small

#8194 Added recommended to the Allowed Web Origins note for auth0-spa-js include
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/angular2/01-login.md
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/vanillajs/01-login.md
  articles/quickstart/spa/vuejs/01-login.md
Labels: quickstart

#8186 Remove extra comma
  articles/api-auth/which-oauth-flow-to-use.md
Labels: ready-for-review, tiny

#8185 Fix link to screenshot
  articles/users/guides/azure-access-control.md
Labels: ready-for-review, tiny

#8187 Fix typo
  articles/email/templates.md
Labels: ready-for-review, tiny

#8195 Update import-export-directory-structure.md
  articles/extensions/deploy-cli/guides/import-export-directory-structure.md
Labels: ready-for-review, tiny

#8196 Update import-export-yaml-file.md
  articles/extensions/deploy-cli/guides/import-export-yaml-file.md
Labels: ready-for-review, tiny

#8197 Update templates.md
  articles/email/templates.md
Labels: ready-for-review, tiny

#8199 Update custom-domain-migration.md
  articles/private-cloud/custom-domain-migration.md
Labels: ready-for-review, tiny

#8200 Fix typo
  articles/protocols/ws-fed/index.md
Labels: ready-for-review, tiny

#8202 Add custom domain usage.
  articles/extensions/account-link.md
Labels: ready-for-review

#8204 Remove indication that user profile caches with database connections can be deleted
  articles/users/guides/update-user-profiles-using-your-database.md
Labels: ready-for-review, tiny

#8206 Adding a note about Firefox
  articles/cross-origin-authentication/index.md
Labels: ready-for-review, tiny

#8121 New doc: Configure Passwordless Connections
  articles/dashboard/guides/connections/_includes/_control-sign-ups.md
  articles/dashboard/guides/connections/_includes/_enable-apps.md
  articles/dashboard/guides/connections/_includes/_otp-settings.md
  articles/dashboard/guides/connections/configure-passwordless-email.md
  articles/dashboard/guides/connections/configure-passwordless-sms.md
  media/articles/connections/passwordless/connections-passwordless-email.png
Labels: in-review, medium, ready-for-review

#8144 Adding doc for use case(s) for rules and passwordless
  articles/connections/passwordless/use-case-rules.md
Labels: in-review, ready-for-review

#8147 Create start of passwordless troubleshoot guide
  articles/connections/passwordless/troubleshoot.md
  articles/connections/passwordless/user-guide.md
Labels: do-not-merge, medium

#8157 Add doc on relevant API endpoints for Passwordless
  articles/connections/passwordless/relevant-api-endpoints.md
Labels: in-review, ready-for-review

#8169 Add doc on SSO API endpoints
  articles/sso/current/relevant-api-endpoints.md
Labels: in-review, ready-for-review

#8174 Terminology Update: Changing CSM -> TAM
  articles/appliance/critical-issue.md
  articles/appliance/dashboard/updates.md
  articles/appliance/disaster-recovery-raci.md
  articles/appliance/disaster-recovery.md
  articles/appliance/geo-ha/disaster-recovery.md
  articles/dev-lifecycle/child-tenants.md
  articles/onboarding/appliance-sprint.md
  articles/onboarding/enterprise-support.md
  articles/support/_delete-tenant.md
  articles/support/tickets.md
Labels: ready-for-review, small

#8175 Configure SSO Integrations
  articles/integrations/sso/_template.md
  articles/integrations/sso/index.md
  articles/integrations/sso/sentry.md
  media/articles/sso/integrations/sentry.png
Labels: in-review, ready-for-review

#8158 Rework SSO Dashboard Extension
  articles/dashboard/guides/extensions/sso-dashboard-add-apps.md
  articles/dashboard/guides/extensions/sso-dashboard-create-app.md
  articles/dashboard/guides/extensions/sso-dashboard-install-extension.md
  articles/dashboard/guides/extensions/sso-dashboard-update-apps.md
  articles/extensions/sso-dashboard.md
  articles/extensions/troubleshoot.md
  media/articles/extensions/sso-dashboard/change-settings.png
  media/articles/extensions/sso-dashboard/new-app.png
Labels: in-review, medium

#8149 Configure embedded login (lock v11) with passwordless
  articles/connections/passwordless/configure-login-page.md
Labels: do-not-merge

#8210 Fix android QS snippet
  articles/quickstart/native/android/06-calling-apis.md
Labels: quickstart, tiny

#8128 Doc Update: Using custom SMS Gateways
  articles/connections/passwordless/sms-gateway.md
  articles/dashboard/guides/connections/sms-gateway.md
Labels: in-review, medium, ready-for-review

#8211 Replaced screenshots
  media/articles/email/providers/enter-keys.png
  media/articles/email/providers/enter-smtp-data.png
  media/articles/email/providers/mandrill-key.png
  media/articles/email/providers/sendgrid-dashboard.png
  media/articles/email/providers/sparkpost-set-key.png
Labels: ready-for-review, tiny

#8203 Update device flow limitations
  articles/flows/guides/device-auth/includes/index.md
  articles/flows/guides/device-auth/includes/troubleshooting.md
Labels: ready-for-review, tiny

#8198 wip: create intro to sso, inbound intro, outbound intro
  articles/sso/current/inbound.md
  articles/sso/current/intro.md
  articles/sso/current/outbound.md
Labels: do-not-merge

#8208 Updated Angular2 quickstart code samples
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart

#8183 Update Django webapp article
  articles/quickstart/webapp/django/01-login.md
Labels: quickstart, small

#8218 Update python-webapp QS requested scope
  articles/quickstart/webapp/python/01-login.md
Labels: quickstart, tiny

#8205 Adding Auth0 Security Bulletin: Assigning Scopes Based on Email Address
  articles/security/bulletins/2019-09-05_scopes.md
  articles/security/bulletins/index.md
Labels: ready-for-review

#8224 Corrected casing on NavBar for consistency
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#8219 Add batch size notes to logging extension docs
  articles/extensions/_includes/_batch-size.md
  articles/extensions/application-insight.md
  articles/extensions/azure-blob-storage.md
  articles/extensions/cloudwatch.md
  articles/extensions/logentries.md
  articles/extensions/loggly.md
  articles/extensions/logstash.md
  articles/extensions/mixpanel.md
  articles/extensions/papertrail.md
  articles/extensions/segment.md
  articles/extensions/splunk.md
  articles/extensions/sumologic.md
Labels: medium, ready-for-review

#8221 Add note regarding exporting user metadata
  articles/users/guides/bulk-user-exports.md
Labels: ready-for-review, small

#8222 Add info on expiration and deletion times
  articles/users/guides/bulk-user-exports.md
  articles/users/guides/bulk-user-imports.md
Labels: ready-for-review, small

#8172 add spa authenticate with cookies guide
  articles/login/spa/authenticate-with-cookies.md
  articles/security/store-tokens.md
  media/articles/login/spa/image1.png
  media/articles/login/spa/image2.png
  media/articles/login/spa/image3.png
  media/articles/login/spa/image4.png
  media/articles/login/spa/image5.png
  media/articles/login/spa/image6.png
  media/articles/login/spa/image7.png
  media/articles/login/spa/image8.png
  media/articles/login/spa/image9.png
Labels: medium, ready-for-review

#8231 Update instructions on redirecting to user consent page
  articles/compliance/gdpr/features-aiding-compliance/user-consent/_redirect.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/webtask-redirect.md
Labels: medium, ready-for-review

#8237 Update 01-login.md
  articles/quickstart/webapp/django/01-login.md
Labels: quickstart

#8215 Update logout Android quickstart
  articles/quickstart/native/android/00-login.md
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/_includes/_login.md
  articles/quickstart/native/android/download.md
Labels: quickstart

#8188 Update logout URL with Laravel config
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart, tiny

#8240 QS-297 | Logout Guidance Obj-c
  articles/quickstart/native/ios-objc/_includes/_login_centralized.md
  articles/quickstart/native/ios-objc/download.md
Labels: quickstart, small

#8247 Refactored out links to auth0-spa-js in favour of variable
  articles/libraries/auth0-spa-js/index.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  config/vars.yml
Labels: tiny

#8249 ADFS Connection: Remove outdated screenshot, separate the powershell commands for setup
  articles/connections/enterprise/adfs.md
Labels: ready-for-review, small

#8235 Rules update
  articles/rules/index.md
  articles/rules/references/user-object.md
Labels: ready-for-review, small

#8261 Remove unnecessary dependency
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#8241 QS-298 | Fix Logout Guidance - Swift
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_product_bundle_note.md
  articles/quickstart/native/ios-swift/download.md
Labels: quickstart, small

#8264 Updates to API descriptions
  articles/api/info.md
Labels: ready-for-review, small

#8255 changed handleCallback to handleAuthentication in vue quickstart
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart

#8270 SSO links and nav
  articles/sessions/concepts/session-layers.md
  articles/sessions/references/example-short-lived-session-mgmt.md
  articles/sso/current/inbound.md
  articles/sso/current/index.md
  articles/sso/current/index_old.md
  articles/sso/current/intro.md
  articles/sso/current/outbound.md
  articles/sso/current/relevant-api-endpoints.md
  config/sidebar.yml
Labels: medium, ready-for-review

#8269 Add basic definition of JWT claim
  articles/tokens/jwt-claims.md
Labels: ready-for-review, small

#8268 Clarify context.accessToken.scope and fix link
  articles/rules/references/context-object.md
  articles/scopes/current/sample-use-cases.md
Labels: ready-for-review, small

#8191 Sign In With Apple Setup and Configuration
  articles/api/authentication/api-authz/_get-token.md
  articles/connections/apple-setup.md
  articles/connections/apple-siwa/add-siwa-to-native-app.md
  articles/connections/apple-siwa/add-siwa-to-web-app.md
  articles/connections/apple-siwa/set-up-apple.md
  articles/connections/apple-siwa/test-siwa-connection.md
  articles/connections/social/apple.md
  articles/policies/rate-limits.md
  media/articles/connections/social/apple/apple-2FA.png
  media/articles/connections/social/apple/apple-app-mobile-settings.png
  media/articles/connections/social/apple/apple-connection.png
  media/articles/connections/social/apple/apple-email-preferences.png
  media/articles/connections/social/apple/apple-login-page.png
  media/articles/connections/social/apple/apple-siwa-authn-flow.png
  media/articles/connections/social/apple/apple-siwa-setup-flow.png
  media/articles/connections/social/apple/apple_connection.png
  media/articles/connections/social/apple/native-apple-siwa-flow.png
Labels: medium, ready-for-review

#8217 Updating Vue Quickstart for auth0-spa-js
  articles/quickstart/spa/_includes/_calling_api_create_backend.md
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/vuejs/01-login.md
  articles/quickstart/spa/vuejs/02-calling-an-api.md
  articles/quickstart/spa/vuejs/03-calling-an-api.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/index.yml
Labels: large, quickstart

#8274 Update dashboard tenant settings reference
  articles/api-auth/tutorials/password-grant.md
  articles/architecture-scenarios/_includes/_branding/_introduction.md
  articles/architecture-scenarios/_includes/_logout/_introduction.md
  articles/best-practices/tenant-settings.md
  articles/configure/index.md
  articles/dashboard/dashboard-tenant-settings.md
  articles/dashboard/index.md
  articles/dashboard/reference/settings-api.md
  articles/dashboard/reference/settings-application.md
  articles/dashboard/reference/settings-tenant.md
  articles/getting-started/dashboard-overview.md
  articles/libraries/lock/v11/configuration.md
  articles/tokens/guides/access-token/get-access-tokens.md
  articles/universal-login/default-login-url.md
  config/redirects.js
  yarn-error.log
Labels: large, ready-for-review

#8276 Add Auth0 Overview to sidebar
  articles/getting-started/index.md
  articles/getting-started/overview.md
  config/sidebar.yml
Labels: ready-for-review, tiny

#8278 Update sidebar.yml to fix 4th level expansion issues
  config/sidebar.yml
Labels: ready-for-review, tiny

#8271 Update Papertrail docs
  articles/extensions/papertrail.md
  media/articles/extensions/papertrail/auth0-logs-at-papertrail-01.png
  media/articles/extensions/papertrail/auth0-logs-at-papertrail-02.png
  media/articles/extensions/papertrail/papertrail-existing-system.png
  media/articles/extensions/papertrail/papertrail-new-system-01.png
  media/articles/extensions/papertrail/papertrail-new-system-02.png
Labels: medium, ready-for-review

#8253 Securing Apigee with Auth0
  articles/integrations/apigee.md
Labels: large, ready-for-review

#8273 Fixed broken Connections > Exact page
  articles/connections/social/exact.md
  media/articles/connections/social/exact/exact-register-1.png
  media/articles/connections/social/exact/exact-register-2.png
  media/articles/connections/social/exact/exact-register-3.png
  media/articles/connections/social/exact/exact-register-4.png
  media/articles/connections/social/exact/exact-register-5.png
  media/articles/connections/social/exact/exact-register-6.png
Labels: ready-for-review, small

#8284 Removed short fragment syntax to fix highlight js
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#8244 Update Quickstart for Golang to allow using Go Modules
  articles/quickstart/webapp/golang/01-login.md
Labels: quickstart

#8282 Fix Connections index and nav
  articles/connections/identity-providers-enterprise.md
  articles/connections/identity-providers-legal.md
  articles/connections/identity-providers-social.md
  articles/connections/index.md
  articles/connections/pass-parameters-to-idps.md
  articles/connections/passwordless/index.md
  config/sidebar.yml
Labels: ready-for-review, small

#8286 Add legacy notes to SSO docs
  articles/applications/application-settings/_settings-pt2.md
  articles/connections/social/devkeys.md
  articles/dashboard/guides/applications/enable-sso-app.md
  articles/dashboard/reference/settings-application.md
  articles/hosted-pages/login/index.md
  articles/integrations/sso/_template.md
  articles/rules/_includes/_context-prop-sso.md
  articles/security/blacklisting-attributes.md
Labels: ready-for-review, small

#8283 Fix acronyms
  articles/getting-started/overview.md
Labels: ready-for-review, small

#8275 Add link to jwt claims to jwt structure doc
  articles/tokens/reference/jwt/jwt-structure.md
Labels: ready-for-review, tiny
