Repository auth0/docs, pull requests merged in 2020-02, with the labels that each got.

#8690 Update self-managed-certificates.md
  articles/custom-domains/self-managed-certificates.md
Labels: ready-for-review

#8691 Removing old Passwordless guidance
  articles/connections/passwordless/guides/use-sms-gateway-passwordless.md
  articles/dashboard/guides/connections/_includes/_passwordless/_choose_method.md
  articles/dashboard/guides/connections/_includes/_passwordless/_control-sign-ups.md
  articles/dashboard/guides/connections/_includes/_passwordless/_enable-apps.md
  articles/dashboard/guides/connections/_includes/_passwordless/_enter-auth-parameters.md
  articles/dashboard/guides/connections/_includes/_passwordless/_enter-message-text.md
  articles/dashboard/guides/connections/_includes/_passwordless/_message-language.md
  articles/dashboard/guides/connections/_includes/_passwordless/_message-syntax.md
  articles/dashboard/guides/connections/_includes/_passwordless/_otp-settings.md
  articles/dashboard/guides/connections/set-up-connections-passwordless.md
  articles/dashboard/guides/universal-login/configure-login-page-passwordless.md
  config/redirects.js
Labels: ready-for-review, small

#8697 typo in deployment models link
  articles/getting-started/overview.md
Labels: ready-for-review

#8702 Updated Reset Account Password page
  articles/connections/database/password-change.md
  articles/connections/database/password-strength.md
  articles/email/templates.md
  articles/pre-deployment/tests/recommended.md
  articles/support/reset-account-password.md
  articles/universal-login/advanced-customization.md
  articles/universal-login/password-reset.md
Labels: ready-for-review, small

#8719 Fix DAE broken anchor and link
  articles/extensions/delegated-admin/v3/index.md
Labels: ready-for-review, tiny

#8718 Typos in passwordless endpoint names
  articles/connections/passwordless/guides/embedded-login-native.md
  articles/connections/passwordless/guides/embedded-login-webapps.md
Labels: ready-for-review, tiny

#8717 Typo in SAP OData title
  articles/addons/sap-odata.md
Labels: ready-for-review, tiny

#8723 Credential Stuffing Attack Prevention Beta Doc
  articles/anomaly-detection/guides/prevent-credential-stuffing-attacks.md
  media/articles/anomaly-detection/captcha-login-screen.png
  media/articles/anomaly-detection/credential-stuffing-attack.png
Labels: ready-for-review, small

#8694 API Auth docs - Minor changes for consistency
  articles/api-auth/apis.md
  articles/api-auth/blacklists-vs-grants.md
  articles/api-auth/config/using-the-auth0-dashboard.md
  articles/api-auth/config/using-the-management-api.md
  articles/api-auth/dynamic-client-registration.md
  articles/api-auth/faq.md
  articles/api-auth/grant/authorization-code-pkce.md
  articles/api-auth/grant/authorization-code.md
  articles/api-auth/intro.md
  articles/api-auth/passwordless.md
  articles/api-auth/token-renewal-in-safari.md
  articles/api-auth/tutorials/adoption/_index.md
  articles/api-auth/tutorials/adoption/api-tokens.md
  articles/api-auth/tutorials/adoption/authorization-code.md
  articles/api-auth/tutorials/adoption/client-credentials.md
  articles/api-auth/tutorials/adoption/delegation.md
  articles/api-auth/tutorials/adoption/implicit.md
  articles/api-auth/tutorials/adoption/index.md
  articles/api-auth/tutorials/adoption/oidc-conformant.md
  articles/api-auth/tutorials/adoption/password.md
  articles/api-auth/tutorials/adoption/refresh-tokens.md
  articles/api-auth/tutorials/adoption/scope-custom-claims.md
  articles/api-auth/tutorials/adoption/single-sign-on.md
  articles/api-auth/tutorials/authorization-code-grant-pkce.md
  articles/api-auth/tutorials/authorization-code-grant.md
  articles/api-auth/tutorials/client-credentials.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/api-auth/tutorials/hybrid-flow.md
  articles/api-auth/tutorials/implicit-grant.md
  articles/api-auth/tutorials/multifactor-resource-owner-password.md
  articles/api-auth/tutorials/nonce.md
  articles/api-auth/tutorials/password-grant.md
  articles/api-auth/tutorials/represent-multiple-apis.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
  articles/api-auth/user-consent.md
Labels: medium, ready-for-review

#8726 Changed email address link
  articles/anomaly-detection/guides/prevent-credential-stuffing-attacks.md
Labels: ready-for-review, tiny

#8721 Update application delegate methods for Lock.swift
  articles/connections/passwordless/_old/ios-magic-link.md
  articles/libraries/lock-ios/v1/index.md
  articles/libraries/lock-ios/v1/use-your-own-ui.md
  articles/libraries/lock-ios/v2/migration.md
  articles/quickstart/native/react-native/00-login.md
Labels: small

#8729 Update Lock version for Credential Stuffing EA
  articles/anomaly-detection/guides/prevent-credential-stuffing-attacks.md
Labels: ready-for-review, tiny

#8732 Broken links
  articles/anomaly-detection/guides/prevent-credential-stuffing-attacks.md
Labels: ready-for-review

#8734 Update universal login password reset link
  articles/support/reset-account-password.md
Labels: ready-for-review, tiny

#8730 Breaking changes warning - Authz Ext
  articles/extensions/authorization-extension/v2/index.md
Labels: do-not-merge

#8735 Add changelog link to Authz breaking changes instructions
  articles/extensions/authorization-extension/v2/index.md
Labels: ready-for-review, tiny

#8738 Update warning on ip address changes
  articles/guides/ip-whitelist.md
Labels: ready-for-review, tiny

#8739 Clarify password changes with management api token for spa
  articles/api/management/v2/get-access-tokens-for-spas.md
Labels: ready-for-review, tiny

#8743 [QS-424] Added another bullet point point
  articles/quickstart/spa/_includes/_callback_component.md
Labels: quickstart, tiny

#8744 [QS-425] Replaced `innerHTML` with `textContent`
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
Labels: quickstart, tiny

#8742 Remove inconsistent line
  articles/api-auth/tutorials/password-grant.md
Labels: ready-for-review, tiny

#8741 Add app_metadata naming warning
  articles/rules/guides/metadata.md
Labels: ready-for-review, tiny

#8745 Updated Lock.swift documentation
  articles/libraries/lock-ios/v2/configuration.md
Labels: small

#8746 Update integrations index page
  articles/integrations/index.md
Labels: ready-for-review, small

#8736 Hooks support for Deploy CLI Tool
  articles/extensions/deploy-cli/_includes/_strip-option.md
  articles/extensions/deploy-cli/_includes/_upgrade-v4.md
  articles/extensions/deploy-cli/guides/call-deploy-cli-programmatically.md
  articles/extensions/deploy-cli/guides/create-deploy-cli-application-manually.md
  articles/extensions/deploy-cli/guides/import-export-directory-structure.md
  articles/extensions/deploy-cli/guides/import-export-yaml-file.md
  articles/extensions/deploy-cli/guides/install-deploy-cli.md
  articles/extensions/deploy-cli/index.md
  articles/extensions/deploy-cli/references/whats-new.md
  config/redirects.js
  config/sidebar.yml
Labels: medium, ready-for-review

#8750 Updated minimum Express version for Express webapp quickstart
  articles/quickstart/webapp/express/index.yml
Labels: quickstart

#8754 Update .NET Core 3.0 to .NET Core 3.1
  articles/quickstart/webapp/aspnet-core-3/index.yml
Labels: small

#8752 Update index.yml
  articles/quickstart/webapp/aspnet-core/index.yml
Labels: tiny

#8753 Add additional breaking change steps to Authz extension
  articles/extensions/authorization-extension/v2/index.md
Labels: ready-for-review, tiny

#8748 Update test-testall-endpoints.md
  articles/monitoring/guides/test-testall-endpoints.md
Labels: ready-for-review, small

#8757 Update QS to non-deprecated sample
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart, tiny

#8655 Update Progressive Profiling with new example
  articles/best-practices/rules.md
  articles/rules/guides/redirect.md
  articles/users/concepts/overview-progressive-profiling.md
  articles/users/guides/redirect-users-after-login.md
Labels: medium, ready-for-review

#8767 Updated the cross-origin sample to remove reassignment of auth0 object
  articles/cross-origin-authentication/index.md
Labels: tiny

#8759 Fix broken Dwolla developer portal link + add miiCard deprecation info
  articles/connections/social/dwolla.md
  articles/connections/social/miicard.md
Labels: ready-for-review, tiny

#8777 Updated custom domains setup screenshots
  articles/custom-domains/self-managed-certificates.md
  media/articles/custom-domains/custom-domains-self-managed.png
  media/articles/custom-domains/custom-domains.png
Labels: ready-for-review, tiny

#8776 Removed webtask info
  articles/connections/database/index.md
  articles/connector/scom-monitoring.md
  articles/integrations/aws-api-gateway/custom-authorizers/index.md
Labels: ready-for-review, tiny

#8775 Added note to user search
  articles/users/search/v3/query-syntax.md
Labels: ready-for-review, tiny

#8774 Added note to azure-blob-storage.md
  articles/extensions/azure-blob-storage.md
Labels: ready-for-review, tiny

#8773 Added note for token_endpoint_auth_method: none
  articles/api-auth/dynamic-client-registration.md
  articles/api/authentication/_application-reg.md
  articles/applications/reference/grant-types-auth0-mapping.md
Labels: ready-for-review, tiny

#8778 Added signed cookie warning
  articles/protocols/oauth2/oauth-state.md
Labels: ready-for-review, tiny

#8771 Take ownership of some community quickstarts
  articles/quickstart/native/cordova/index.yml
  articles/quickstart/native/windows-uwp-csharp/index.yml
  articles/quickstart/native/wpf-winforms/index.yml
  articles/quickstart/native/xamarin/index.yml
Labels: quickstart

#8772 Update support matrix
  articles/support/matrix.md
Labels: update-needed

#8780 Add forced logout warning
  articles/migrations/guides/_forced-logouts.md
  articles/migrations/guides/migration-oauthro-oauthtoken-pwdless.md
  articles/migrations/guides/migration-oauthro-oauthtoken.md
Labels: ready-for-review, tiny

#8779 [QS-436] Update router location on Vue.JS quickstart docs
  articles/quickstart/spa/vuejs/02-calling-an-api.md
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
  articles/quickstart/spa/vuejs/index.yml
Labels: quickstart

#8787 [QS-441] Fix typo in Angular QS code
  articles/quickstart/spa/angular2/_includes/_centralized_login.md
Labels: quickstart, tiny

#8789 Fixed broken link
  articles/applications/index.md
Labels: ready-for-review, tiny

#8790 HealthCheck Services Sales changes
  articles/services/packages.md
  media/articles/services/Auth0-Services-HealthCheck.pdf
Labels: ready-for-review, tiny

#8715 Remove advice for manual token gen using library
  articles/api/management/v2/tokens-flows.md
Labels: do-not-merge, in-review

#8765 Update API authorization for SDK v7.0
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/backend/php/index.yml
Labels: medium, quickstart

#8442 [DO-NOT-MERGE][IUM-641] Custom Password Hashes
  articles/users/_includes/_password-encoding-description.md
  articles/users/guides/bulk-user-imports.md
  articles/users/references/bulk-import-database-schema-examples.md
  articles/users/references/user-profile-structure.md
  package.json
  updates/2019-10-30.yml
Labels: do-not-merge, ready-for-review

#8791 Remove webtask references
  articles/compliance/gdpr/features-aiding-compliance/user-consent/webtask-redirect.md
  articles/integrations/aws-api-gateway/delegation/index.md
  articles/rules/references/legacy.md
  articles/support/removing-auth0-exporting-data.md
Labels: ready-for-review, tiny
