Repository auth0/docs, pull requests merged in 2020-08, with the labels that each got.

#9350 CMS launch cleanup for files left on production
  articles/api/authentication/_userinfo.md
  articles/architecture-scenarios/_includes/_authorization/_api-integration.md
  articles/architecture-scenarios/_includes/_operations/_notifications.md
Labels: ready-for-review

#9352 Remove webtask redirect doc
  articles/compliance/gdpr/features-aiding-compliance/user-consent/_redirect.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/webtask-redirect.md
Labels: ready-for-review

#9357 Removed archived doc from sidebar, fixed redirect chains, 404s
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9285 [DO NOT MERGE] Contentful Launch, Attempt 2
  articles/api/authentication/legacy/_impersonation.md
  articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
  articles/architecture-scenarios/web-app-sso/part-2.md
  articles/connections/calling-an-external-idp-api.md
  articles/connections/database/custom-db/index.md
  articles/integrations/azure-api-management/configure-auth0.md
  articles/libraries/lock/v11/index.md
  articles/users/search/v2/query-syntax.md
  config/cards.yml
  config/included-folders.yml
  config/redirects.js
  config/redirectsarchive.js
  config/sections.yml
  config/sidebar.yml
  prebuild.sh
  updates/2016-06-10.yml
Labels: do-not-merge

#9363 Azure AD connection link add info on removing unverified label
  articles/connections/_find-auth0-domain-redirects.md
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review, small

#9375 Update Get started sidebar links
  config/sidebar.yml
Labels: ready-for-review

#9377 Update services sidebar and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9368 [SDK-1881] New Angular quickstart
  articles/quickstart/spa/_includes/_auth_note_custom_domains.md
  articles/quickstart/spa/_includes/_auth_note_dev_keys.md
  articles/quickstart/spa/angular-next/01-login.md
  articles/quickstart/spa/angular-next/download.md
  articles/quickstart/spa/angular-next/index.yml
  articles/quickstart/spa/react/01-login.md
Labels: do-not-merge, medium, quickstart, ready-for-review

#9382 Update github path for Angular tutorial
  articles/quickstart/spa/angular-next/01-login.md
Labels: quickstart, tiny

#9383 Moved redirect to Token Best Practices
  config/redirects.js
Labels: ready-for-review

#9387 Fix redirect for mobile browser-based vs native experience
  config/redirects.js
Labels: ready-for-review

#9392 Changed querystring to query string
  articles/api/authentication/_logout.md
  articles/api/authentication/_saml-sso.md
  articles/api/management/v1/index.md
  articles/architecture-scenarios/mobile-api/part-1.md
  articles/architecture-scenarios/web-app-sso/part-1.md
  articles/architecture-scenarios/web-app-sso/part-3.md
Labels: ready-for-review

#9393 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#9395 Fix broken markdown in social connections docs
  snippets/social/amazon/3.md
  snippets/social/auth0-oidc/1.md
  snippets/social/baidu/3.md
  snippets/social/basecamp/3.md
  snippets/social/docomo/3.md
  snippets/social/facebook/3.md
  snippets/social/fitbit/3.md
  snippets/social/goodreads/3.md
  snippets/social/google/3.md
  snippets/social/linkedin/3.md
  snippets/social/planning-center/3.md
  snippets/social/renren/3.md
  snippets/social/salesforce-sandbox/3.md
  snippets/social/twitter/3.md
  snippets/social/vkontakte/3.md
  snippets/social/weibo/3.md
  snippets/social/wordpress/3.md
  snippets/social/yahoo/3.md
  snippets/social/yammer/3.md
  snippets/social/yandex/3.md
Labels: ready-for-review

#9394 Remove Angular version from quickstart meta
  articles/quickstart/spa/angular2/01-login.md
Labels: quickstart

#9396 [SDK-1812] Updates for inclusive language across quickstarts
  articles/quickstart/native/_includes/_callback-url-introduction.md
  articles/quickstart/native/android/02-custom-login-form.md
  articles/quickstart/native/android/_includes/_lock_manifest.md
  articles/quickstart/native/windows-uwp-csharp/01-login.md
  articles/quickstart/native/xamarin/01-login.md
  articles/quickstart/spa/_includes/_callback_component.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/webapp/_includes/_getting_started.md
  articles/quickstart/webapp/aspnet-core-3/_includes/_login.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
Labels: quickstart

#9397 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#9406 Update sidebar.yml
  config/sidebar.yml
Labels: ready-for-review
