Repository auth0/docs, pull requests merged in 2020-12, with the labels that each got.

#9511 Update cards.yml
  config/cards.yml
Labels: do-not-merge

#9516 Fix typo in glossary
  config/glossary.json
Labels: ready-for-review

#9519 Changed sidebar item wording
  config/sidebar.yml
Labels: ready-for-review

#9520 Update Laravel quickstarts to reference latest SDK changes
  articles/quickstart/backend/laravel/index.yml
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/laravel/index.yml
Labels: quickstart, small

#9523 [SPA Quickstart] Add explanation that domain and audience should be configured for SPA backend
  articles/quickstart/spa/_includes/_calling_api_create_backend.md
Labels: quickstart, tiny

#9522 Added SPM installation instructions
  articles/libraries/lock-ios/_includes/_dependencies.md
Labels: small

#9528 Bump minimum supported PHP version to reflect current state of 7.3
  articles/_includes/_libraries_support_sdks.html
  articles/libraries/auth0-php/index.md
  articles/quickstart/backend/php/index.yml
  articles/quickstart/webapp/php/index.yml
Labels: ready-for-review, tiny

#9531 Add new bot detection docs to sidebar
  articles/api/authentication/errors/_errors.md
  config/sidebar.yml
Labels: ready-for-review

#9532 Updates based on DR-847
  articles/connections/azuread-adfs-email-verification.md
  media/connections/migration-section.png
Labels: small

#9527 Updated due to https://auth0.slack.com/archives/C02FE2CTZ/p1607207966…
  articles/architecture-scenarios/spa-api/part-1.md
Labels: ready-for-review, small

#9536 Add redirect for Mgmt API Access Token FAQs
  config/redirects.js
Labels: ready-for-review

#9521 Added Adaptive MFA to sidebar nav
  config/sidebar.yml
Labels: do-not-merge

#9524 Sidebar updates
  config/sidebar.yml
Labels: ready-for-review

#9542 Changed redirect for spa-redirect to customize-email-templates
  config/redirects.js
Labels: ready-for-review

#9539 Consolidated redirects
  config/redirects.js
Labels: ready-for-review, tiny

#9537 Updated _passwordless.md file
  articles/api/authentication/_passwordless.md
Labels: ready-for-review, small

#9543 Reorder Get Started items in sidebar
  config/sidebar.yml
Labels: ready-for-review, tiny

#9547 Update private cloud nav and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small
