Repository auth0/docs, pull requests merged in 2020-05, with the labels that each got.

#8832 Hide Deprecated Docs
  articles/_includes/_lock_auth0js_deprecations_notice.md
  articles/api-auth/intro.md
  articles/api-auth/tutorials/adoption/oidc-conformant.md
  articles/api-auth/tutorials/adoption/refresh-tokens.md
  articles/api/authentication/legacy/_linking.md
  articles/api/info.md
  articles/connections/enterprise/ip-address.md
  articles/connections/passwordless/guides/embedded-login-webapps.md
  articles/connections/social/auth0-oidc.md
  articles/connections/social/facebook.md
  articles/connections/social/linkedin.md
  articles/errors/deprecation-errors.md
  articles/extensions/deploy-cli/guides/call-deploy-cli-programmatically.md
  articles/extensions/deploy-cli/index.md
  articles/extensions/deploy-cli/references/whats-new.md
  articles/mfa/concepts/guardian.md
  articles/migrations/guides/facebook-social-context.md
  articles/migrations/guides/google_cloud_messaging.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/migrations/guides/linkedin-api-deprecation.md
  articles/migrations/guides/liveid-api-deprecation.md
  articles/migrations/guides/management-api-v1-v2.md
  articles/migrations/guides/passwordless-start.md
  articles/migrations/past-migrations.md
  articles/product-lifecycle/migrations.md
  articles/troubleshoot/guides/check-deprecation-errors.md
  articles/users/guides/link-user-accounts-auth-api.md
  config/redirects.js
  config/sidebar.yml
Labels: medium

#8989 improved account linking samples
  articles/users/references/link-accounts-client-side-scenario.md
  articles/users/references/link-accounts-server-side-scenario.md
  media/articles/link-accounts/account-linking-spa.png
  media/articles/link-accounts/account-linking-webapp-small.png
  media/articles/link-accounts/regular-web-app-initial-login.png
  media/articles/link-accounts/regular-web-app-user-settings.png
  media/articles/link-accounts/spa-initial-login.png
Labels: do-not-merge

#8948 Account Linking / email_verified changes
  articles/best-practices/rules.md
  articles/compliance/gdpr/features-aiding-compliance/data-minimization.md
  articles/users/concepts/overview-user-account-linking.md
Labels: do-not-merge, small

#8990 Update verify and change pw email templates param lists
  articles/email/templates.md
Labels: ready-for-review, tiny

#8994 Correct typing error
  articles/universal-login/new.md
Labels: ready-for-review, tiny

#8997 Improve clarity of wording
  articles/best-practices/metadata-best-practices.md
Labels: ready-for-review, tiny

#8979 WIP: Create doc on verified email usage
  articles/users/guides/email-verified.md
Labels: ready-for-review, small

#8981 Removing unnecessary/incorrect link
  articles/mfa/guides/reset-user-mfa.md
Labels: ready-for-review, tiny

#8983 Clarifying multiple audiences
  articles/tokens/guides/get-access-tokens.md
Labels: tiny

#8991 fixed links to custom mfa page
  articles/mfa/guides/guardian/create-enrollment-ticket.md
  articles/universal-login/multifactor-authentication.md
Labels: tiny

#9000 Adds link in the rules bulletin to the email verified usage document
  articles/security/bulletins/2019-01-10_rules.md
Labels: ready-for-review, tiny

#9006 Fix broken link
  articles/mfa/concepts/mfa-factors.md
Labels: ready-for-review, tiny

#9005 Update redirects.js
  config/redirects.js
Labels: ready-for-review, tiny

#9007 Add email verified usage doc to sidebar and users index
  articles/users/index.md
  config/sidebar.yml
Labels: ready-for-review, tiny

#8999 Update Auth0.swift docs [SDK-1631]
  articles/libraries/auth0-swift/database-authentication.md
  articles/libraries/auth0-swift/index.md
  articles/libraries/auth0-swift/passwordless.md
  articles/libraries/auth0-swift/save-and-refresh-jwt-tokens.md
  articles/libraries/auth0-swift/touchid-authentication.md
  articles/libraries/auth0-swift/user-management.md
  config/sidebar.yml
Labels: medium

#9009 Update error-pages.md
  articles/universal-login/error-pages.md
Labels: ready-for-review, tiny

#8995 Update management-api-v1-v2.md
  articles/migrations/guides/management-api-v1-v2.md
Labels: ready-for-review, tiny

#9017 Add clarity on when to contact Support
  articles/support/reset-account-password.md
Labels: tiny

#9020 Updated iOS libs installation instructions
  articles/libraries/auth0-swift/index.md
  articles/libraries/lock-ios/_includes/_dependencies.md
  articles/quickstart/native/_includes/_ios_dependency_centralized.md
  articles/quickstart/native/ios-swift/_includes/_dependency_embedded.md
  snippets/native-platforms/ios-facebook-login/facebook-install-auth0-sdk.md
Labels: small

#9012 Remove legacy OIDC behavior paragraph
  articles/libraries/auth0-android/index.md
Labels: tiny

#9018 Fix broken link
  config/sidebar.yml
Labels: ready-for-review, tiny

#9019 Fix broken links
  articles/product-lifecycle/migrations.md
Labels: ready-for-review, tiny

#8961 Add a guide for SMS MFA using Vonage
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/post-change-password.md
  articles/hooks/extensibility-points/post-user-registration.md
  articles/hooks/extensibility-points/pre-user-registration.md
  articles/hooks/extensibility-points/send-phone-message.md
  articles/mfa/guides/configure-sms.md
  articles/multifactor-authentication/_includes/_test-setup.md
  articles/multifactor-authentication/send-phone-message-hook-amazon-sns.md
  articles/multifactor-authentication/send-phone-message-hook-infobip.md
  articles/multifactor-authentication/send-phone-message-hook-telesign.md
  articles/multifactor-authentication/send-phone-message-hook-twilio.md
  articles/multifactor-authentication/send-phone-message-hook-vonage.md
  config/sidebar.yml
  media/articles/multifactor-authentication/01-guide-vonage-dashboard-sms-api-test.png
  media/articles/multifactor-authentication/02-guide-auth0-add-new-hook.png
  media/articles/multifactor-authentication/03-guide-auth0-edit-new-sms-hook.png
  media/articles/multifactor-authentication/04-guide-auth0-add-hook-secrets.png
  media/articles/multifactor-authentication/05-guide-auth0-add-nexmo-module.png
  media/articles/multifactor-authentication/06-guide-auth0-run-sms-hook.png
  media/articles/multifactor-authentication/07-guide-auth0-activate-sms-factor.png
  media/articles/multifactor-authentication/08-guide-test-sms-verification.png
  media/articles/multifactor-authentication/09-guide-login-sms-error-message.png
  media/articles/multifactor-authentication/10-guide-auth0-log-sms-error.png
  media/articles/multifactor-authentication/11-guide-auth0-log-sms-error-details.png
Labels: medium, ready-for-review

#9016 Update lock configuration options page
  articles/libraries/lock/v11/configuration.md
Labels: ready-for-review, small

#9031 Create private cloud regions page
  articles/private-cloud/regions.md
Labels: ready-for-review, small

#9028 Private cloud deployments
  articles/private-cloud/deployments.md
Labels: medium, ready-for-review

#9014 Fix code sample
  articles/users/references/link-accounts-client-side-scenario.md
  articles/users/references/link-accounts-server-side-scenario.md
Labels: ready-for-review, small

#9049 Add redirect to line connection
  config/redirects.js
Labels: ready-for-review, tiny

#9050 Update password grant before you start info
  articles/api-auth/tutorials/password-grant.md
Labels: small

#9058 Update 01-authorization.md
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart

#9056 Update Laravel web app quickstart with updated custom user guidance
  articles/quickstart/webapp/laravel/01-login.md
Labels: quickstart, small

#8982 Management API Rate Limits for Self Service Subscribers
  articles/api/management/guides/tenants/configure-session-lifetime-settings.md
  articles/dashboard/guides/tenants/configure-session-lifetime-settings.md
  articles/dashboard/reference/settings-tenant.md
  articles/dev-lifecycle/child-tenants.md
  articles/policies/endpoints.md
  articles/policies/entity-limits.md
  articles/policies/index.md
  articles/policies/legacy-rate-limits.md
  articles/policies/rate-limits-auth-api.md
  articles/policies/rate-limits-mgmt-api.md
  articles/policies/rate-limits.md
  config/sidebar.yml
  media/articles/policies/entity-limit-reached.png
Labels: do-not-merge, medium

#9064 Azure Event Grid copy-edits
  articles/logs/streams/azure-event-grid.md
Labels: ready-for-review, small

#8918 [IUM-932] MFA Import
  articles/connections/database/custom-db/templates/login.md
  articles/mfa/guides/import-user-mfa.md
  articles/mfa/index.md
  articles/users/guides/bulk-user-imports.md
  articles/users/references/bulk-import-database-schema-examples.md
Labels: medium

#9035 added esendex and fixed formatting
  articles/hooks/extensibility-points/send-phone-message.md
  articles/mfa/_includes/_enable-push-notifications.md
  articles/mfa/_includes/_test-setup.md
  articles/mfa/concepts/guardian.md
  articles/mfa/concepts/mfa-factors.md
  articles/mfa/guides/configure-cisco-duo.md
  articles/mfa/guides/configure-email-universal-login.md
  articles/mfa/guides/configure-otp.md
  articles/mfa/guides/configure-sms.md
  articles/mfa/guides/enable-mfa.md
  articles/mfa/guides/reset-user-mfa.md
  articles/mfa/send-phone-message-hook-amazon-sns.md
  articles/mfa/send-phone-message-hook-esendex.md
  articles/mfa/send-phone-message-hook-infobip.md
  articles/mfa/send-phone-message-hook-telesign.md
  articles/mfa/send-phone-message-hook-twilio.md
  articles/mfa/send-phone-message-hook-vonage.md
  articles/rules/references/use-cases.md
  articles/universal-login/multifactor-authentication.md
  media/articles/mfa/01-guide-vonage-dashboard-sms-api-test.png
  media/articles/mfa/02-guide-auth0-add-new-hook.png
  media/articles/mfa/03-guide-auth0-edit-new-sms-hook.png
  media/articles/mfa/04-guide-auth0-add-hook-secrets.png
  media/articles/mfa/05-guide-auth0-add-nexmo-module.png
  media/articles/mfa/06-guide-auth0-run-sms-hook.png
  media/articles/mfa/07-guide-auth0-activate-sms-factor.png
  media/articles/mfa/08-guide-test-sms-verification.png
  media/articles/mfa/09-guide-login-sms-error-message.png
  media/articles/mfa/10-guide-auth0-log-sms-error.png
  media/articles/mfa/11-guide-auth0-log-sms-error-details.png
  media/articles/mfa/duo-login.png
  media/articles/mfa/duo-screenshot.png
  media/articles/mfa/duo-settings.png
  media/articles/mfa/email-settings.png
  media/articles/mfa/google-auth-scan-code.png
  media/articles/mfa/google-auth-screenshot.png
  media/articles/mfa/guardian-download.png
  media/articles/mfa/guardian-functionality.png
  media/articles/mfa/guardian-push.png
  media/articles/mfa/guardian-settings.png
  media/articles/mfa/mfa-dashboard.png
  media/articles/mfa/mfa-email.png
  media/articles/mfa/mfa-otp-login.png
  media/articles/mfa/mfa-otp-setup.png
  media/articles/mfa/mfa-sms1.png
  media/articles/mfa/mfa-sms2.png
  media/articles/mfa/mfa-success.png
  media/articles/mfa/recovery-code.png
  media/articles/mfa/signup.png
  media/articles/mfa/sms-settings.png
Labels: ready-for-review

#9066 Update link & link text for shared users
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
Labels: in-review

#9072 Readd rules with passwordless use case
  articles/connections/passwordless/concepts/sample-use-cases-rules.md
Labels: ready-for-review, small

#9075 Hide Analytics section from public view
  articles/analytics/guides/facebook-analytics.md
  articles/analytics/guides/google-analytics.md
  articles/analytics/index.md
  config/sidebar.yml
Labels: ready-for-review, small

#9076 Add key dates table to migration guide for API1 to API2
  articles/migrations/guides/management-api-v1-v2.md
Labels: ready-for-review, small

#9036 Move Native Social SIWA to Native Connections page
  articles/connections/apple-siwa/add-siwa-to-web-app.md
  articles/connections/nativesocial/add-siwa-to-native-app.md
  articles/connections/social/37signals.md
  articles/connections/social/amazon.md
  articles/connections/social/apple.md
  articles/connections/social/baidu.md
  articles/connections/social/bitbucket.md
  articles/connections/social/box.md
  articles/connections/social/docomo.md
  articles/connections/social/dropbox.md
  articles/connections/social/dwolla.md
  articles/connections/social/evernote.md
  articles/connections/social/exact.md
  articles/connections/social/facebook.md
  articles/connections/social/fitbit.md
  articles/connections/social/github.md
  articles/connections/social/goodreads.md
  articles/connections/social/google.md
  articles/connections/social/instagram.md
  articles/connections/social/line.md
  articles/connections/social/linkedin.md
  articles/connections/social/microsoft-account.md
  articles/connections/social/oauth2.md
  articles/connections/social/paypal.md
  articles/connections/social/planning-center.md
  articles/connections/social/renren.md
  articles/connections/social/reprompt-permissions.md
  articles/connections/social/salesforce.md
  articles/connections/social/shopify.md
  articles/connections/social/soundcloud.md
  articles/connections/social/thecity.md
  articles/connections/social/twitter.md
  articles/connections/social/vkontakte.md
  articles/connections/social/weibo.md
  articles/connections/social/wordpress.md
  articles/connections/social/yahoo.md
  articles/connections/social/yammer.md
  articles/connections/social/yandex.md
  config/redirects.js
Labels: ready-for-review, small

#9083 Add Note about Passwordless SMS Gateway
  articles/connections/passwordless/guides/use-sms-gateway-passwordless.md
Labels: ready-for-review, tiny

#9089 Typo fix
  articles/libraries/auth0-php/management-api.md
Labels: ready-for-review, tiny

#9080 Clarify emails sent upon brute force protection
  articles/connections/database/rate-limits.md
Labels: ready-for-review, small

#9081 Fixed typo in title for legacy rate limits
  articles/policies/legacy-rate-limits.md
Labels: ready-for-review, tiny

#9084 Rename testing best practices page to reflect content
  articles/best-practices/testing.md
Labels: ready-for-review, tiny

#9082 Added RBAC limits
  articles/authorization/concepts/core-vs-extension.md
  articles/authorization/reference/rbac-limits.md
Labels: ready-for-review, small

#9090 Extra examples in deploy cli yaml config
  articles/extensions/deploy-cli/guides/import-export-yaml-file.md
Labels: ready-for-review, tiny

#9092 Modernize Shopify guide formatting
  articles/connections/social/shopify.md
Labels: ready-for-review, small

#9074 Native facebook GA
  articles/connections/nativesocial/facebook-native.md
  articles/quickstart/native/android-facebook-login/00-login-facebook.md
  articles/quickstart/native/ios-swift-facebook-login/00-login-facebook.md
Labels: quickstart

#9094 Removed links to /analytics docs
  articles/integrations/index.md
  articles/monitoring/guides/monitor-applications.md
Labels: ready-for-review, tiny

#9079 Update configure-refresh-token-rotation.md
  articles/tokens/guides/configure-refresh-token-rotation.md
Labels: ready-for-review, tiny

#9093 Update Xamarin quickstart to use latest major
  articles/quickstart/native/xamarin/index.yml
  snippets/native-platforms/xamarin/setup.md
Labels: quickstart, tiny
