Repository auth0/docs, pull requests merged in 2020-04, with the labels that each got.

#8874 Update Spring 5 API Quickstart to Spring Boot 2.2.6
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#8872 Updated the SIWA QuickStart [SDK-1489]
  articles/quickstart/native/ios-swift-siwa/_includes/_login_centralized.md
Labels: quickstart, tiny

#8885 Adjusting wording for accuracy
  articles/best-practices/metadata-best-practices.md
Labels: ready-for-review, tiny

#8884 Removing unused code
  articles/logs/references/log-event-type-codes.md
Labels: ready-for-review, tiny

#8883 Reserved names for custom permissions
  articles/dashboard/guides/apis/add-permissions-apis.md
Labels: ready-for-review, tiny

#8882 Updating Salesforce brand name
  articles/architecture-scenarios/b2e.md
  articles/integrations/index.md
  articles/integrations/sso/index.md
  articles/protocols/saml/identity-providers/salesforce.md
  articles/protocols/saml/index.html
  articles/protocols/saml/saml-configuration/auth0-as-identity-provider.md
  articles/protocols/saml/saml-configuration/auth0-as-service-provider.md
  articles/protocols/saml/saml-configuration/index.md
  articles/sso/current/outbound.md
  config/sidebar.yml
Labels: ready-for-review, small

#8878 Fixing broken link
  articles/api/management/guides/connections/configure-connection-sync.md
  config/redirects.js
Labels: ready-for-review, tiny

#8877 Fixing warning, adding copy to another
  articles/libraries/lock-android/v2/index.md
  articles/libraries/lock-ios/v2/index.md
Labels: ready-for-review, tiny

#8875 Update php examples for management api
  articles/libraries/auth0-php/index.md
  articles/libraries/auth0-php/management-api.md
Labels: ready-for-review, tiny

#8592 Native Facebook Login documentation
  articles/connections/identity-providers-social.md
  articles/connections/nativesocial/facebook.md
  media/articles/connections/nativesocial/native-social-login.png
Labels: do-not-merge

#8848 Native Facebook Login QuickStarts
  articles/quickstart/native/_includes/_facebook_login_howto.md
  articles/quickstart/native/_includes/_facebook_login_prerequisites.md
  articles/quickstart/native/android-facebook-login/00-login-facebook.md
  articles/quickstart/native/android-facebook-login/download.md
  articles/quickstart/native/android-facebook-login/index.yml
  articles/quickstart/native/android/index.yml
  articles/quickstart/native/ios-swift-facebook-login/00-login-facebook.md
  articles/quickstart/native/ios-swift-facebook-login/download.md
  articles/quickstart/native/ios-swift-facebook-login/index.yml
  articles/quickstart/native/ios-swift-siwa/00-login-siwa.md
  articles/quickstart/native/ios-swift-siwa/index.yml
  snippets/native-platforms/android-facebook-login/facebook-app-credentials.md
  snippets/native-platforms/android-facebook-login/facebook-button-config.md
  snippets/native-platforms/android-facebook-login/facebook-button-permissions.md
  snippets/native-platforms/android-facebook-login/facebook-fetch-profile.md
  snippets/native-platforms/android-facebook-login/facebook-fetch-session-token.md
  snippets/native-platforms/android-facebook-login/facebook-install-auth0-sdk.md
  snippets/native-platforms/android-facebook-login/facebook-token-exchange.md
  snippets/native-platforms/ios-facebook-login/facebook-app-credentials.md
  snippets/native-platforms/ios-facebook-login/facebook-button-config.md
  snippets/native-platforms/ios-facebook-login/facebook-button-permissions.md
  snippets/native-platforms/ios-facebook-login/facebook-fetch-profile.md
  snippets/native-platforms/ios-facebook-login/facebook-fetch-session-token.md
  snippets/native-platforms/ios-facebook-login/facebook-install-auth0-sdk.md
  snippets/native-platforms/ios-facebook-login/facebook-token-exchange.md
  snippets/native-platforms/ios-swift-siwa/setup.md
  snippets/native-platforms/ios-swift-siwa/use.md
Labels: do-not-merge, quickstart

#8894 Update social connections list
  articles/connections/identity-providers-social.md
  articles/connections/nativesocial/facebook-native.md
Labels: ready-for-review, small

#8898 Fix missing ldap screenshot
  articles/connections/enterprise/active-directory-ldap.md
Labels: ready-for-review, tiny

#8899 Add scopes request param
  articles/api/authentication/_login.md
Labels: ready-for-review, tiny

#8903 Add storage: root additional signup option to lock docs
  articles/libraries/lock/v11/configuration.md
Labels: ready-for-review, small

#8876 DXEX-503 Review and revise references to Magic Globals
  articles/connections/database/custom-db/create-db-connection.md
  articles/connections/database/custom-db/templates/change-password.md
  articles/connections/database/custom-db/templates/create.md
  articles/connections/database/custom-db/templates/delete.md
  articles/connections/database/custom-db/templates/get-user.md
  articles/connections/database/custom-db/templates/login.md
  articles/connections/database/custom-db/templates/verify.md
  articles/connections/database/db2-script.md
  articles/connections/social/oauth2.md
  articles/email/custom.md
  articles/integrations/authenticating-devices-using-mqtt.md
  articles/monitoring/guides/send-events-to-keenio.md
  articles/monitoring/guides/track-leads-salesforce.md
  articles/monitoring/guides/track-signups-salesforce.md
  articles/rules/guides/metadata.md
  articles/security/bulletins/2019-01-10_rules.md
  articles/users/references/user-data-storage-scenario.md
Labels: do-not-merge

#8821 New Refresh Token Rotation content
  articles/_includes/_refresh_token_rotation_panel.md
  articles/_includes/_refresh_token_rotation_recommended.md
  articles/api-auth/token-renewal-in-safari.md
  articles/api-auth/tutorials/silent-authentication.md
  articles/architecture-scenarios/mobile-api/index.md
  articles/architecture-scenarios/mobile-api/part-1.md
  articles/architecture-scenarios/spa-api/part-3.md
  articles/architecture-scenarios/spa-api/spa-implementation-angular2.md
  articles/best-practices/custom-db-connections/security.md
  articles/dashboard/guides/apis/update-token-lifetime.md
  articles/flows/concepts/auth-code-pkce.md
  articles/flows/concepts/implicit.md
  articles/mfa/guides/customize-mfa-universal-login.md
  articles/microsites/add-login/add-login-native-mobile-app.md
  articles/microsites/add-login/add-login-regular-web-app.md
  articles/microsites/add-login/add-login-single-page-app.md
  articles/microsites/call-api/call-api-device.md
  articles/microsites/call-api/call-api-m2m-app.md
  articles/microsites/call-api/call-api-native-mobile-app.md
  articles/microsites/call-api/call-api-regular-web-app.md
  articles/microsites/call-api/call-api-single-page-app.md
  articles/security/index.md
  articles/tokens/_includes/_rtr_enabled.md
  articles/tokens/concepts/refresh-token-rotation.md
  articles/tokens/concepts/refresh-tokens.md
  articles/tokens/concepts/token-storage.md
  articles/tokens/guides/configure-refresh-token-rotation.md
  articles/tokens/guides/disable-refresh-token-rotation.md
  articles/tokens/guides/revoke-refresh-tokens.md
  articles/tokens/guides/store-tokens.md
  articles/tokens/guides/use-refresh-token-rotation.md
  articles/tokens/guides/use-refresh-tokens.md
  articles/tokens/references/id-token-structure.md
  config/redirects.js
  config/sidebar.yml
  media/articles/tokens/in-memory-token-storage.png
  media/articles/tokens/non-rotating-tokens.png
  media/articles/tokens/reuse-detection.png
  media/articles/tokens/rotating-tokens.png
  media/articles/tokens/rt-and-at.png
  media/articles/tokens/rtr-state-diagram.png
Labels: medium, ready-for-review

#8911 Updated Auth0 SPA SDK docs for RTR
  articles/libraries/auth0-spa-js/index.md
  config/vars.yml
Labels: small

#8764 Review of node8 migrations docs in preparation for node 12 migration
  articles/dashboard/guides/extensions/delegated-admin-create-app.md
  articles/dashboard/guides/extensions/sso-dashboard-create-app.md
  articles/dashboard/reference/settings-tenant.md
  articles/extensions/delegated-admin/v2/index.md
  articles/extensions/troubleshoot.md
  articles/migrations/guides/extensibility-node12.md
  articles/product-lifecycle/migrations.md
  media/articles/migrations/node-hidden-secret-error.png
  media/articles/migrations/node-runtime1.png
  media/articles/migrations/node-runtime2.png
Labels: do-not-merge, in-review

#8916 Update Laravel WebApp Quickstart dependencies
  articles/quickstart/webapp/laravel/01-login.md
  articles/quickstart/webapp/laravel/index.yml
Labels: quickstart, tiny

#8922 Added additional redirect for MFA
  config/redirects.js
Labels: ready-for-review, tiny

#8905 Add Product Release Stages
  articles/product-lifecycle/deprecation-eol.md
  articles/product-lifecycle/index.md
  articles/product-lifecycle/migration-process.md
  articles/product-lifecycle/migrations.md
  articles/product-lifecycle/product-release-stages.md
  config/glossary.json
  config/redirects.js
  config/sidebar.yml
Labels: do-not-merge, in-review

#8929 Fix Facebook Native snippet
  snippets/native-platforms/android-facebook-login/facebook-fetch-profile.md
Labels: quickstart, tiny

#8930 [SDK-1442] Updated SPA include to point to PKCE flow docs
  articles/quickstart/spa/_includes/_getting_started.md
Labels: quickstart

#8935 Fixed broken link to postman
  articles/api/postman.md
Labels: ready-for-review, tiny

#8932 Update Mgmt API Connection Options attributes
  articles/connections/references/_includes/_options-validation.md
  articles/connections/references/options-mgmt-api.md
Labels: ready-for-review, tiny

#8921 Added Additional OIDC Connection Settings
  articles/connections/enterprise/oidc.md
  media/articles/dashboard/connections/enterprise/conn-enterprise-additional-oidc-settings.png
Labels: do-not-merge, in-review, small

#8870 Signing key rotation docs for review
  articles/_includes/_create_resource_server.md
  articles/architecture-scenarios/mobile-api/api-implementation-nodejs.md
  articles/architecture-scenarios/server-api/api-implementation-nodejs.md
  articles/architecture-scenarios/spa-api/api-implementation-nodejs.md
  articles/best-practices/token-best-practices.md
  articles/dashboard/guides/tenants/configure-device-user-code-settings.md
  articles/dashboard/guides/tenants/configure-session-lifetime-settings.md
  articles/dashboard/guides/tenants/enable-sso-tenant.md
  articles/dashboard/guides/tenants/revoke-signing-keys.md
  articles/dashboard/guides/tenants/rotate-signing-keys.md
  articles/dashboard/guides/tenants/view-signing-keys.md
  articles/dashboard/reference/settings-tenant.md
  articles/mfa/guides/configure-step-up-apis.md
  articles/policies/rate-limits.md
  articles/protocols/saml/samlp.md
  articles/tokens/concepts/jwks.md
  articles/tokens/guides/manage-signing-keys.md
  config/sidebar.yml
  media/articles/dashboard/guides/tenants/tenant-settings.png
  media/articles/dashboard/tenants/tenant-settings-advanced-device-user-code.png
  media/articles/dashboard/tenants/tenant-settings-advanced-login-session-management.png
  media/articles/dashboard/tenants/tenant-settings-signing-keys-revoke-confirm.png
  media/articles/dashboard/tenants/tenant-settings-signing-keys-revoke.png
  media/articles/dashboard/tenants/tenant-settings-signing-keys-rotate-confirm.png
  media/articles/dashboard/tenants/tenant-settings-signing-keys-rotate-revoke-confirm.png
  media/articles/dashboard/tenants/tenant-settings-signing-keys.png
  media/articles/dashboard/tenants/tenant-settings.png
Labels: do-not-merge, in-review

#8936 Clarify refresh token rotation on implicit flow
  articles/_includes/_refresh_token_rotation_recommended.md
  articles/flows/concepts/implicit.md
Labels: ready-for-review, tiny

#8942 Added info on RSS feed subscription for Auth0 status
  articles/monitoring/guides/check-status.md
Labels: ready-for-review, tiny

#8939 add sanitization to custom error doc
  articles/universal-login/custom-error-pages.md
Labels: ready-for-review

#8940 Hosted Pages clean-up
  articles/analytics/guides/facebook-analytics.md
  articles/api-auth/intro.md
  articles/appliance/admin/index.md
  articles/applications/concepts/grant-types-legacy.md
  articles/architecture-scenarios/_includes/_authentication/_universal-login.md
  articles/architecture-scenarios/_includes/_provisioning/_introduction.md
  articles/architecture-scenarios/_includes/_provisioning/_self-signup.md
  articles/architecture-scenarios/spa-api/spa-implementation-angular2.md
  articles/best-practices/connection-settings.md
  articles/best-practices/tenant-settings.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-custom-ui.md
  articles/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock.md
  articles/connections/database/password-strength.md
  articles/cross-origin-authentication/index.md
  articles/custom-domains/additional-configuration.md
  articles/custom-domains/index.md
  articles/custom-domains/troubleshoot.md
  articles/dashboard/manage-dashboard-admins.md
  articles/dashboard/reference/settings-tenant.md
  articles/errors/deprecation-errors.md
  articles/extensions/account-link.md
  articles/guides/login/_includes/_customizing-login-page.md
  articles/guides/login/migration-embedded-universal.md
  articles/guides/login/migration-sso.md
  articles/guides/login/universal-vs-embedded.md
  articles/hosted-pages/login/index.md
  articles/libraries/auth0-android/index.md
  articles/libraries/auth0js/v9/migration-guide.md
  articles/libraries/lock/v11/configuration.md
  articles/libraries/lock/v11/migration-guide.md
  articles/login/index.md
  articles/microsites/add-login/add-login-native-mobile-app.md
  articles/microsites/add-login/add-login-regular-web-app.md
  articles/microsites/add-login/add-login-single-page-app.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/migrations/past-migrations.md
  articles/pre-deployment/tests/recommended.md
  articles/sso/current/sso-auth0.md
  articles/troubleshoot/guides/check-deprecation-errors.md
  articles/troubleshoot/guides/check-login-logout-issues.md
  articles/universal-login/custom-error-pages.md
  articles/universal-login/error-pages.md
  articles/universal-login/version-control.md
  articles/users/guides/azure-access-control.md
  articles/users/references/link-accounts-client-side-scenario.md
  articles/users/references/link-accounts-server-side-scenario.md
  config/redirects.js
Labels: medium, ready-for-review

#8941 Fix broken MFA link
  articles/mfa/guides/configure-sms.md
  articles/mfa/references/troubleshoot-mfa.md
  config/redirects.js
Labels: ready-for-review, small

#8944 Removing C# support for rules
  articles/rules/guides/csharp.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, tiny

#8805 [ULP-1730] Added documentation for Send Phone Message Hook
  articles/hooks/create.md
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/send-phone-message.md
  articles/mfa/guides/configure-sms.md
  articles/multifactor-authentication/send-phone-message-hook-amazon-sns.md
  articles/multifactor-authentication/send-phone-message-hook-infobip.md
  articles/multifactor-authentication/send-phone-message-hook-telesign.md
  articles/multifactor-authentication/send-phone-message-hook-twilio.md
  config/sidebar.yml
  media/articles/multifactor-authentication/mfa-sms1.png
  media/articles/multifactor-authentication/mfa-sms2.png
  media/articles/multifactor-authentication/sms-number.png
  media/articles/multifactor-authentication/sms-settings.png
Labels: do-not-merge

#8949 Changed 'gateway' to 'provider'
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/send-phone-message.md
  articles/mfa/guides/configure-sms.md
  articles/multifactor-authentication/send-phone-message-hook-amazon-sns.md
  articles/multifactor-authentication/send-phone-message-hook-infobip.md
  articles/multifactor-authentication/send-phone-message-hook-telesign.md
  articles/multifactor-authentication/send-phone-message-hook-twilio.md
  media/articles/mfa/mfa-sms-twilio.png
  media/articles/mfa/sms-config.png
Labels: do-not-merge, in-review

#8954 Fix upside down image
  media/articles/logs/http-event-stream.png
Labels: ready-for-review, tiny

#8946 Update express quickstart
  articles/quickstart/webapp/express/01-login.md
Labels: quickstart

#8951 Fixed URL in ping7 IdP SAML Protocols
  articles/protocols/saml/identity-providers/ping7.md
Labels: ready-for-review, tiny

#8950 Clarify rules in context of authentication transaction flow
  articles/flows/guides/auth-code-pkce/includes/sample-use-cases-call-api.md
  articles/flows/guides/auth-code/includes/sample-use-cases-call-api.md
  articles/flows/guides/implicit/includes/sample-use-cases-call-api.md
  articles/rules/index.md
  articles/rules/references/context-object.md
  articles/rules/references/user-object.md
  articles/scopes/current/sample-use-cases.md
Labels: ready-for-review, small

#8952 Combine duplicate account linking scenarios/remove links to old Github samples
  articles/users/references/link-accounts-client-side-scenario.md
  articles/users/references/link-accounts-server-side-scenario.md
  articles/users/references/link-accounts-user-initiated-scenario.md
  config/redirects.js
  config/sidebar.yml
Labels: medium, ready-for-review

#8956 Add token storage link and explain that auth code is one-time use
  articles/flows/concepts/auth-code-pkce.md
  articles/flows/concepts/auth-code.md
  articles/flows/concepts/client-credentials.md
  articles/flows/concepts/device-auth.md
  articles/flows/concepts/implicit.md
Labels: ready-for-review, small

#8957 Add info about SAML vulnerabilities and blog post to arch scenario
  articles/architecture-scenarios/web-saml.md
Labels: ready-for-review, tiny

#8945 Remove miicard support
  articles/connections/social/miicard.md
  config/redirects.js
Labels: ready-for-review, tiny

#8928 Self-managed certificates fix
  articles/custom-domains/_cloudflare-cname-flattening.md
  articles/custom-domains/_provide-domain-name.md
  articles/custom-domains/self-managed-certificates.md
  articles/custom-domains/set-up-cloudflare.md
Labels: ready-for-review, small

#8943 Updated Azure AD screenshots
  articles/connections/enterprise/azure-active-directory/v2/index.md
  media/articles/dashboard/connections/enterprise/conn-enterprise-list.png
  media/articles/dashboard/connections/enterprise/conn-enterprise-ms-azure-ad-settings-1.png
  media/articles/dashboard/connections/enterprise/conn-enterprise-ms-azure-ad-settings-2.png
Labels: ready-for-review, small

#8792 OPEX-929: Add an entry for Datadog under the Log Streams documentation
  articles/logs/streams/aws-eventbridge.md
  articles/logs/streams/datadog.md
  articles/logs/streams/http-event.md
  articles/logs/streams/index.md
  config/sidebar.yml
  media/articles/logs/datadog/tutorial-1.png
  media/articles/logs/datadog/tutorial-2.png
  media/articles/logs/datadog/tutorial-3.png
  media/articles/logs/datadog/tutorial-4.png
Labels: do-not-merge

#8958 Add optional scope parameter to refresh token endpoint in Authentication API Explorer
  articles/api/authentication/api-authz/_get-token.md
Labels: ready-for-review, tiny

#8959 Fix table formatting
  articles/dashboard/guides/extensions/delegated-admin-create-app.md
Labels: ready-for-review, tiny

#8963 Add rules order in context of transaction flow
  articles/rules/index.md
Labels: ready-for-review, tiny

#8964 Add sample response body and parameter values
  articles/users/search/v3/get-users-endpoint.md
  articles/users/search/v3/view-search-results-by-page.md
Labels: ready-for-review, small

#8965 Clarify tenant name and custom domain treatment during deletion
  articles/support/delete-reset-tenant.md
Labels: ready-for-review, tiny

#8966 Move MFA default exp note
  articles/mfa/guides/customize-mfa-universal-login.md
Labels: ready-for-review, tiny

#8960 Moving new Express QS out of Beta
  .github/CODEOWNERS
  articles/quickstart/webapp/express/01-login.md
  articles/quickstart/webapp/express/download.md
  articles/quickstart/webapp/express/index.yml
  articles/quickstart/webapp/nodejs/01-login.md
  articles/quickstart/webapp/nodejs/download.md
  articles/quickstart/webapp/nodejs/index.yml
Labels: quickstart

#8968 Update Laravel API Quickstart for Laravel 6 and updated SDK
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/backend/laravel/index.yml
Labels: quickstart

#8976 Add sample ID Token contents with custom claims
  articles/scopes/current/sample-use-cases.md
Labels: ready-for-review, small

#8974 Updated Refresh Token diagrams
  articles/tokens/concepts/refresh-token-rotation.md
  media/articles/tokens/reuse-detection.png
  media/articles/tokens/reuse-detection1.png
  media/articles/tokens/reuse-detection2.png
Labels: ready-for-review, small

#8925 Fix Management API Tokens issues
  articles/api/management/v2/create-m2m-app.md
  articles/api/management/v2/get-access-tokens-for-spas.md
  articles/api/management/v2/tokens.md
  articles/policies/rate-limits.md
  articles/users/guides/manage-user-metadata.md
Labels: ready-for-review, small
