Repository auth0/docs, pull requests merged in 2020-11, with the labels that each got.

#9501 [SDK-2089] Vue Quickstart - sync auth wrapper with sample
  articles/quickstart/spa/vuejs/_includes/_centralized_login.md
Labels: quickstart, ready-for-review, tiny

#9505 Add native login links to microsite widget
  articles/microsites/add-login/add-login-native-mobile-app.md
Labels: ready-for-review

#9508 Archive and redirect custom social extension to oauth2 custom connection
  articles/architecture-scenarios/_includes/_authentication/_sso-legacy.md
  articles/connections/generic-oauth2-connection-examples.md
  config/redirects.js
Labels: ready-for-review

#9509 Add link to new cookies doc
  config/sidebar.yml
Labels: ready-for-review

#9512 Removed redundant sentence
  articles/connections/database/custom-db/templates/get-user.md
Labels: ready-for-review

#9514 Log Stream URLs and new Sumo Logic Link
  config/sidebar.yml
Labels: do-not-merge
