Repository auth0/docs, pull requests merged in 2020-07, with the labels that each got.

#9148 Correct intro to device quickstart
  articles/quickstart/native/device/01-login.md
Labels: quickstart, tiny

#9195 Add Note about DNS Provider Proxy Settings
  articles/custom-domains/_provide-domain-name.md
  articles/custom-domains/auth0-managed-certificates.md
Labels: ready-for-review, tiny

#9215 Update tenant-create.png
  media/articles/connections/tenant-create.png
Labels: ready-for-review, tiny

#9166 Add Spring Boot 2 Quickstart article
  articles/quickstart/webapp/java-spring-boot/01-login.md
  articles/quickstart/webapp/java-spring-boot/download.md
  articles/quickstart/webapp/java-spring-boot/index.yml
Labels: large, quickstart

#9211 Remove Spring Boot 1 RWA Quickstart articles
  articles/quickstart/webapp/java-spring-mvc/01-login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_setup.md
  articles/quickstart/webapp/java-spring-mvc/download.md
  articles/quickstart/webapp/java-spring-mvc/index.yml
  articles/quickstart/webapp/java-spring-security-mvc/01-login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
  articles/quickstart/webapp/java-spring-security-mvc/download.md
  articles/quickstart/webapp/java-spring-security-mvc/index.yml
Labels: quickstart, small

#9224 publish CVE-2020-15084 bulletin
  articles/security/bulletins/cve-2020-15084.md
  articles/security/bulletins/index.md
Labels: ready-for-review

#9213 Fixed typo in "kid" to "ID"
  articles/dashboard/guides/tenants/revoke-signing-keys.md
  articles/dashboard/guides/tenants/view-signing-keys.md
Labels: ready-for-review, tiny

#9212 Remove duplicate info from API1 to API2 migration doc
  articles/api/management/v2/changes.md
Labels: ready-for-review, tiny

#9221 User script mandatory during custom db automatic migration
  articles/connections/database/custom-db/templates/get-user.md
Labels: ready-for-review, small

#9156 added new languages
  articles/universal-login/i18n.md
Labels: do-not-merge

#9228 added note about HRD domains being accessible
  articles/universal-login/identifier-first.md
Labels: do-not-merge

#9238 Update support matrix with currently supported java quickstarts
  articles/support/matrix.md
Labels: tiny

#9232 Add store and reuse info to token best practices
  articles/best-practices/token-best-practices.md
Labels: ready-for-review, tiny

#9209 edits to the event stream documentation
  articles/logs/streams/amazon-eventbridge.md
  articles/logs/streams/datadog.md
Labels: do-not-merge, in-review

#9247 Fixed Challenge with Recovery Codes doc title
  articles/mfa/guides/mfa-api/recovery-code.md
Labels: ready-for-review, tiny

#9250 Updating rate limits wording to be inclusive of all paying customers instead of enterprise only
  articles/policies/rate-limits-auth-api.md
  articles/policies/rate-limits.md
Labels: ready-for-review, small

#9242 PET-472 Lab 01 Updates
  articles/identity-labs/01-web-sign-in/exercise-01.md
Labels: ready-for-review

#9251 Add notice on extensions
  articles/migrations/guides/unpaginated-api2-requests.md
Labels: do-not-merge, in-review

#9253 Hide removed addon docs
  articles/addons/azure-blob-storage.md
  articles/addons/azure-mobile-services.md
  articles/addons/azure-sb.md
  articles/addons/index.md
  articles/addons/salesforce-sandbox.md
  articles/addons/salesforce.md
  articles/addons/sap-odata.md
  config/sidebar.yml
Labels: ready-for-review, small

#9240 Remove outdated/orphaned services docs
  articles/services/auth0-advanced.md
  articles/services/auth0-introduction.md
Labels: ready-for-review, tiny

#9233 Fix SAML addon settings and AWS config order in AWS SSO integration doc
  articles/integrations/aws/sso.md
Labels: medium, ready-for-review

#9256 Update doc variables on paypal connections
  articles/connections/social/paypal-sandbox.md
  articles/connections/social/paypal.md
Labels: ready-for-review, tiny

#9258 Add dbconnection signup rate limit
  articles/policies/rate-limits-auth-api.md
Labels: ready-for-review, tiny

#9257 Clarify hooks connection compatibility
  articles/hooks/extensibility-points/index.md
  articles/hooks/index.md
Labels: ready-for-review, tiny

#9261 Fix redirect url var for paypal connections
  articles/connections/social/paypal-sandbox.md
  articles/connections/social/paypal.md
Labels: ready-for-review, tiny

#9230 Unpaginated Request Deprecation and Migration
  articles/migrations/guides/unpaginated-api2-requests.md
  articles/product-lifecycle/migrations.md
Labels: ready-for-review, small

#9262 Update 02-calling-an-api.md
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart

#9269 Updating PR template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: ready-for-review, small

#9266 Contentful Launch PR
  config/included-folders.yml
  config/redirects.js
  config/sections.yml
  config/sidebar.yml
Labels: do-not-merge

#9284 Revert "Contentful Launch PR (#9266)"
  config/included-folders.yml
  config/redirects.js
  config/sections.yml
  config/sidebar.yml
Labels: do-not-merge
