Repository auth0/docs, pull requests merged in 2020-09, with the labels that each got.

#9407 Make prod look at GitHub for SSO integrations
  config/included-folders.yml
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9405 Update 01-login.md
  articles/quickstart/spa/react/01-login.md
Labels: quickstart

#9410 Fixed links to Bot Detection doc
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9411 Add Email Template Descriptions link in Sidebar
  config/sidebar.yml
Labels: ready-for-review

#9415 Fix typo in Twitter connection
  snippets/social/twitter/1.md
Labels: ready-for-review

#9414 Updated for Inclusive Language
  articles/api/authorization-extension/_users.md
  articles/architecture-scenarios/_includes/_authentication/_mfa.md
  articles/architecture-scenarios/implementation/b2b/b2b-provisioning.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small

#9416 Migrated User/Password Auth Rate Limits to Contentful
  articles/api/authentication/_introduction.md
  articles/api/authentication/_login.md
  articles/api/authentication/legacy/_login.md
  articles/connections/database/index.md
  articles/connections/database/rate-limits.md
  articles/policies/rate-limits.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small

#9413 Add UL page templates to brand/customize section of sidebar
  config/sidebar.yml
Labels: ready-for-review

#9418 Refactor: change authentication into authorization
  articles/quickstart/backend/nodejs/01-authorization.md
Labels: quickstart, tiny

#9417 Professional Services Sidebar and Redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9421 Splunk Log Streaming Sidebar updates
  config/sidebar.yml
Labels: ready-for-review

#9423 Added sidebar link to orphan
  config/sidebar.yml
Labels: ready-for-review

#9409 [SDK-1920] Add Calling an API chapter to Angular quickstart
  articles/quickstart/spa/_includes/_calling_api_preamble_api2.md
  articles/quickstart/spa/angular-next/01-login.md
  articles/quickstart/spa/angular-next/02-calling-an-api.md
  articles/quickstart/spa/angular-next/index.yml
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: medium, quickstart, ready-for-review

#9425 Update express quickstart
  articles/quickstart/webapp/express/01-login.md
Labels: do-not-merge

#9432 Language change to tutorial view
  snippets/sso-integrations/ad-rms/5.md
  snippets/sso-integrations/box/5.md
  snippets/sso-integrations/cisco-webex/5.md
  snippets/sso-integrations/cloudbees/5.md
  snippets/sso-integrations/concur/5.md
  snippets/sso-integrations/datadog/5.md
  snippets/sso-integrations/dropbox/5.md
  snippets/sso-integrations/dynamics-crm/5.md
  snippets/sso-integrations/echosign/5.md
  snippets/sso-integrations/egencia/5.md
  snippets/sso-integrations/egnyte/5.md
  snippets/sso-integrations/eloqua/5.md
  snippets/sso-integrations/freshdesk/5.md
  snippets/sso-integrations/g-suite/5.md
  snippets/sso-integrations/github-enterprise-cloud/5.md
  snippets/sso-integrations/github-enterprise-server/5.md
  snippets/sso-integrations/heroku/5.md
  snippets/sso-integrations/hosted-graphite/5.md
  snippets/sso-integrations/litmos/5.md
  snippets/sso-integrations/new-relic/5.md
  snippets/sso-integrations/office-365/5.md
  snippets/sso-integrations/pluralsight/5.md
  snippets/sso-integrations/salesforce/5.md
  snippets/sso-integrations/sentry/5.md
  snippets/sso-integrations/sharepoint/5.md
  snippets/sso-integrations/slack/5.md
  snippets/sso-integrations/springcm/5.md
  snippets/sso-integrations/sprout-video/5.md
  snippets/sso-integrations/tableau-online/5.md
  snippets/sso-integrations/tableau-server/5.md
  snippets/sso-integrations/workday/5.md
  snippets/sso-integrations/workpath/5.md
  snippets/sso-integrations/zendesk/5.md
  snippets/sso-integrations/zoom/5.md
Labels: ready-for-review

#9422 Fix typo: opend --> openid for embedded login native
  articles/connections/passwordless/guides/embedded-login-native.md
Labels: ready-for-review

#9434 Add new Angular SPA SDK to sidebar
  config/sidebar.yml
Labels: ready-for-review

#9398 Move requires_username to under main options object
  articles/connections/references/_includes/_options-validation.md
  articles/connections/references/options-mgmt-api.md
Labels: ready-for-review

#9435 Removed link to auto-generated content
  articles/connections/enterprise/adfs.md
Labels: ready-for-review

#9438 Update redirects for Splunk docs
  config/redirects.js
Labels: ready-for-review

#9440 Most recent social connection guide fixes
  snippets/social/baidu/3.md
  snippets/social/basecamp/3.md
  snippets/social/bitbucket/3.md
  snippets/social/box/3.md
  snippets/social/clever/3.md
  snippets/social/digitalocean/3.md
  snippets/social/discord/3.md
  snippets/social/dropbox/3.md
  snippets/social/dwolla/3.md
  snippets/social/exact/3.md
  snippets/social/figma/3.md
  snippets/social/fitbit/3.md
  snippets/social/linkedin/3.md
  snippets/social/microsoft-account/3.md
  snippets/social/paypal-sandbox/3.md
  snippets/social/paypal/3.md
  snippets/social/planning-center/3.md
  snippets/social/quickbooks-online/3.md
  snippets/social/renren/3.md
  snippets/social/shopify/3.md
  snippets/social/slack/3.md
  snippets/social/twitch/3.md
  snippets/social/vimeo/3.md
  snippets/social/vkontakte/3.md
  snippets/social/weibo/3.md
  snippets/social/wordpress/3.md
  snippets/social/yammer/3.md
  snippets/social/yandex/3.md
Labels: ready-for-review

#9446 Add dashboard outlier fields to social connection guides for marketplace
  snippets/social/apple/3.md
  snippets/social/apple/4.md
  snippets/social/basecamp/4.md
  snippets/social/exact/4.md
  snippets/social/facebook/4.md
  snippets/social/google/4.md
  snippets/social/linkedin/4.md
  snippets/social/microsoft-account/3.md
  snippets/social/microsoft-account/4.md
  snippets/social/salesforce-community/4.md
  snippets/social/salesforce-community/5.md
  snippets/social/shopify/4.md
Labels: ready-for-review

#9447 Change platform to look at GitHub for SSO Integrations [HOLD FOR MARKETPLACE LAUNCH - 1]
  config/included-folders.yml
  config/redirects.js
Labels: do-not-merge

#9452 Fix small issues with Angular quickstart
  articles/quickstart/spa/angular/01-login.md
  articles/quickstart/spa/angular/02-calling-an-api.md
  media/platforms/angular.png
Labels: quickstart, ready-for-review, tiny

#9433 [SDK-1957] Update aspnet core quickstart to match sample
  articles/quickstart/webapp/aspnet-core-3/02-user-profile.md
  articles/quickstart/webapp/aspnet-core-3/03-authorization.md
  articles/quickstart/webapp/aspnet-core-3/_includes/_login.md
  articles/quickstart/webapp/aspnet-core-3/_includes/_setup.md
Labels: quickstart, ready-for-review

#9448 [SDK-1965] Update ASPNET Core Web API Quickstart
  articles/quickstart/backend/_includes/_api_create_new.md
  articles/quickstart/backend/_includes/_api_troubleshooting.md
  articles/quickstart/backend/_includes/_api_using.md
  articles/quickstart/backend/aspnet-core-webapi/01-authorization.md
  articles/quickstart/backend/aspnet-core-webapi/03-troubleshooting.md
  articles/quickstart/backend/aspnet-core-webapi/index.yml
  snippets/api-auth/hs256/csharp.md
Labels: quickstart, ready-for-review

#9424 [SDK-1956] Update aspnet-owin quickstart to match sample
  articles/quickstart/webapp/aspnet-owin/00-intro.md
  articles/quickstart/webapp/aspnet-owin/01-login.md
  articles/quickstart/webapp/aspnet-owin/02-user-profile.md
  articles/quickstart/webapp/aspnet-owin/03-authorization.md
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
Labels: quickstart, ready-for-review

#9453 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#9457 Updates to Angular quickstart from consumer feedback
  articles/quickstart/spa/angular/01-login.md
  articles/quickstart/spa/angular/index.yml
Labels: quickstart, ready-for-review, tiny

#9463 [SDK-1971] Add quickstart for ASPNET Core 2.1 Web API
  articles/quickstart/backend/aspnet-core-webapi-2/01-authorization.md
  articles/quickstart/backend/aspnet-core-webapi-2/02-using.md
  articles/quickstart/backend/aspnet-core-webapi-2/03-troubleshooting.md
  articles/quickstart/backend/aspnet-core-webapi-2/download.md
  articles/quickstart/backend/aspnet-core-webapi-2/index.yml
Labels: quickstart, ready-for-review
