Repository auth0/docs, pull requests merged in 2020-03, with the labels that each got.

#8799 Yahoo user profile changes
  articles/migrations/guides/yahoo-userinfo-updates.md
  articles/product-lifecycle/migrations.md
Labels: in-review

#8804 Updated index.yml to remove explicit auth0-spa-js version
  articles/quickstart/spa/angular2/index.yml
  articles/quickstart/spa/react/index.yml
  articles/quickstart/spa/vanillajs/index.yml
  articles/quickstart/spa/vuejs/index.yml
Labels: quickstart

#8794 explanatory note about metadata endpoints and custom domains [IPS-1074]
  articles/custom-domains/index.md
Labels: in-review

#8768 Changed JWT Expiration to ID Token Expiration
  articles/applications/application-settings/_settings-pt2.md
  articles/best-practices/application-settings.md
  articles/dashboard/guides/applications/update-token-lifetime.md
  articles/dashboard/reference/settings-application.md
  articles/libraries/auth0js/v9/index.md
  articles/libraries/lock/v11/configuration.md
  articles/sessions/references/example-short-lived-session-mgmt.md
  media/articles/applications/settings.png
  media/articles/dashboard/guides/rotate-client-secret.png
Labels: ready-for-review, small

#8797 Update Enum property list on pass-parameters-to-idps.md
  articles/connections/pass-parameters-to-idps.md
Labels: ready-for-review, tiny

#8798 Clarify password history availability
  articles/connections/database/password-options.md
Labels: in-review

#8809 Removing duplicate entries
  articles/guides/ip-whitelist.md
Labels: ready-for-review, tiny

#8812 fixing broken link
  articles/dashboard/guides/connections/test-connections-enterprise.md
Labels: ready-for-review, tiny

#8811 adding a link for context about rules
  articles/api-auth/tutorials/adoption/scope-custom-claims.md
Labels: ready-for-review, tiny

#8796 Add instagram deprecation warning
  articles/connections/social/instagram.md
Labels: in-review

#8749 Clean Up Account Linking docs
  articles/_includes/_linking_accounts.md
  articles/api/authentication/legacy/_linking.md
  articles/api/info.md
  articles/architecture-scenarios/_includes/_authentication/_social-authentication.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_linking-accounts.md
  articles/architecture-scenarios/implementation/b2b/b2b-authentication.md
  articles/best-practices/rules.md
  articles/compliance/gdpr/features-aiding-compliance/data-minimization.md
  articles/connections/calling-an-external-idp-api.md
  articles/connections/passwordless/guides/best-practices.md
  articles/dev-centers/java.md
  articles/extensions/account-link.md
  articles/libraries/auth0-android/user-management.md
  articles/libraries/auth0-swift/user-management.md
  articles/libraries/auth0js/v9/index.md
  articles/link-accounts/index.md
  articles/link-accounts/suggested-linking/index.md
  articles/link-accounts/user-initiated-linking.md
  articles/link-accounts/user-initiated-linking/index.md
  articles/migrations/guides/account-linking-id-tokens.md
  articles/migrations/guides/account-linking.md
  articles/migrations/guides/calling-api-with-idtokens.md
  articles/migrations/past-migrations.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/ios-swift/07-linking-accounts.md
  articles/rules/_includes/_user-prop-identities.md
  articles/rules/references/context-object.md
  articles/rules/references/use-cases.md
  articles/users/_includes/_account-linking-id-tokens.md
  articles/users/_includes/_user-prop-identities.md
  articles/users/concepts/overview-user-account-linking.md
  articles/users/concepts/overview-user-profile.md
  articles/users/guides/link-user-accounts-auth-api.md
  articles/users/guides/link-user-accounts.md
  articles/users/guides/unlink-user-accounts.md
  articles/users/normalized/auth0/normalized-user-profile-schema.md
  articles/users/references/link-accounts-client-side-scenario.md
  articles/users/references/link-accounts-server-side-scenario.md
  articles/users/references/link-accounts-user-initiated-scenario.md
  articles/users/search/v3/get-users-endpoint.md
  config/redirects.js
  config/sidebar.yml
Labels: large, ready-for-review

#8747 Update side nav sections
  config/sidebar.yml
Labels: medium, ready-for-review

#8327 Update SPA microsites and flows to discuss PKCE
  articles/api-auth/index.md
  articles/api-auth/intro.md
  articles/api/authentication/api-authz/_authz-client.md
  articles/api/authentication/api-authz/_get-token.md
  articles/connections/calling-an-external-idp-api.md
  articles/flows/concepts/auth-code-pkce.md
  articles/flows/concepts/implicit.md
  articles/flows/guides/auth-code-pkce/add-login-auth-code-pkce.md
  articles/flows/guides/auth-code-pkce/call-api-auth-code-pkce.md
  articles/flows/guides/implicit/add-login-implicit.md
  articles/flows/guides/implicit/includes/authorize-user-add-login.md
  articles/flows/guides/implicit/includes/sample-use-cases-add-login.md
  articles/flows/index.md
  articles/integrations/sharepoint.md
  articles/microsites/add-login/add-login-single-page-app.md
  articles/microsites/call-api/call-api-single-page-app.md
  articles/quickstart/native/windows-uwp-csharp/01-login.md
  articles/quickstart/native/wpf-winforms/01-login.md
  media/articles/flows/concepts/auth-sequence-auth-code-pkce.png
  media/articles/flows/concepts/auth-sequence-implicit-form-post.png
  media/articles/flows/concepts/auth-sequence-implicit.png
  media/articles/microsites/overview-flow-add-login-single-page-app-pkce.png
  media/articles/microsites/overview-flow-call-api-single-page-app-pkce.png
Labels: large, ready-for-review

#8816 Fix grant type for device flow token request
  articles/flows/guides/device-auth/includes/request-tokens.md
Labels: ready-for-review, tiny

#8820 Adding a PSaaS caveat
  articles/migrations/guides/passwordless-start.md
Labels: ready-for-review, tiny

#8819 Wording correction about production tenants
  articles/best-practices/tenant-settings.md
Labels: ready-for-review, tiny

#8802 Add explanation of why using Client Credentials flow
  articles/integrations/apigee.md
Labels: ready-for-review, tiny

#8827 Update IdP Access Token tutorial and remove webtasks
  articles/api/authentication/legacy/_login.md
  articles/connections/calling-an-external-idp-api.md
  articles/libraries/auth0-android/configuration.md
Labels: ready-for-review, small

#8835 Update Lock.swift main docs page
  articles/libraries/lock-ios/_includes/_dependencies.md
  articles/libraries/lock-ios/v2/index.md
Labels: small

#8833 Fixed Lock.swift custom fields docs
  articles/libraries/lock-ios/v2/custom-fields.md
Labels: tiny

#8834 Update Auth0.swift main docs page
  articles/libraries/auth0-swift/index.md
Labels: tiny

#8836 Add link to support center compliance download/request page
  articles/compliance/index.md
Labels: ready-for-review, tiny

#8829 React quickstart - resolve route params lost on redirect
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#8838 Match function in description to functions used in examples
  articles/libraries/auth0-spa-js/index.md
Labels: ready-for-review, tiny

#8844 Updated Getting Started Deployment Models
  articles/getting-started/deployment-models.md
Labels: ready-for-review, tiny

#8843 Replace dashboard screenshot
  articles/integrations/aws/sso.md
  media/articles/integrations/aws/addons.png
Labels: ready-for-review, small

#8841 Add note about session expiration
  articles/connections/database/password-change.md
  articles/sessions/index.md
  articles/support/reset-account-password.md
Labels: ready-for-review, tiny

#8842 Case iOS/RN Quickstart titles according to Style Guide
  articles/quickstart/native/ios-swift-siwa/00-login.md
  articles/quickstart/native/ios-swift-siwa/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/02-custom-login-form.md
  articles/quickstart/native/ios-swift/03-user-sessions.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/ios-swift/_includes/_login_embedded.md
  articles/quickstart/native/react-native/00-login.md
Labels: quickstart, ready-for-review, small

#8847 Add info on concurrent import users jobs
  articles/policies/rate-limits.md
  articles/users/guides/bulk-user-imports.md
Labels: ready-for-review, tiny

#8845 Removed Modify Scope Rule Examples
  articles/rules/references/samples.md
Labels: ready-for-review, tiny

#8846 Reset Email to Change Password
  articles/email/templates.md
Labels: ready-for-review, tiny

#8849 Link to blog post on active directory NTP sync
  articles/connector/troubleshooting.md
Labels: ready-for-review, tiny

#8856 Fix broken link, remove obsolete code
  articles/quickstart/backend/django/01-authorization.md
Labels: quickstart, tiny

#8860 Fix PHP WebApp Quickstart callback URL
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/download.md
Labels: quickstart, tiny

#8862 Adding documentation about MFA with new UL experience
  articles/multifactor-authentication/index.md
  articles/universal-login/multifactor-authentication.md
  media/articles/universal-login/new-ul-mfa1.png
  media/articles/universal-login/new-ul-mfa2.png
Labels: do-not-merge, small

#8861 Adding MFA language widget options
  articles/universal-login/multifactor-authentication.md
Labels: small

#8867 Updated SIWA quickstart to match repo
  articles/quickstart/native/ios-swift-siwa/00-login-siwa.md
  articles/quickstart/native/ios-swift-siwa/index.yml
Labels: tiny

#8868 Fixed SIWA article path
  articles/quickstart/native/ios-swift-siwa/00-login-siwa.md
Labels: tiny

#8869 Model class requires a public constructor
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#8865 Fixed broken link
  articles/protocols/saml/idp-initiated-sso.md
Labels: ready-for-review, tiny

#8866 Add instructions for updating app ownership when enabling third party…
  articles/api/management/guides/applications/update-ownership.md
  articles/applications/guides/enable-third-party-apps.md
Labels: ready-for-review, small
