Repository auth0/docs, pull requests merged in 2020-06, with the labels that each got.

#9104 Replacing images
  articles/integrations/marketing/adobe-campaign/index.md
  media/articles/integrations/marketing/import-export-fields.png
  media/articles/integrations/marketing/import-export-set-format.png
Labels: ready-for-review, tiny

#9114 Create OnFido Integration Redirect Rule doc
  articles/rules/guides/integrate-user-id-verification.md
  media/articles/rules/edit-onfido-rule.png
  media/articles/rules/enable-onfido-redirect-rule.png
  media/articles/rules/onfido-metadata-example.png
  media/articles/rules/onfido-verification-login1.png
  media/articles/rules/onfido-verify-identity.png
  media/articles/rules/onfido-verify-success.png
Labels: medium, ready-for-review

#9077 [DX-SDK] Auth0 React quickstart
  articles/quickstart/spa/_includes/_getting_started.md
  articles/quickstart/spa/auth0-react/01.md
  articles/quickstart/spa/auth0-react/download.md
  articles/quickstart/spa/auth0-react/index.yml
Labels: in-review, quickstart

#9118 Update link on React QS
  articles/quickstart/spa/auth0-react/01.md
Labels: tiny

#9108 Update creating-invite-only-applications.md
  articles/design/creating-invite-only-applications.md
  articles/design/index.md
Labels: medium, ready-for-review

#9116 New integrations using rules templates
  articles/dashboard/guides/rules/configure-variables.md
  articles/dashboard/guides/rules/create-rules.md
  articles/rules/guides/integrate-efm-solutions.md
  articles/rules/guides/integrate-hubspot.md
  articles/rules/guides/integrate-mixpanel.md
  articles/rules/guides/integrate-salesforce.md
  articles/rules/references/use-cases.md
  media/articles/dashboard/rules/rules-edit-rule.png
  media/articles/dashboard/rules/rules-list-empty.png
  media/articles/dashboard/rules/rules-list-with-rules-variables.png
  media/articles/dashboard/rules/rules-list-with-rules.png
  media/articles/dashboard/rules/rules-settings-add-variable.png
  media/articles/dashboard/rules/rules-templates.png
Labels: ready-for-review

#9126 Add set up connection to device flow prereqs
  articles/flows/guides/device-auth/includes/index.md
Labels: ready-for-review, small

#9128 Add ERFM integration
  articles/rules/guides/integrate-erfm-solutions.md
  articles/rules/references/use-cases.md
Labels: ready-for-review

#9124 New connections guides for Sandbox environments
  articles/connections/social/37signals.md
  articles/connections/social/amazon.md
  articles/connections/social/apple.md
  articles/connections/social/baidu.md
  articles/connections/social/bitbucket.md
  articles/connections/social/box.md
  articles/connections/social/docomo.md
  articles/connections/social/dropbox.md
  articles/connections/social/dwolla.md
  articles/connections/social/evernote-sandbox.md
  articles/connections/social/evernote.md
  articles/connections/social/exact.md
  articles/connections/social/facebook.md
  articles/connections/social/github.md
  articles/connections/social/goodreads.md
  articles/connections/social/google.md
  articles/connections/social/instagram.md
  articles/connections/social/line.md
  articles/connections/social/linkedin.md
  articles/connections/social/microsoft-account.md
  articles/connections/social/oauth2.md
  articles/connections/social/paypal-sandbox.md
  articles/connections/social/paypal.md
  articles/connections/social/planning-center.md
  articles/connections/social/renren.md
  articles/connections/social/salesforce-community.md
  articles/connections/social/salesforce-sandbox.md
  articles/connections/social/salesforce.md
  articles/connections/social/shopify.md
  articles/connections/social/soundcloud.md
  articles/connections/social/thecity.md
  articles/connections/social/twitter.md
  articles/connections/social/vkontakte.md
  articles/connections/social/weibo.md
  articles/connections/social/wordpress.md
  articles/connections/social/yahoo.md
  articles/connections/social/yammer.md
  articles/connections/social/yandex.md
Labels: ready-for-review

#9129 Add Shopify and MaxMind Rules template integrations
  articles/rules/guides/automatically-generate-leads-shopify.md
  articles/rules/guides/integrate-maxmind.md
  articles/rules/references/use-cases.md
Labels: do-not-merge, in-review

#9106 Quick fixes to wording in PC docs
  articles/appliance/disaster-recovery.md
  articles/appliance/geo-ha/index.md
  articles/private-cloud/add-ons.md
Labels: ready-for-review, small

#9097 Use npm instead of yarn
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart

#9132 Updates for Regional Domain Addition of US
  articles/connections/enterprise/oidc.md
  articles/custom-domains/additional-configuration.md
  articles/dev-lifecycle/setting-up-env.md
  articles/getting-started/create-tenant.md
  articles/libraries/_includes/_configure_custom_domain.md
  articles/libraries/lock/v11/migration-v10-v11.md
  articles/policies/endpoints.md
Labels: ready-for-review

#9105 Removing line that mentions further discussion that doesn't occur
  articles/users/concepts/overview-user-profile.md
Labels: ready-for-review, tiny

#9147 Correct mistake in PC note
  articles/mfa/guides/configure-sms.md
Labels: ready-for-review, tiny

#9149 Add Platform US 3 Note
  articles/custom-domains/additional-configuration.md
  articles/libraries/_includes/_configure_custom_domain.md
  articles/policies/endpoints.md
Labels: ready-for-review, tiny

#9127 Clarify Auth0 APIs option for Azure AD enterprise connection
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review

#9130 Add link to MFA API endpoint guide
  articles/mfa/concepts/mfa-factors.md
Labels: ready-for-review

#9131 Remove link to analytics section
  articles/extend-integrate/index.md
Labels: ready-for-review

#9138 Make passwordless-start migration guide public
  articles/migrations/guides/passwordless-start.md
  config/redirects.js
Labels: ready-for-review, small

#9155 Remove date commitment for Authz parity
  articles/_includes/_rbac_methods.md
Labels: ready-for-review, tiny

#9152 Update React Native version this QS was tested on
  articles/quickstart/native/react-native/index.yml
Labels: quickstart, tiny

#9160 Fix SIWA links/docs hidden
  articles/connections/social/apple.md
  config/redirects.js
Labels: ready-for-review

#9111 Update Social Connections Docs
  articles/connections/social/amazon.md
  articles/connections/social/apple.md
  articles/connections/social/baidu.md
  articles/connections/social/basecamp.md
  articles/connections/social/bitbucket.md
  articles/connections/social/box.md
  articles/connections/social/docomo.md
  articles/connections/social/dropbox.md
  articles/connections/social/dwolla.md
  articles/connections/social/evernote-sandbox.md
  articles/connections/social/exact.md
  articles/connections/social/facebook.md
  articles/connections/social/fitbit.md
  articles/connections/social/github.md
  articles/connections/social/goodreads.md
  articles/connections/social/google.md
  articles/connections/social/instagram.md
  articles/connections/social/line.md
  articles/connections/social/linkedin.md
  articles/connections/social/microsoft-account.md
  articles/connections/social/oauth2.md
  articles/connections/social/planning-center.md
  articles/connections/social/renren.md
  articles/connections/social/reprompt-permissions.md
  articles/connections/social/salesforce-community.md
  articles/connections/social/salesforce-sandbox.md
  articles/connections/social/shopify.md
  articles/connections/social/soundcloud.md
  articles/connections/social/twitter.md
  articles/connections/social/vkontakte.md
  articles/connections/social/weibo.md
  articles/connections/social/wordpress.md
  articles/connections/social/yahoo.md
  articles/connections/social/yammer.md
  articles/connections/social/yandex.md
  config/redirects.js
Labels: do-not-merge, in-review

#9095 initial version of page templates docs
  articles/architecture-scenarios/_includes/_branding/_universal-login.md
  articles/architecture-scenarios/_includes/_profile-mgmt/_password-reset.md
  articles/universal-login/classic.md
  articles/universal-login/customization-classic.md
  articles/universal-login/customization-new.md
  articles/universal-login/index.md
  articles/universal-login/new-experience-limitations.md
  articles/universal-login/new.md
  articles/universal-login/page-templates.md
  articles/universal-login/password-reset.md
  articles/universal-login/text-customization-prompts/_prompt_definition.md
  articles/universal-login/text-customization.md
Labels: do-not-merge

#9172 Fix typo
  articles/libraries/auth0-android/passwordless.md
Labels: tiny

#9162 Add Apple Mgmt API instructions
  articles/connections/social/apple.md
Labels: ready-for-review, small

#9183 Added note about US subdomains
  articles/getting-started/the-basics.md
Labels: ready-for-review, tiny

#9182 Added link to Entity Limits policy doc
  articles/design/using-auth0-with-multi-tenant-apps.md
Labels: ready-for-review, tiny

#9180 Updated links and descriptions for OAuth 2.0 in Protocols
  articles/api-auth/which-oauth-flow-to-use.md
  articles/protocols/oauth2/index.md
Labels: ready-for-review, small

#9136 Add log stream to Slack example and diagram
  articles/logs/streams/amazon-eventbridge.md
  articles/logs/streams/azure-event-grid.md
  articles/logs/streams/datadog.md
  articles/logs/streams/http-event-to-slack.md
  articles/logs/streams/http-event.md
  articles/logs/streams/index.md
  config/sidebar.yml
  media/articles/logs/log-stream-to-slack-diagram.png
  media/articles/logs/log-stream-to-slack-message.png
Labels: ready-for-review

#9185 [DX-SDK] Add React SDK quickstart: Call an API
  articles/quickstart/spa/auth0-react/01-login.md
  articles/quickstart/spa/auth0-react/02-calling-an-api.md
  articles/quickstart/spa/auth0-react/index.yml
Labels: quickstart

#9171 Auth0 React SDK library docs
  articles/_includes/_libraries_support_sdks.html
  articles/flows/concepts/auth-code-pkce.md
  articles/libraries/auth0-react/index.md
  articles/libraries/index.md
  config/sidebar.yml
  config/vars.yml
Labels: do-not-merge, medium, ready-for-review

#9181 Correct Rules Best Practice
  articles/best-practices/rules.md
Labels: do-not-merge, in-review

#9189 Release Auth0 React quickstart
  articles/quickstart/spa/auth0-react/01-login.md
  articles/quickstart/spa/auth0-react/02-calling-an-api.md
  articles/quickstart/spa/auth0-react/download.md
  articles/quickstart/spa/auth0-react/index.yml
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/react/_includes/_centralized_login.md
  articles/quickstart/spa/react/index.yml
Labels: quickstart

#9112 [MFA-162] Initial version of Voice MFA docs
  articles/api/authentication/_multifactor-authentication.md
  articles/appliance/infrastructure/internet-restricted-deployment.md
  articles/architecture-scenarios/_includes/_authentication/_mfa.md
  articles/best-practices/performance.md
  articles/branding-customization/index.md
  articles/compliance/gdpr/features-aiding-compliance/protect-user-data.md
  articles/connections/database/custom-db/templates/login.md
  articles/connections/passwordless/_includes/_setup-sms-twilio.md
  articles/getting-started/_list-processes.md
  articles/getting-started/deployment-models.md
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/send-phone-message.md
  articles/logs/references/log-event-type-codes.md
  articles/mfa/concepts/guardian.md
  articles/mfa/concepts/mfa-factors.md
  articles/mfa/guides/a.json
  articles/mfa/guides/configure-phone.md
  articles/mfa/guides/configure-sms.md
  articles/mfa/guides/customize-mfa-universal-login.md
  articles/mfa/guides/customize-phone-messages.md
  articles/mfa/guides/enable-mfa.md
  articles/mfa/guides/guardian/customize-sms-messages.md
  articles/mfa/guides/import-user-mfa.md
  articles/mfa/guides/mfa-api/authenticate.md
  articles/mfa/guides/mfa-api/manage.md
  articles/mfa/guides/mfa-api/multifactor-resource-owner-password.md
  articles/mfa/guides/mfa-api/otp.md
  articles/mfa/guides/mfa-api/phone.md
  articles/mfa/guides/mfa-api/push.md
  articles/mfa/references/troubleshoot-mfa.md
  articles/mfa/send-phone-message-hook-twilio.md
  articles/policies/rate-limits.md
  articles/pre-deployment/tests/required.md
  articles/quickstart/webapp/_includes/_mfa-introduction.md
  articles/rules/_includes/_context-prop-authentication.md
  articles/universal-login/new.md
  articles/users/references/bulk-import-database-schema-examples.md
  config/redirects.js
  config/sidebar.yml
  media/articles/mfa/mfa-dashboard.png
  media/articles/mfa/mfa-phone-settings.png
  media/articles/mfa/mfa-phone-templates.png
  media/articles/mfa/mfa-phone-twilio.png
  media/articles/mfa/mfa-sms-twilio.png
  media/articles/mfa/mfa-sms-voice.png
  media/articles/mfa/mfa-sms.png
  media/articles/mfa/mfa-sms1.png
  media/articles/mfa/mfa-sms2.png
  media/articles/mfa/sms-settings.png
Labels: do-not-merge

#9175 New Atlassian SAML app configuration
  articles/protocols/saml/index.html
  articles/protocols/saml/saml-apps/atlassian.md
  articles/protocols/saml/saml-apps/index.md
  media/articles/protocols/saml/atlassian-saml2-web-app-settings.png
Labels: ready-for-review, small

#9194 Code snippet updates
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart, tiny

#9199 Redirect auth0-react quickstart to react
  config/redirects.js
Labels: quickstart, tiny

#9159 [SDK-1672] Update OWIN QS to remove Kentor cookies and configure built-in middleware
  articles/quickstart/webapp/aspnet-owin/04-migrating.md
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
  articles/quickstart/webapp/aspnet-owin/index.yml
Labels: quickstart, small

#9200 Redirect fixup for /quickstart/spa/auth0-react/01
  config/redirects.js
Labels: quickstart, tiny

#8988 Update parameters for custom error page url
  articles/universal-login/custom-error-pages.md
Labels: in-review, small

#9196 OPEX-1323: A few improvements to the log codes page
  articles/logs/references/log-event-type-codes.md
Labels: do-not-merge

#9202 Fix express-jwt refs to algorithm
  articles/custom-domains/additional-configuration.md
  articles/quickstart/backend/rails/01-authorization.md
  articles/quickstart/spa/_includes/_calling_api_create_backend.md
  articles/quickstart/spa/_includes/_calling_api_create_backend_no_proxy.md
  articles/quickstart/spa/_includes/_calling_api_modify_backend.md
  articles/quickstart/spa/vanillajs/02-calling-an-api.md
  articles/users/references/user-data-storage-scenario.md
Labels: do-not-merge

#9205 Update 02-calling-an-api.md erroneous link to localhost
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart

#9208 email verification prompt docs
  articles/connections/azuread-adfs-email-verification.md
  articles/email/templates.md
  articles/users/guides/email-verified.md
  media/articles/connections/azuread-adfs-email-verification.png
Labels: do-not-merge
