Repository auth0/docs, pull requests merged in 2020-01, with the labels that each got.

#8584 New Redirect URI Formats and Restrictions
  articles/_includes/_redirect_uri_formats.md
  articles/architecture-scenarios/_includes/_authentication/_application-integration.md
  articles/dev-lifecycle/local-testing-and-development.md
  articles/logout/guides/redirect-users-after-logout.md
  articles/protocols/oauth2/redirect-users.md
  articles/protocols/reference/redirect-uri-formats.md
  articles/rules/guides/redirect.md
  articles/users/concepts/redirect-users-after-login.md
  config/redirects.js
  config/sidebar.yml
  updates/2016-11-02.yml
Labels: medium, ready-for-review

#8572 SAML error and tenant log data for anomaly detection
  articles/anomaly-detection/guides/use-tenant-data-for-anomaly-detection.md
  articles/anomaly-detection/index.md
  articles/logs/index.md
  articles/monitoring/index.md
  articles/protocols/saml/saml-configuration/troubleshoot/common-saml-errors.md
  config/sidebar.yml
  media/articles/anomaly-detection/anomaly-detection-features.png
  media/articles/anomaly-detection/traffic-failure-trends.png
Labels: ready-for-review, small

#8604 Rework Logs content
  articles/anomaly-detection/guides/use-tenant-data-for-anomaly-detection.md
  articles/appliance/monitoring/index.md
  articles/architecture-scenarios/_includes/_operations/_logging.md
  articles/dashboard/index.md
  articles/errors/deprecation-errors.md
  articles/extensions/splunk.md
  articles/flows/guides/device-auth/includes/index.md
  articles/flows/guides/device-auth/includes/troubleshooting.md
  articles/getting-started/deployment-models.md
  articles/integrations/aws-eventbridge.md
  articles/logs/concepts/logs-admins-devs.md
  articles/logs/guides/migrate-logs-v2-v3.md
  articles/logs/guides/retrieve-logs-mgmt-api.md
  articles/logs/guides/view-log-data-dashboard.md
  articles/logs/index.md
  articles/logs/references/log-data-retention.md
  articles/logs/references/log-event-data.md
  articles/logs/references/log-event-filters.md
  articles/logs/references/query-syntax.md
  articles/monitoring/guides/send-events-to-splunk.md
  articles/monitoring/index.md
  config/redirects.js
  config/sidebar.yml
  media/articles/logs/dashboard-logs.png
  media/articles/logs/log-event-filter.png
Labels: medium, ready-for-review

#8608 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#8611 Log Event Type Codes filename change
  articles/flows/guides/device-auth/includes/index.md
  articles/flows/guides/device-auth/includes/troubleshooting.md
  articles/logs/concepts/logs-admins-devs.md
  articles/logs/guides/retrieve-logs-mgmt-api.md
  articles/logs/guides/view-log-data-dashboard.md
  articles/logs/index.md
  articles/logs/references/log-data-retention.md
  articles/logs/references/log-event-filters.md
  articles/logs/references/log-event-type-codes.md
  articles/logs/references/query-syntax.md
  articles/monitoring/index.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small

#8504 Added migration guide and API docs for pwdless
  articles/api/authentication/_passwordless.md
  articles/connections/passwordless/reference/relevant-api-endpoints.md
  articles/libraries/auth0-android/passwordless.md
  articles/libraries/lock-android/v2/passwordless-magic-link.md
  articles/libraries/lock-android/v2/passwordless.md
  articles/libraries/lock-ios/v2/passwordless.md
  articles/migrations/guides/migration-oauthro-oauthtoken-pwdless.md
  articles/migrations/guides/passwordless-start.md
  articles/product-lifecycle/migrations.md
Labels: do-not-merge

#8496 Passwordless - Second Batch Changes - Overview, Factors, Implementation
  articles/api/authentication/_passwordless.md
  articles/applications/reference/grant-types-available.md
  articles/connections/_otp-limitations.md
  articles/connections/passwordless/_includes/_introduction-email-magic-link.md
  articles/connections/passwordless/_includes/_introduction-email.md
  articles/connections/passwordless/_includes/_introduction-sms.md
  articles/connections/passwordless/_includes/_rate_limit_server_side.md
  articles/connections/passwordless/_includes/_setup-cors.md
  articles/connections/passwordless/_includes/_setup-email.md
  articles/connections/passwordless/_includes/_setup-sms-twilio.md
  articles/connections/passwordless/_old/android-email.md
  articles/connections/passwordless/_old/android-sms.md
  articles/connections/passwordless/_old/android.md
  articles/connections/passwordless/_old/index-old.md
  articles/connections/passwordless/_old/ios-email-objc.md
  articles/connections/passwordless/_old/ios-email-swift.md
  articles/connections/passwordless/_old/ios-touch-id-objc.md
  articles/connections/passwordless/_old/ios-touch-id-swift.md
  articles/connections/passwordless/_old/ios.md
  articles/connections/passwordless/_old/native-passwordless-universal.md
  articles/connections/passwordless/_old/sms.md
  articles/connections/passwordless/_old/spa-sms.md
  articles/connections/passwordless/_old/spa.md
  articles/connections/passwordless/concepts/sample-use-cases-rules.md
  articles/connections/passwordless/guides/best-practices.md
  articles/connections/passwordless/guides/configure-login-page-embedded.md
  articles/connections/passwordless/guides/email-magic-link.md
  articles/connections/passwordless/guides/email-otp.md
  articles/connections/passwordless/guides/embedded-login-native.md
  articles/connections/passwordless/guides/embedded-login-spa.md
  articles/connections/passwordless/guides/embedded-login-webapps.md
  articles/connections/passwordless/guides/embedded-login.md
  articles/connections/passwordless/guides/implement-passwordless.md
  articles/connections/passwordless/guides/sms-otp.md
  articles/connections/passwordless/guides/universal-login.md
  articles/connections/passwordless/index.md
  articles/connections/passwordless/reference/troubleshoot.md
  articles/dashboard/guides/applications/set-up-cors.md
  articles/dashboard/guides/universal-login/configure-login-page-passwordless.md
  articles/link-accounts/user-initiated-linking.md
  config/redirects.js
  config/sidebar.yml
  media/articles/connections/passwordless/passwordless-email.png
  media/articles/connections/passwordless/passwordless-sms.png
Labels: do-not-merge

#8618 Fixed formatting issues in Passwordless iOS
  articles/libraries/auth0-swift/passwordless.md
Labels: ready-for-review, tiny

#8610 Update Tokens Best Practices
  articles/best-practices/index.md
  articles/best-practices/token-best-practices.md
  articles/tokens/access-tokens.md
  articles/tokens/guides/access-token/get-access-tokens.md
  articles/tokens/guides/access-token/use-access-tokens.md
  articles/tokens/guides/id-token/get-id-tokens.md
  articles/tokens/guides/jwt/validate-jwt.md
  articles/tokens/id-tokens.md
  articles/tokens/jwt-claims.md
  articles/tokens/jwt.md
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review, small

#8615 Update info on external identity provider refresh tokens
  articles/connections/_call-api.md
  articles/connections/social/google.md
  articles/tokens/overview-idp-access-tokens.md
Labels: ready-for-review, small

#8593 Added a small section to verify token signature algorithm to SPA quickstarts
  articles/_includes/_token_signature.md
  articles/quickstart/spa/_includes/_getting_started.md
  media/articles/applications/token-signature-algorithm.png
Labels: quickstart

#8623 Add non-custom domain assertion url example
  articles/protocols/saml/saml-sp-generic.md
Labels: ready-for-review, tiny

#8622 Update custom db connection error handling doc
  articles/connections/database/custom-db/error-handling.md
Labels: ready-for-review, tiny

#8624 [SDK-773] Removed a page that is no longer referenced
  articles/quickstart/spa/_includes/_authz_client_routes_disclaimer.md
Labels: quickstart, tiny

#8628 Clarification about cookie expiration
  articles/multifactor-authentication/custom.md
Labels: ready-for-review, tiny

#8627 Adding management API password change limitation
  articles/universal-login/new-experience-limitations.md
Labels: ready-for-review, tiny

#8620 Updating DAE rules step for clarity
  articles/extensions/delegated-admin/v3/index.md
Labels: ready-for-review, small

#8635 Revert "New Redirect URI Formats and Restrictions"
  articles/_includes/_redirect_uri_formats.md
  articles/architecture-scenarios/_includes/_authentication/_application-integration.md
  articles/dev-lifecycle/local-testing-and-development.md
  articles/logout/guides/redirect-users-after-logout.md
  articles/protocols/oauth2/redirect-users.md
  articles/protocols/reference/redirect-uri-formats.md
  articles/rules/guides/redirect.md
  articles/users/guides/redirect-users-after-login.md
  config/redirects.js
  config/sidebar.yml
  updates/2016-11-02.yml
Labels: ready-for-review, tiny

#8639 Update Java Regular Webapp Quickstarts
  articles/quickstart/webapp/java-ee/_includes/_login.md
  articles/quickstart/webapp/java-ee/_includes/_setup.md
  articles/quickstart/webapp/java-spring-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_login.md
  articles/quickstart/webapp/java-spring-security-mvc/_includes/_setup.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_setup.md
Labels: medium, quickstart

#8645 Update quickstart with direction from v0.6.0
  .github/CODEOWNERS
  articles/quickstart/webapp/express/01-login.md
Labels: quickstart, small

#8644 Move arch scenarios up in nav
  config/sidebar.yml
Labels: do-not-merge, in-review

#8641 Fix Spring MVC path issue
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#8648 Added logo sizing info to Universal Login
  articles/universal-login/index.md
  articles/universal-login/new.md
Labels: ready-for-review, tiny

#8634 Updating a subheading for clarity
  articles/connections/apple-siwa/set-up-apple.md
Labels: ready-for-review, tiny

#8651 AWS IAM UI updates
  articles/identity-labs/01-web-sign-in/index.md
  articles/identity-labs/02-calling-an-api/exercise-01.md
  articles/identity-labs/02-calling-an-api/index.md
  articles/identity-labs/03-mobile-native-app/exercise-01.md
  articles/identity-labs/03-mobile-native-app/index.md
  articles/identity-labs/04-single-page-app/index.md
  articles/identity-labs/_includes/_git-clone-note.md
  articles/identity-labs/_includes/_what-you-need.md
  articles/integrations/aws/sso.md
  media/articles/integrations/aws/aws-configure-provider.png
  media/articles/integrations/aws/aws-iam-configure-provider.png
  media/articles/integrations/aws/aws-iam-create-role-policies.png
  media/articles/integrations/aws/aws-iam-create-role-review.png
  media/articles/integrations/aws/aws-iam-create-role-tags.png
  media/articles/integrations/aws/aws-iam-create-role.png
  media/articles/integrations/aws/aws-iam-identity-providers.png
  media/articles/integrations/aws/aws-iam-roles.png
  media/articles/integrations/aws/create-provider-confirm.png
  media/articles/integrations/aws/create-provider.png
  media/articles/integrations/aws/iam-new-role.png
  media/articles/integrations/aws/iam-review-role.png
  media/articles/integrations/aws/select-role-type.png
  media/articles/integrations/aws/select-saml-provider-to-trust.png
Labels: ready-for-review, small

#8652 Add Mailgun email provider
  articles/connections/passwordless/_includes/_setup-email.md
  articles/email/providers.md
  articles/email/templates.md
  media/articles/dashboard/emails/providers/emails-providers-list.png
  media/articles/dashboard/emails/providers/emails-providers-settings-aws.png
  media/articles/dashboard/emails/providers/emails-providers-settings-mailgun.png
  media/articles/dashboard/emails/providers/emails-providers-settings-mandrill.png
  media/articles/dashboard/emails/providers/emails-providers-settings-sendgrid.png
  media/articles/dashboard/emails/providers/emails-providers-settings-smtp.png
  media/articles/dashboard/emails/providers/emails-providers-settings-sparkpost.png
  media/articles/email/providers/aws-keys.png
  media/articles/email/providers/email-mandrill-monitoring.png
  media/articles/email/providers/email-sendgrid-monitoring.png
  media/articles/email/providers/enter-keys.png
  media/articles/email/providers/enter-smtp-data.png
  media/articles/email/providers/mandrill-key.png
  media/articles/email/providers/mandrill-keygen.png
  media/articles/email/providers/sendgrid-dashboard.png
  media/articles/email/providers/sendgrid-key.png
  media/articles/email/providers/sendgrid-permissions.png
  media/articles/email/providers/sendgrid-test.png
  media/articles/email/providers/ses-smtp.png
  media/articles/email/providers/ses-verify.png
  media/articles/email/providers/sparkpost-api-key-creation.png
  media/articles/email/providers/sparkpost-message-events.png
  media/articles/email/providers/sparkpost-set-key.png
  media/articles/email/providers/token-generator.png
Labels: medium, ready-for-review

#8657 Added note about Keychain items in Auth0.swift documentation
  articles/libraries/auth0-swift/save-and-refresh-jwt-tokens.md
Labels: tiny

#8659 [IPS-867] Remove rate limits plicy for /authorize
  articles/policies/rate-limits.md
  updates/2020-01-20.yml
Labels: ready-for-review

#8621 Brute-Force Protection Email Updates
  articles/anomaly-detection/concepts/breached-passwords.md
  articles/anomaly-detection/guides/enable-disable-brute-force-protection.md
  articles/anomaly-detection/guides/set-anomaly-detection-preferences.md
  articles/anomaly-detection/index.md
  articles/anomaly-detection/references/anomaly-detection-faqs.md
  articles/anomaly-detection/references/anomaly-detection-restrictions-limitations.md
  articles/anomaly-detection/references/breached-password-detection-triggers-actions.md
  articles/anomaly-detection/references/brute-force-protection-triggers-actions.md
  articles/guides/login/migration-sso.md
  config/redirects.js
  config/sidebar.yml
  media/articles/anomaly-detection/anomaly-detection-overview.png
  media/articles/anomaly-detection/breached-password-shield.png
  media/articles/anomaly-detection/brute-force-shield.png
Labels: medium, ready-for-review

#8669 Updates to reflect current state of Dashboard
  articles/protocols/saml/saml-sp-generic.md
Labels: ready-for-review, small

#8674 Update _delete-tenant.md
  articles/support/_delete-tenant.md
Labels: ready-for-review

#8661 Update react code sample inline with sample changes
  articles/quickstart/spa/react/_includes/_centralized_login.md
Labels: quickstart, tiny

#8667 Added Note about adding Private Cloud Custom Domains
  articles/appliance/dashboard/tenants.md
Labels: ready-for-review, tiny

#8670 Minor updates to OIDC docs
  articles/protocols/oidc/index.md
  articles/tokens/concepts/jwt-claims.md
  articles/users/normalized/oidc/index.md
Labels: ready-for-review, tiny

#8676 Update all compliance info
  articles/compliance/index.md
Labels: do-not-merge

#8632 [ESD-3677] Incorrect Connection Update Example
  articles/security/blacklisting-attributes.md
Labels: tiny

#8662 [IPS-941] Add email requirements for Zendesk SSO integration
  articles/integrations/sso/_template.md
Labels: ready-for-review

#8681 Fix broken links on Compliance page
  articles/compliance/index.md
Labels: ready-for-review, tiny

#8563 Add glossary terms: confidential client and public client
  config/glossary.json
Labels: ready-for-review, small

#8685 Fixed broken link
  articles/logs/guides/view-log-data-dashboard.md
Labels: ready-for-review, tiny

#8679 Added note on MFA reset
  articles/best-practices/tenant-settings.md
  articles/dashboard/manage-dashboard-admins.md
Labels: ready-for-review, small

#8678 Added link to Azure consent
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review, tiny

#8677 Update rate-limits.md
  articles/policies/rate-limits.md
Labels: ready-for-review, tiny

#8686 Update Spring 5 API Quickstart to latest version
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#8682 Update using-resource-owner-password-from-server-side.md
  articles/api-auth/tutorials/using-resource-owner-password-from-server-side.md
Labels: ready-for-review, small

#8688 Update auth0-managed-certificates.md
  articles/custom-domains/auth0-managed-certificates.md
Labels: ready-for-review

#8673 Update Ionic4 Instructions
  articles/quickstart/native/ionic4/01-login.md
Labels: quickstart

#8698 Create draft of HTTP Event Streams
  articles/logs/index.md
  articles/logs/streams/aws-eventbridge.md
  articles/logs/streams/http-event.md
  articles/logs/streams/index.md
  config/redirects.js
  config/sidebar.yml
  media/articles/logs/http-event-stream.png
Labels: do-not-merge, in-review, small

#8707 Specifying Where to Place the ExternalAPI.js File
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart

#8699 Hooks section Rework
  articles/_includes/_ip_whitelist.md
  articles/api-auth/tutorials/client-credentials.md
  articles/api-auth/tutorials/client-credentials/customize-with-hooks.md
  articles/architecture-scenarios/_includes/_authorization/_m2m.md
  articles/architecture-scenarios/_includes/_deployment/_introduction.md
  articles/architecture-scenarios/_includes/_qa/_integration-testing.md
  articles/architecture-scenarios/_includes/_qa/_introduction.md
  articles/best-practices/custom-db-connections/execution.md
  articles/best-practices/rules.md
  articles/connections/database/custom-db/index.md
  articles/connections/database/password-change.md
  articles/dashboard/guides/roles/delete-roles.md
  articles/extend-integrate/index.md
  articles/extensions/deploy-cli/index.md
  articles/getting-started/whats-next.md
  articles/hooks/_includes/_access_hook_secrets.md
  articles/hooks/_includes/_default_hook_enable_behavior.md
  articles/hooks/_includes/_handle_rate_limits.md
  articles/hooks/_includes/_hook_enabled_limit.md
  articles/hooks/_includes/_hook_secrets_limit.md
  articles/hooks/_includes/_test_runner_save_warning.md
  articles/hooks/_includes/set-up-webtask-cli.md
  articles/hooks/client-credentials-exchange.md
  articles/hooks/create.md
  articles/hooks/delete.md
  articles/hooks/enable-disable.md
  articles/hooks/extensibility-points/client-credentials-exchange.md
  articles/hooks/extensibility-points/index.md
  articles/hooks/extensibility-points/post-change-password.md
  articles/hooks/extensibility-points/post-user-registration.md
  articles/hooks/extensibility-points/pre-user-registration.md
  articles/hooks/index.md
  articles/hooks/logs.md
  articles/hooks/post-change-password.md
  articles/hooks/post-user-registration.md
  articles/hooks/pre-user-registration.md
  articles/hooks/secrets/create.md
  articles/hooks/secrets/delete.md
  articles/hooks/secrets/index.md
  articles/hooks/secrets/update.md
  articles/hooks/secrets/view.md
  articles/hooks/update.md
  articles/hooks/view-logs.md
  articles/hooks/view.md
  articles/tokens/guides/create-namespaced-custom-claims.md
  config/redirects.js
  config/sidebar.yml
Labels: do-not-merge, in-review
