Repository auth0/docs, pull requests merged in 2021-11, with the labels that each got.

#9910 [DXDOCS-224] feat: rename libraries section to sdks
  config/sections.yml
Labels: do-not-merge, quantum

#9917 Qs screenshot updates
  articles/quickstart/spa/angular/01-login.md
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/java-ee/_includes/_login.md
  articles/quickstart/webapp/java-spring-boot/01-login.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/nextjs/01-login.md
  articles/quickstart/webapp/nodejs/01-login.md
  media/articles/api-auth/create-api.png
  media/articles/api-auth/create-client.png
  media/articles/api-auth/create-scope.png
  media/articles/api-auth/default-directory-setting.png
  media/articles/dashboard/client_settings.png
  media/articles/ios/swift/add-capability.png
  media/articles/native-platforms/windows-uwp-csharp/universal-login.png
  media/articles/native-platforms/wpf-winforms/universal-login.png
  media/articles/rules/rule-choose-add-country-template.png
  media/articles/rules/rule-create-add-country-country.png
  media/articles/server-apis/authorize-m2m-for-api.png
  media/articles/server-apis/configure-permissions.png
  media/articles/server-apis/create-api.png
  media/quickstarts/universal-login.png
Labels: do-not-merge

#9923 Use correct path for data-code in react QS
  articles/quickstart/spa/react/interactive.md
Labels: quickstart
