Repository auth0/docs, pull requests merged in 2021-04, with the labels that each got.

#9679 Redirect Mgmt API v1 Migration guide to Past Migrations
  config/redirects.js
Labels: ready-for-review

#9680 Fix allowed callback URL in Spring Boot Quickstart download instructions
  articles/quickstart/webapp/java-spring-boot/download.md
Labels: quickstart

#9681 Add new prompt screenshots for Orgs
  media/articles/universal-login/text-customization/accept-invitation.png
  media/articles/universal-login/text-customization/organization-selection.png
Labels: ready-for-review

#9682 Add Organizations Nav
  config/sidebar.yml
Labels: ready-for-review

#9683 Move Orgs config section
  config/sidebar.yml
Labels: ready-for-review

#9685 Pass the issuer as an array of strings [ESD-12786]
  articles/quickstart/backend/nodejs/01-authorization.md
Labels: quickstart, tiny

#9674 Add redirects, update sidebar, update included folders for arch scens
  articles/connections/identity-providers-social.md
  config/included-folders.yml
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9686 new section added
  articles/connections/enterprise/saml.md
Labels: do-not-merge, ready-for-review

#9690 Dr 1042 error handling update
  articles/connections/database/custom-db/_includes/_bp-error-object.md
  articles/connections/database/custom-db/error-handling.md
Labels: ready-for-review

#9687 Update sidebar to add Adaptive MFA links
  config/sidebar.yml
Labels: ready-for-review

#9692 Add note to the Swift Quickstart about a skippable step iOS 12+
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
Labels: quickstart

#9688 Added Multiple Organization Architecture Scenario
  config/sidebar.yml
Labels: ready-for-review

#9696 Add Deploy landing page and update links
  config/sidebar.yml
Labels: ready-for-review

#9698 Deploy CLI Redirects
  config/redirects.js
Labels: ready-for-review

#9702 Update download instructions for Android sample [ESD-12922]
  articles/architecture-scenarios/mobile-api/mobile-implementation-android.md
  articles/quickstart/native/android/download.md
Labels: quickstart

#9697 Security Sidebar link update
  config/sidebar.yml
Labels: ready-for-review

#9691 Fixed redirect to /protocols/saml-protocol
  config/redirects.js
Labels: ready-for-review

#9701 Signing Keys sidebar and redirect updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9708 Brand & Customize sidebar and redirect
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9713 Troubleshoot sidebar and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9714 Add redirect for ping federate saml idp config doc
  config/redirects.js
Labels: ready-for-review

#9715 Security landing pages, redirects, and sidebar updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review
