Repository auth0/docs, pull requests merged in 2021-09, with the labels that each got.

#9867 Add user import redirect
  config/redirects.js
Labels: ready-for-review

#9869 Add QS redirects - new PR
  config/redirects.js
Labels: ready-for-review

#9870 Add redirects for Manhattan broken links
  config/redirects.js
Labels: ready-for-review

#9871 Deploy CLI Tools redirect
  config/redirects.js
Labels: ready-for-review

#9874 Update redirects.js
  config/redirects.js
Labels: do-not-merge

#9877 [Ionic] Patch download.md to include web origin for Android
  articles/quickstart/native/ionic-angular/download.md
  articles/quickstart/native/ionic-react/download.md
Labels: quickstart

#9879 [SDK-2789] Update references to ASP.NET SDK
  articles/quickstart/webapp/aspnet-core-beta/01-login.md
  articles/quickstart/webapp/aspnet-core-beta/index.yml
Labels: do-not-merge, quickstart

#9880 Release Auth0-PHP 8.0.0
  articles/quickstart/backend/php-beta/01-authorization.md
  articles/quickstart/backend/php-beta/02-using.md
  articles/quickstart/backend/php-beta/03-troubleshooting.md
  articles/quickstart/backend/php-beta/download.md
  articles/quickstart/backend/php-beta/index.yml
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/backend/php/02-using.md
  articles/quickstart/backend/php/03-troubleshooting.md
  articles/quickstart/backend/php/download.md
  articles/quickstart/backend/php/index.yml
  articles/quickstart/webapp/php-beta/01-login.md
  articles/quickstart/webapp/php-beta/download.md
  articles/quickstart/webapp/php-beta/index.yml
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/download.md
  articles/quickstart/webapp/php/index.yml
  snippets/server-platforms/php/dependencies.md
  snippets/server-platforms/php/install.md
  snippets/server-platforms/php/setup.md
  snippets/server-platforms/php/use.md
Labels: tiny

#9883 Clarify using manifest placeholders and schemes
  articles/quickstart/native/android/00-login.md
Labels: quickstart, small

#9881 Updates to PHP SDK documentation
  articles/libraries/auth0-php/authentication-api.md
  articles/libraries/auth0-php/basic-use.md
  articles/libraries/auth0-php/index.md
  articles/libraries/auth0-php/jwt-validation.md
  articles/libraries/auth0-php/management-api.md
  articles/libraries/auth0-php/troubleshooting.md
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/backend/php/index.yml
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/index.yml
Labels: small
