Repository auth0/docs, pull requests merged in 2021-02, with the labels that each got.

#9595 Manage Dashboard Access redirects and sidebar updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9254 Archive outdated library migration guides
  articles/_includes/_version_warning_lock.md
  articles/connections/passwordless/_old/ios-magic-link.md
  articles/libraries/auth0-spa-js/index.md
  articles/libraries/auth0-spa-js/migrate-from-auth0js.md
  articles/libraries/auth0js/v9/migration-angular.md
  articles/libraries/auth0js/v9/migration-angularjs-v6.md
  articles/libraries/auth0js/v9/migration-angularjs-v7.md
  articles/libraries/auth0js/v9/migration-angularjs-v8.md
  articles/libraries/auth0js/v9/migration-guide.md
  articles/libraries/auth0js/v9/migration-react.md
  articles/libraries/auth0js/v9/migration-v6-v9.md
  articles/libraries/auth0js/v9/migration-v7-v9.md
  articles/libraries/auth0js/v9/migration-v8-v9.md
  articles/libraries/lock-android/_includes/_lock-version.md
  articles/libraries/lock-android/v1/configuration.md
  articles/libraries/lock-android/v1/delegation-api.md
  articles/libraries/lock-android/v1/index.md
  articles/libraries/lock-android/v1/internationalization.md
  articles/libraries/lock-android/v1/native-social-authentication.md
  articles/libraries/lock-android/v1/passwordless-magic-link.md
  articles/libraries/lock-android/v1/passwordless.md
  articles/libraries/lock-android/v1/refresh-jwt-tokens.md
  articles/libraries/lock-android/v1/sending-authentication-parameters.md
  articles/libraries/lock-android/v1/use-your-own-ui.md
  articles/libraries/lock-android/v2/index.md
  articles/libraries/lock-android/v2/migration-guide.md
  articles/libraries/lock-ios/_includes/_lock-version-1.md
  articles/libraries/lock-ios/_includes/_lock-version.md
  articles/libraries/lock-ios/v1/customization.md
  articles/libraries/lock-ios/v1/delegation-api.md
  articles/libraries/lock-ios/v1/index.md
  articles/libraries/lock-ios/v1/lock-ios-api.md
  articles/libraries/lock-ios/v1/logging.md
  articles/libraries/lock-ios/v1/native-social-authentication.md
  articles/libraries/lock-ios/v1/password-reset-ios.md
  articles/libraries/lock-ios/v1/passwordless.md
  articles/libraries/lock-ios/v1/save-and-refresh-jwt-tokens.md
  articles/libraries/lock-ios/v1/sending-authentication-parameters.md
  articles/libraries/lock-ios/v1/swift.md
  articles/libraries/lock-ios/v1/use-your-own-ui.md
  articles/libraries/lock-ios/v2/migration.md
  articles/libraries/lock/v11/migration-angular.md
  articles/libraries/lock/v11/migration-angularjs-v10.md
  articles/libraries/lock/v11/migration-angularjs-v8.md
  articles/libraries/lock/v11/migration-angularjs-v9.md
  articles/libraries/lock/v11/migration-cordova.md
  articles/libraries/lock/v11/migration-guide.md
  articles/libraries/lock/v11/migration-lock-passwordless.md
  articles/libraries/lock/v11/migration-react.md
  articles/libraries/lock/v11/migration-v10-v11.md
  articles/libraries/lock/v11/migration-v8-v11.md
  articles/libraries/lock/v11/migration-v9-v11.md
  articles/migrations/guides/legacy-lock-api-deprecation.md
  articles/pre-deployment/tests/required.md
  articles/security/bulletins/cve-2018-6874.md
  config/sidebar.yml
Labels: medium, ready-for-review

#9605 [React Quickstart] Update chapter 2 to allow choosing an API when downloading the sample
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart, ready-for-review, tiny

#9607 Fixed sidebar errors
  config/sidebar.yml
Labels: ready-for-review

#9608 Reorder sidebar items under Custom Domains
  config/sidebar.yml
Labels: ready-for-review

#9609 Update requirements for Xamarin
  articles/quickstart/native/xamarin/index.yml
Labels: tiny

#9611 Update paths and requirements for the .NET Core quickstarts
  articles/quickstart/webapp/aspnet-core-2/00-intro.md
  articles/quickstart/webapp/aspnet-core-2/01-login.md
  articles/quickstart/webapp/aspnet-core-2/02-user-profile.md
  articles/quickstart/webapp/aspnet-core-2/03-authorization.md
  articles/quickstart/webapp/aspnet-core-2/_includes/_login.md
  articles/quickstart/webapp/aspnet-core-2/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core-2/download.md
  articles/quickstart/webapp/aspnet-core-2/index.yml
  articles/quickstart/webapp/aspnet-core/01-login.md
  articles/quickstart/webapp/aspnet-core/02-user-profile.md
  articles/quickstart/webapp/aspnet-core/03-authorization.md
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
  articles/quickstart/webapp/aspnet-core/_includes/_setup.md
  articles/quickstart/webapp/aspnet-core/download.md
  articles/quickstart/webapp/aspnet-core/index.yml
  config/redirects.js
Labels: quickstart, ready-for-review, tiny

#9613 Add missing articles to sidebar for Android SDK
  config/sidebar.yml
Labels: ready-for-review, small

#9612 Update callbacks for improved null behavior
  articles/quickstart/native/android-vnext/00-login.md
  articles/quickstart/native/android-vnext/01-user-metadata.md
Labels: small

#9614 Take Android vnext quickstart out of beta
  articles/quickstart/native/android-vnext/00-login.md
  articles/quickstart/native/android-vnext/01-user-metadata.md
  articles/quickstart/native/android-vnext/index.yml
Labels: quickstart, small

#9615 Replace old android quickstarts with the new version
  articles/quickstart/native/android-vnext/00-login.md
  articles/quickstart/native/android-vnext/download.md
  articles/quickstart/native/android-vnext/index.yml
  articles/quickstart/native/android/00-login.md
  articles/quickstart/native/android/01-embedded-login.md
  articles/quickstart/native/android/01-user-metadata.md
  articles/quickstart/native/android/02-custom-login-form.md
  articles/quickstart/native/android/03-session-handling.md
  articles/quickstart/native/android/04-user-profile.md
  articles/quickstart/native/android/05-linking-accounts.md
  articles/quickstart/native/android/06-calling-apis.md
  articles/quickstart/native/android/07-authorization.md
  articles/quickstart/native/android/_includes/_api_authz.md
  articles/quickstart/native/android/_includes/_auth0.md
  articles/quickstart/native/android/_includes/_callback_urls.md
  articles/quickstart/native/android/_includes/_credentials.md
  articles/quickstart/native/android/_includes/_gradle.md
  articles/quickstart/native/android/_includes/_lock.md
  articles/quickstart/native/android/_includes/_lock_login.md
  articles/quickstart/native/android/_includes/_lock_manifest.md
  articles/quickstart/native/android/_includes/_login.md
  articles/quickstart/native/android/download.md
  articles/quickstart/native/android/getting-started.md
  articles/quickstart/native/android/index.yml
Labels: quickstart

#9616 Add link to older releases for Android Quickstart
  articles/quickstart/native/android/index.yml
Labels: quickstart

#9618 Update rules to redirect to the new android quickstart
  config/redirects.js
Labels: ready-for-review, tiny

#9621 Remove beta status from Next.js QuickStart
  articles/quickstart/webapp/nextjs/01-login.md
  articles/quickstart/webapp/nextjs/index.yml
Labels: quickstart, tiny

#9626 Replace ASP.NET Core 3.x with ASP.NET Core in Web App Quickstart
  articles/quickstart/webapp/aspnet-core/01-login.md
Labels: tiny

#9628 Add Support Center Users link to Sidebar
  config/sidebar.yml
Labels: ready-for-review

#9617 Add note about customizing apple login page
  snippets/social/apple/0.md
Labels: ready-for-review, tiny

#9598 Clarify shopify connection usage
  snippets/social/shopify/0.md
Labels: ready-for-review

#9620 Update System Requirements for WPF/Winforms
  articles/quickstart/native/wpf-winforms/index.yml
Labels: quickstart, tiny

#9476 Adding Pluck from RXJS
  articles/quickstart/spa/angular/02-calling-an-api.md
Labels: quickstart

#9629 Update ASPNET Owin MVC QS to use CookieManager
  articles/quickstart/webapp/aspnet-owin/_includes/_login.md
Labels: quickstart, tiny

#9631 Update the nextjs logo
  articles/quickstart/webapp/nextjs/index.yml
Labels: tiny

#9632 Deprecate Deployment Extensions
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9627 SAML Configuration sidebar updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review
