Repository auth0/docs, pull requests merged in 2021-06, with the labels that each got.

#9739 Fix typo in Slack SSO Integration doc
  snippets/sso-integrations/slack/6.md
Labels: ready-for-review, tiny

#9647 Add notes linking to Authentication Guides to the QuickStarts
  articles/quickstart/spa/angular/01-login.md
  articles/quickstart/spa/angular/02-calling-an-api.md
  articles/quickstart/spa/react/01-login.md
  articles/quickstart/spa/react/02-calling-an-api.md
  articles/quickstart/spa/vuejs/01-login.md
  articles/quickstart/spa/vuejs/02-calling-an-api.md
  articles/quickstart/webapp/express/01-login.md
Labels: quickstart, small

#9755 Fixed broken redirect - log stream filters
  config/redirects.js
Labels: ready-for-review

#9743 Change Office 365 SSO tutorial from deprecated tool
  snippets/sso-integrations/office-365/6.md
Labels: ready-for-review

#9757 Add entity limit redirects
  config/redirects.js
Labels: ready-for-review

#9758 Add instructions for Redirect URI type selection
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review

#9759 Add Rules Best Practices Children
  config/sidebar.yml
Labels: ready-for-review

#9768 Update the RN QS for the SDK v2.9.0 [SDK-2620]
  articles/quickstart/native/react-native/00-login.md
Labels: do-not-merge, quickstart

#9762 Bot Detection sidebar changes
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9736 Remove unused dependency reference from ASPNET Core Quickstart
  articles/quickstart/webapp/aspnet-core/_includes/_login.md
Labels: tiny

#9774 Add organization parameters
  articles/api/authentication/api-authz/_authz-client.md
Labels: ready-for-review

#9771 Add link to Changelog under Support sidebar menu
  config/sidebar.yml
Labels: ready-for-review

#9776 Update sidebar.yml
  config/sidebar.yml
Labels: ready-for-review
