Repository auth0/docs, pull requests merged in 2021-03, with the labels that each got.

#9635 Update redirects.js
  config/redirects.js
Labels: ready-for-review

#9603 Rails 6 Quickstarts
  articles/quickstart/webapp/rails/01-login.md
  articles/quickstart/webapp/rails/02-session-handling.md
  articles/quickstart/webapp/rails/02-troubleshooting.md
  articles/quickstart/webapp/rails/03-user-profile.md
  articles/quickstart/webapp/rails/index.yml
Labels: quickstart

#9649 Update _introduction-sms.md
  articles/connections/passwordless/_includes/_introduction-sms.md
Labels: ready-for-review

#9651 login redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9653 More Login parent link updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9652 SSO Integrations doc link updates
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9659 Updated link in docomo connection steps
  snippets/social/docomo/3.md
Labels: ready-for-review

#9650 Update 01-login.md
  articles/quickstart/webapp/rails/01-login.md
Labels: quickstart

#9661 Rename screenshot
  media/articles/dashboard/sso-integrations/dashboard-integrations-sso-create_consent.png
  media/articles/dashboard/sso-integrations/dashboard-integrations-sso-create_list.png
  media/articles/dashboard/sso-integrations/dashboard-integrations-sso-create_select-service.png
  media/articles/dashboard/sso-integrations/dashboard-integrations-sso-create_settings.png
  media/articles/dashboard/sso-integrations/dashboard-integrations-sso-create_view-tutorial.png
  snippets/sso-integrations/ad-rms/3.md
  snippets/sso-integrations/adobe-sign/3.md
  snippets/sso-integrations/box/3.md
  snippets/sso-integrations/cisco-webex/3.md
  snippets/sso-integrations/cloudbees/3.md
  snippets/sso-integrations/concur/3.md
  snippets/sso-integrations/datadog/3.md
  snippets/sso-integrations/dropbox/3.md
  snippets/sso-integrations/dynamics-crm/3.md
  snippets/sso-integrations/egencia/3.md
  snippets/sso-integrations/egnyte/3.md
  snippets/sso-integrations/eloqua/3.md
  snippets/sso-integrations/freshdesk/3.md
  snippets/sso-integrations/g-suite/3.md
  snippets/sso-integrations/github-enterprise-cloud/3.md
  snippets/sso-integrations/github-enterprise-server/3.md
  snippets/sso-integrations/heroku/3.md
  snippets/sso-integrations/hosted-graphite/3.md
  snippets/sso-integrations/litmos/3.md
  snippets/sso-integrations/new-relic/3.md
  snippets/sso-integrations/office-365/3.md
  snippets/sso-integrations/pluralsight/3.md
  snippets/sso-integrations/salesforce/3.md
  snippets/sso-integrations/sentry/3.md
  snippets/sso-integrations/sharepoint/3.md
  snippets/sso-integrations/slack/3.md
  snippets/sso-integrations/springcm/3.md
  snippets/sso-integrations/sprout-video/3.md
  snippets/sso-integrations/tableau-online/3.md
  snippets/sso-integrations/tableau-server/3.md
  snippets/sso-integrations/workday/3.md
  snippets/sso-integrations/workpath/3.md
  snippets/sso-integrations/zendesk/3.md
  snippets/sso-integrations/zoom/3.md
Labels: ready-for-review

#9664 Attack Protection sidebar updates and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9666 Revert changes from /flows/login parent
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9648 Add Custom Domain item to sidebar
  config/sidebar.yml
Labels: do-not-merge

#9667 Docs 1659 sessions cookies
  articles/users/_includes/_account-linking-id-tokens.md
  config/redirects.js
  config/sidebar.yml
Labels: do-not-merge

#9640 update typo in maven dependency
  articles/quickstart/webapp/java-spring-boot/01-login.md
Labels: quickstart
