Repository auth0/docs, pull requests merged in 2021-05, with the labels that each got.

#9728 [SDK-2574] Remove Auth0 SDK listing from Spring 5 API Quickstart metadata
  articles/quickstart/backend/java-spring-security5/index.yml
Labels: quickstart, tiny

#9689 Add log stream filters to sidebar
  config/sidebar.yml
Labels: ready-for-review

#9730 [SDK-2567] Remove Spring 4 API Quickstart
  articles/quickstart/backend/java-spring-security/01-authorization.md
  articles/quickstart/backend/java-spring-security/02-using.md
  articles/quickstart/backend/java-spring-security/03-troubleshooting.md
  articles/quickstart/backend/java-spring-security/download.md
  articles/quickstart/backend/java-spring-security/index.yml
  articles/quickstart/backend/java-spring-security5/index.yml
Labels: quickstart, small

#9731 Change sidebar titles under Configuration section
  config/sidebar.yml
Labels: ready-for-review

#9700 Retitle documentation to read Authorization
  articles/quickstart/backend/rails/01-authorization.md
Labels: quickstart

#9735 Add passwordless webauthn device biometrics and email or sms docs to sidebar
  config/sidebar.yml
Labels: ready-for-review

#9733 Connect Your App to Microsoft Azure Active Directory connections doc fix
  articles/connections/enterprise/azure-active-directory/v2/index.md
Labels: ready-for-review, tiny

#9734 Move Logs under Monitor in sidebar
  config/redirects.js
  config/sidebar.yml
Labels: medium, ready-for-review
