Repository auth0/docs, pull requests merged in 2021-07, with the labels that each got.

#9778 [SDK-2612] Update PHP Quickstarts for SDK 8.0 Beta
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/backend/php/download.md
  articles/quickstart/backend/php/index.yml
  articles/quickstart/webapp/php/01-login.md
  articles/quickstart/webapp/php/download.md
  articles/quickstart/webapp/php/index.yml
  snippets/server-platforms/php/dependencies.md
  snippets/server-platforms/php/install.md
  snippets/server-platforms/php/setup.md
  snippets/server-platforms/php/use.md
Labels: medium, quickstart

#9791 Remove Postman and changelog links
  config/sidebar.yml
Labels: ready-for-review

#9792 Get Started Sidebar changes and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9795 Add redirect for removed Postman file
  config/redirects.js
Labels: ready-for-review

#9796 Update iOS login screenshot
  media/articles/native-platforms/ios-swift/lock_centralized_login.png
Labels: quickstart, tiny

#9793 Update RWA Quickstarts to use updated ULP screenshot
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/java-ee/_includes/_login.md
  articles/quickstart/webapp/java/_includes/_login.md
  articles/quickstart/webapp/nodejs/01-login.md
Labels: quickstart, tiny

#9790 PHP SDK 8.0: Link to beta quickstarts from stable quickstarts
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/webapp/php/01-login.md
Labels: tiny

#9783 Remove "$" from bash snippets
  articles/connections/generic-oauth2-connection-examples.md
  articles/libraries/lock-android/v2/passwordless-magic-link.md
  articles/login/spa/authenticate-with-cookies.md
  articles/logs/streams/http-event-to-slack.md
  articles/quickstart/backend/django/01-authorization.md
  articles/quickstart/backend/laravel/01-authorization.md
  articles/quickstart/native/ionic4/01-login.md
  articles/quickstart/spa/vanillajs/02-calling-an-api.md
  articles/quickstart/spa/vanillajs/_includes/_centralized_login.md
  articles/quickstart/webapp/django/01-login.md
  articles/quickstart/webapp/rails/01-login.md
  articles/security/bulletins/cve-2018-11537.md
Labels: small

#9803 Update mobile login screenshots
  articles/quickstart/native/android/00-login.md
  articles/quickstart/native/ios-swift/_includes/_login_centralized.md
  articles/quickstart/native/react-native/00-login.md
  articles/quickstart/native/xamarin/01-login.md
  media/articles/native-platforms/android/login-android.png
  media/articles/native-platforms/ios-swift/lock_centralized_login.png
  media/articles/native-platforms/ios-swift/login-ios.png
  media/articles/native-platforms/xamarin/universal-login.png
Labels: quickstart, tiny

#9801 Brand and Customize Sidebar Fixes
  config/sidebar.yml
Labels: ready-for-review

#9804 Update sidebar.yml
  config/sidebar.yml
Labels: ready-for-review

#9806 Sidebar updates for Organizations and Actions
  config/sidebar.yml
Labels: ready-for-review

#9807 API Settings sidebar and redirects
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9812 URL slug redirect and sidebar update
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9815 Fix snippet in Touch ID / Face ID QS
  articles/libraries/auth0-swift/touchid-authentication.md
Labels: quickstart, tiny

#9808 nginx+ quickstart
  articles/quickstart/webapp/nginx-plus/01-login.md
  articles/quickstart/webapp/nginx-plus/index.yml
  media/platforms/nginx-plus.png
  snippets/server-platforms/nginx-plus/copy.md
  snippets/server-platforms/nginx-plus/dependencies.md
  snippets/server-platforms/nginx-plus/logout.md
  snippets/server-platforms/nginx-plus/module.md
  snippets/server-platforms/nginx-plus/setup.md
  snippets/server-platforms/nginx-plus/token.md
  snippets/server-platforms/nginx-plus/use.md
Labels: quickstart

#9763 [Quickstart] Ionic 5, Capacitor, Auth0 React quickstart
  articles/quickstart/_includes/_auth0-react-classes-info.md
  articles/quickstart/_includes/_auth0-react-install.md
  articles/quickstart/native/ionic-react/01-login.md
  articles/quickstart/native/ionic-react/download.md
  articles/quickstart/native/ionic-react/index.yml
  articles/quickstart/spa/react/01-login.md
Labels: in-review, medium, quickstart

#9784 [SDK-2535] Ionic 5, Capacitor & Auth0 Angular quickstart
  articles/quickstart/_includes/_auth0-angular-install.md
  articles/quickstart/native/_includes/ionic/_add_login_intro.md
  articles/quickstart/native/_includes/ionic/_add_logout_intro.md
  articles/quickstart/native/_includes/ionic/_article_intro.md
  articles/quickstart/native/_includes/ionic/_configure_urls.md
  articles/quickstart/native/_includes/ionic/_handle_callback_intro.md
  articles/quickstart/native/_includes/ionic/_install_plugins.md
  articles/quickstart/native/_includes/ionic/_note_custom_schemes.md
  articles/quickstart/native/_includes/ionic/_note_storage.md
  articles/quickstart/native/ionic-angular/01-login.md
  articles/quickstart/native/ionic-angular/download.md
  articles/quickstart/native/ionic-angular/index.yml
  articles/quickstart/native/ionic-react/01-login.md
  articles/quickstart/native/ionic4/download.md
  articles/quickstart/native/ionic4/index.yml
  articles/quickstart/spa/angular/01-login.md
  config/redirects.js
Labels: large, quickstart

#9816 Fix closing backtick in NGINX quickstart
  snippets/server-platforms/nginx-plus/use.md
Labels: quickstart, tiny

#9818 Sidebar updates for best practices and support sections
  config/sidebar.yml
Labels: ready-for-review

#9822 Fix GitHub integration for Ionic quickstart
  articles/quickstart/native/ionic-angular/index.yml
  articles/quickstart/native/ionic-react/index.yml
  articles/quickstart/native/ionic4/01-login.md
Labels: quickstart, tiny

#9819 Update sidebar.yml
  config/sidebar.yml
Labels: ready-for-review

#9823 Auth0-PHP SDK 8.0 Beta; update panel text referencing new beta SDK, quickstarts, etc.
  articles/quickstart/backend/php/01-authorization.md
  articles/quickstart/webapp/php/01-login.md
Labels: tiny

#9824 Arch Scenarios - sidebar fix
  config/redirects.js
  config/sidebar.yml
Labels: ready-for-review

#9826 Add section to Connections Enterprise SAML doc
  articles/connections/enterprise/saml.md
Labels: ready-for-review

#9827 Simplify Spring Security Dependencies
  articles/quickstart/backend/java-spring-security5/01-authorization.md
Labels: quickstart, tiny

#9830 Fix Android quickstart link 404
  articles/quickstart/native/android/01-user-metadata.md
Labels: quickstart, small

#9639 Update dependency array for React Quickstart (Calling an API)
  articles/quickstart/spa/react/02-calling-an-api.md
Labels: quickstart
